namespace CStructSharp.Generated.Parity;

using System;
using System.Buffers;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using CStructSharp.Diagnostics;

/// <summary>
///     Checks that <see cref="ReadOptions.MaxTotalBytesRead"/> counts the bytes a parse consumes, each byte once, in the
///     runtime and in the generated reader and on every input form: the smallest budget a parse succeeds with is the
///     bytes the value consumes, and one byte less fails with <see cref="CStructReadLimitException"/>. A terminated
///     array's scan for its terminator, a terminated string's read-ahead past its terminator, alignment padding, and the
///     bytes a pointer jumps over are not charged, so the buffered forms (a segmented sequence, the stream forms that
///     buffer, the async forms) must read on past their first copy of the budget plus one byte to give the same result.
/// </summary>
[TestClass]
public class ReadBudgetParityTests
{
    /// <summary>Bytes after a value that the value does not use, so a buffered form's first copy does not hold the whole input.</summary>
    private static readonly byte[] Trailing = [.. Enumerable.Repeat((byte)0xCC, 24)];

    /// <summary>
    ///     Every layout, input and form: the runtime over a byte array, a memory stream, a stream that returns three bytes
    ///     per read, a multi-segment sequence and the async stream form, and the generated reader over a byte array, a
    ///     multi-segment sequence, a memory stream, the three-byte stream and its async form, all need exactly the bytes
    ///     the value occupies.
    /// </summary>
    /// <param name="name">The case name, shown in failure messages.</param>
    /// <param name="consumed">The bytes the value occupies, which is the smallest budget.</param>
    [TestMethod]
    [DataRow("uint8 a[] over 01 02 00", 3)]
    [DataRow("uint16 a[] over 0001 0002 0000", 6)]
    [DataRow("e items[] over 0102 0304 0000", 6)]
    [DataRow("outer { inner { uint8 a[] }; uint8 t } over 01 02 00 07", 4)]
    [DataRow("cstring over 61 62 00 then 07", 4)]
    [DataRow("unicode_string_zero over 4100 0000 then 07", 5)]
    [DataRow("char name[] over 61 00 then 07", 3)]
    [DataRow("uint8 a[] of 300 elements", 301)]
    [DataRow("cstring of 300 characters then 07", 302)]
    [DataRow("aligned uint8 tag; uint16 values[]; uint8 tail over 07 pad 0100 0200 0000 09", 8)]
    [DataRow("aligned uint8 a; uint32 b; uint8 c with tail padding", 6)]
    [DataRow("aligned uint8 a; uint32 v[EOF] over 3 elements", 13)]
    [DataRow("uint8 a; uint8* p to a byte at offset 40", 10)]
    public void MinimumBudget_IsTheBytesTheValueOccupies(string name, int consumed)
    {
        (CStruct layout, string root, byte[] data, Action<byte[], ReadOptions>[] generated) = Case(name);
        var forms = new List<(string Form, Action<ReadOptions> Parse)>
        {
            ("runtime byte[]", options => layout.Parse(data, root, options: options)),
            ("runtime MemoryStream", options => layout.Parse(new MemoryStream(data), root, options: options)),
            ("runtime chunked stream", options => layout.Parse(new ChunkedStream(data), root, options: options)),
            ("runtime sequence", options => layout.Parse(Segmented(data), root, options: options)),
            ("runtime async", options => layout.ParseAsync(new ChunkedStream(data), root, options: options).AsTask().GetAwaiter().GetResult()),
            ("runtime async forward-only", options => layout.ParseAsync(new ChunkedStream(data, seekable: false), root, options: options).AsTask().GetAwaiter().GetResult()),
        };
        string[] generatedForms = ["generated byte[]", "generated sequence", "generated MemoryStream", "generated chunked stream", "generated async", "generated forward-only stream", "generated async forward-only",];
        forms.AddRange(generatedForms.Select((form, index) => (form, (Action<ReadOptions>)(options => generated[index](data, options)))));

        foreach ((string form, Action<ReadOptions> parse) in forms)
        {
            // The whole budget range below the extent fails with the limit, and the extent itself succeeds.
            for (int budget = 0; budget < consumed; budget++)
            {
                var tooSmall = new ReadOptions { MaxTotalBytesRead = budget, };
                Assert.Throws<CStructReadLimitException>(() => parse(tooSmall), name + ", " + form + ", budget " + budget);
            }

            parse(new ReadOptions { MaxTotalBytesRead = consumed, });
        }
    }

    /// <summary>
    ///     Runtime-sized aligned records read through a stream window at their smallest budget: each record charges
    ///     10 bytes but spans 16, so the window of the budget plus one byte must grow for a record that starts it. The
    ///     generated <c>Records</c> and <c>RecordsAsync</c> and the runtime's <c>ParseManyAsync</c> read every record.
    /// </summary>
    [TestMethod]
    public void RecordWindows_GrowForARecordThatStartsThem()
    {
        byte[] record = [5, 0xEE, 0xEE, 0xEE, 1, 0, 0, 0, 0, 0, 0, 0, 9, 0xEE, 0xEE, 0xEE];
        byte[] data = [.. record, .. record, .. record];
        var options = new ReadOptions { MaxTotalBytesRead = 10, };
        CStruct layout = ReadBudgetLayouts.AlignedRecord.Layout;
        Assert.Throws<CStructReadLimitException>(() => layout.Parse(record, "rec", options: options with { MaxTotalBytesRead = 9, }));

        CollectionAssert.AreEqual(new byte[] { 9, 9, 9 }, ReadBudgetLayouts.AlignedRecord.Records(new MemoryStream(data), options).Select(value => value.Tail).ToArray(), "generated Records");
        var tails = new List<byte>();
        System.Collections.Generic.IAsyncEnumerator<ReadBudgetLayouts.AlignedRecord.Rec> records = ReadBudgetLayouts.AlignedRecord.RecordsAsync(new ChunkedStream(data), options).GetAsyncEnumerator();
        while (records.MoveNextAsync().AsTask().GetAwaiter().GetResult())
        {
            tails.Add(records.Current.Tail);
        }

        CollectionAssert.AreEqual(new byte[] { 9, 9, 9 }, tails, "generated RecordsAsync");
        Assert.AreEqual(3, layout.ParseMany(data.AsMemory(), "rec", options: options).Count(), "the memory form, as reference");
    }

    /// <summary>Builds a case's runtime layout, input bytes (with one trailing byte the value does not use) and generated parse forms.</summary>
    /// <param name="name">The case name.</param>
    /// <returns>The runtime layout, its root declaration, the input and the five generated forms.</returns>
    private static (CStruct Layout, string Root, byte[] Data, Action<byte[], ReadOptions>[] Generated) Case(string name) => name switch
    {
        "uint8 a[] over 01 02 00" => (ReadBudgetLayouts.ByteArray.Layout, ReadBudgetLayouts.ByteArray.RootName, [1, 2, 0, 9], Forms(ReadBudgetLayouts.ByteArray.Parse, ReadBudgetLayouts.ByteArray.Parse, ReadBudgetLayouts.ByteArray.Parse, ReadBudgetLayouts.ByteArray.ParseAsync)),
        "uint16 a[] over 0001 0002 0000" => (ReadBudgetLayouts.WideArray.Layout, ReadBudgetLayouts.WideArray.RootName, [1, 0, 2, 0, 0, 0, 9], Forms(ReadBudgetLayouts.WideArray.Parse, ReadBudgetLayouts.WideArray.Parse, ReadBudgetLayouts.WideArray.Parse, ReadBudgetLayouts.WideArray.ParseAsync)),
        "e items[] over 0102 0304 0000" => (ReadBudgetLayouts.StructArray.Layout, ReadBudgetLayouts.StructArray.RootName, [1, 2, 3, 4, 0, 0, 9], Forms(ReadBudgetLayouts.StructArray.Parse, ReadBudgetLayouts.StructArray.Parse, ReadBudgetLayouts.StructArray.Parse, ReadBudgetLayouts.StructArray.ParseAsync)),
        "outer { inner { uint8 a[] }; uint8 t } over 01 02 00 07" => (ReadBudgetLayouts.NestedArray.Layout, ReadBudgetLayouts.NestedArray.RootName, [1, 2, 0, 7, 9], Forms(ReadBudgetLayouts.NestedArray.Parse, ReadBudgetLayouts.NestedArray.Parse, ReadBudgetLayouts.NestedArray.Parse, ReadBudgetLayouts.NestedArray.ParseAsync)),
        "cstring over 61 62 00 then 07" => (ReadBudgetLayouts.NarrowText.Layout, ReadBudgetLayouts.NarrowText.RootName, [0x61, 0x62, 0, 7, 9], Forms(ReadBudgetLayouts.NarrowText.Parse, ReadBudgetLayouts.NarrowText.Parse, ReadBudgetLayouts.NarrowText.Parse, ReadBudgetLayouts.NarrowText.ParseAsync)),
        "unicode_string_zero over 4100 0000 then 07" => (ReadBudgetLayouts.WideText.Layout, ReadBudgetLayouts.WideText.RootName, [0x41, 0, 0, 0, 7, 9], Forms(ReadBudgetLayouts.WideText.Parse, ReadBudgetLayouts.WideText.Parse, ReadBudgetLayouts.WideText.Parse, ReadBudgetLayouts.WideText.ParseAsync)),
        "char name[] over 61 00 then 07" => (ReadBudgetLayouts.CharText.Layout, ReadBudgetLayouts.CharText.RootName, [0x61, 0, 7, 9], Forms(ReadBudgetLayouts.CharText.Parse, ReadBudgetLayouts.CharText.Parse, ReadBudgetLayouts.CharText.Parse, ReadBudgetLayouts.CharText.ParseAsync)),
        "uint8 a[] of 300 elements" => (ReadBudgetLayouts.ByteArray.Layout, ReadBudgetLayouts.ByteArray.RootName, [.. Enumerable.Repeat((byte)5, 300), 0, 9], Forms(ReadBudgetLayouts.ByteArray.Parse, ReadBudgetLayouts.ByteArray.Parse, ReadBudgetLayouts.ByteArray.Parse, ReadBudgetLayouts.ByteArray.ParseAsync)),
        "cstring of 300 characters then 07" => (ReadBudgetLayouts.NarrowText.Layout, ReadBudgetLayouts.NarrowText.RootName, [.. Enumerable.Repeat((byte)0x61, 300), 0, 7, 9], Forms(ReadBudgetLayouts.NarrowText.Parse, ReadBudgetLayouts.NarrowText.Parse, ReadBudgetLayouts.NarrowText.Parse, ReadBudgetLayouts.NarrowText.ParseAsync)),

        // The cases below charge fewer bytes than the position they reach; trailing bytes make every input longer than
        // the first copy of the budget plus one byte, so the buffered forms must read on.
        "aligned uint8 tag; uint16 values[]; uint8 tail over 07 pad 0100 0200 0000 09" => (ReadBudgetLayouts.AlignedArray.Layout, ReadBudgetLayouts.AlignedArray.RootName, [7, 0xEE, 1, 0, 2, 0, 0, 0, 9, .. Trailing], Forms(ReadBudgetLayouts.AlignedArray.Parse, ReadBudgetLayouts.AlignedArray.Parse, ReadBudgetLayouts.AlignedArray.Parse, ReadBudgetLayouts.AlignedArray.ParseAsync)),
        "aligned uint8 a; uint32 b; uint8 c with tail padding" => (ReadBudgetLayouts.PaddedFixed.Layout, ReadBudgetLayouts.PaddedFixed.RootName, [1, 0xEE, 0xEE, 0xEE, 2, 0, 0, 0, 3, 0xEE, 0xEE, 0xEE, .. Trailing], Forms(ReadBudgetLayouts.PaddedFixed.Parse, ReadBudgetLayouts.PaddedFixed.Parse, ReadBudgetLayouts.PaddedFixed.Parse, ReadBudgetLayouts.PaddedFixed.ParseAsync)),
        "aligned uint8 a; uint32 v[EOF] over 3 elements" => (ReadBudgetLayouts.AlignedToEnd.Layout, ReadBudgetLayouts.AlignedToEnd.RootName, [1, 0xEE, 0xEE, 0xEE, 1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0], Forms(ReadBudgetLayouts.AlignedToEnd.Parse, ReadBudgetLayouts.AlignedToEnd.Parse, ReadBudgetLayouts.AlignedToEnd.Parse, ReadBudgetLayouts.AlignedToEnd.ParseAsync)),
        "uint8 a; uint8* p to a byte at offset 40" => (ReadBudgetLayouts.FarPointer.Layout, ReadBudgetLayouts.FarPointer.RootName, [1, 40, 0, 0, 0, 0, 0, 0, 0, .. new byte[31], 0x2A, .. Trailing], Forms(ReadBudgetLayouts.FarPointer.Parse, ReadBudgetLayouts.FarPointer.Parse, ReadBudgetLayouts.FarPointer.Parse, ReadBudgetLayouts.FarPointer.ParseAsync)),
        _ => throw new ArgumentOutOfRangeException(nameof(name), name, "Unknown case."),
    };

    /// <summary>The seven generated parse forms of one layout, each discarding the parsed value.</summary>
    /// <typeparam name="T">The layout's root type.</typeparam>
    /// <param name="array">The byte-array form.</param>
    /// <param name="sequence">The sequence form.</param>
    /// <param name="stream">The stream form.</param>
    /// <param name="parseAsync">The async stream form.</param>
    /// <returns>The byte-array, sequence, memory-stream, chunked-stream, async, forward-only stream and forward-only async forms, in that order.</returns>
    private static Action<byte[], ReadOptions>[] Forms<T>(
        Func<byte[], ReadOptions?, T> array,
        Func<ReadOnlySequence<byte>, ReadOptions?, T> sequence,
        Func<Stream, ReadOptions?, T> stream,
        Func<Stream, ReadOptions?, System.Threading.CancellationToken, System.Threading.Tasks.ValueTask<T>> parseAsync) =>
    [
        (data, options) => array(data, options),
        (data, options) => sequence(Segmented(data), options),
        (data, options) => stream(new MemoryStream(data), options),
        (data, options) => stream(new ChunkedStream(data), options),
        (data, options) => parseAsync(new ChunkedStream(data), options, default).AsTask().GetAwaiter().GetResult(),
        (data, options) => stream(new ChunkedStream(data, seekable: false), options),
        (data, options) => parseAsync(new ChunkedStream(data, seekable: false), options, default).AsTask().GetAwaiter().GetResult(),
    ];

    /// <summary>Splits bytes into a sequence of two-byte segments, so a reader cannot take them as one span.</summary>
    /// <param name="data">The bytes.</param>
    /// <returns>The multi-segment sequence.</returns>
    private static ReadOnlySequence<byte> Segmented(byte[] data)
    {
        var first = new Segment(data.AsMemory(0, Math.Min(2, data.Length)), 0);
        Segment last = first;
        for (int offset = 2; offset < data.Length; offset += 2)
        {
            last = last.Append(data.AsMemory(offset, Math.Min(2, data.Length - offset)));
        }

        return new ReadOnlySequence<byte>(first, 0, last, last.Memory.Length);
    }

    /// <summary>One segment of a multi-segment test sequence.</summary>
    private sealed class Segment : ReadOnlySequenceSegment<byte>
    {
        /// <summary>Creates a segment over <paramref name="memory"/> that starts <paramref name="runningIndex"/> bytes into the sequence.</summary>
        /// <param name="memory">The segment's bytes.</param>
        /// <param name="runningIndex">The sequence offset of the segment's first byte.</param>
        public Segment(ReadOnlyMemory<byte> memory, long runningIndex)
        {
            this.Memory = memory;
            this.RunningIndex = runningIndex;
        }

        /// <summary>Links a new segment after this one.</summary>
        /// <param name="memory">The next segment's bytes.</param>
        /// <returns>The new segment.</returns>
        public Segment Append(ReadOnlyMemory<byte> memory)
        {
            var next = new Segment(memory, this.RunningIndex + this.Memory.Length);
            this.Next = next;
            return next;
        }
    }

    /// <summary>A stream over bytes that returns at most three bytes per read and hides its buffer, so no reader takes it as memory; seekable unless asked otherwise.</summary>
    private sealed class ChunkedStream : Stream
    {
        private readonly byte[] data;
        private readonly bool seekable;
        private long position;

        /// <summary>Creates a stream over <paramref name="data"/>, positioned at its first byte.</summary>
        /// <param name="data">The bytes the stream serves.</param>
        /// <param name="seekable">Whether the stream reports its length and position and can seek.</param>
        public ChunkedStream(byte[] data, bool seekable = true)
        {
            this.data = data;
            this.seekable = seekable;
        }

        /// <inheritdoc/>
        public override bool CanRead => true;

        /// <inheritdoc/>
        public override bool CanSeek => this.seekable;

        /// <inheritdoc/>
        public override bool CanWrite => false;

        /// <inheritdoc/>
        public override long Length => this.seekable ? this.data.Length : throw new NotSupportedException();

        /// <inheritdoc/>
        public override long Position
        {
            get => this.seekable ? this.position : throw new NotSupportedException();
            set => this.position = this.seekable ? value : throw new NotSupportedException();
        }

        /// <summary>Copies at most three bytes from the position.</summary>
        /// <param name="buffer">The destination array.</param>
        /// <param name="offset">The index of the first byte stored.</param>
        /// <param name="count">The most bytes to read.</param>
        /// <returns>The number of bytes read, 0 at the end.</returns>
        public override int Read(byte[] buffer, int offset, int count)
        {
            int read = (int)Math.Min(Math.Min(count, 3), Math.Max(0, this.data.Length - this.position));
            Array.Copy(this.data, this.position, buffer, offset, read);
            this.position += read;
            return read;
        }

        /// <summary>Moves the position.</summary>
        /// <param name="offset">The byte offset relative to <paramref name="origin"/>.</param>
        /// <param name="origin">The reference point.</param>
        /// <returns>The new position.</returns>
        public override long Seek(long offset, SeekOrigin origin)
        {
            this.position = origin switch
            {
                SeekOrigin.Begin => offset,
                SeekOrigin.Current => this.position + offset,
                _ => this.data.Length + offset,
            };
            return this.position;
        }

        /// <summary>Does nothing: the stream is read-only.</summary>
        public override void Flush()
        {
        }

        /// <summary>Rejects a length change.</summary>
        /// <param name="value">The ignored length.</param>
        /// <exception cref="NotSupportedException">Always.</exception>
        public override void SetLength(long value) => throw new NotSupportedException();

        /// <summary>Rejects a write.</summary>
        /// <param name="buffer">The ignored source.</param>
        /// <param name="offset">The ignored index.</param>
        /// <param name="count">The ignored count.</param>
        /// <exception cref="NotSupportedException">Always.</exception>
        public override void Write(byte[] buffer, int offset, int count) => throw new NotSupportedException();
    }
}
