namespace CStructSharp.Generators.Tests;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using CStructSharp;
using CStructSharp.Diagnostics;
using CStructSharp.Values;

/// <summary>
///     Generated readers against the runtime, the oracle: for every fixture with bytes, <c>Parse</c> yields the same
///     value member by member, and every truncated prefix of the bytes fails with the same exception type and message.
/// </summary>
[TestClass]
public class ReaderParityTests
{
    private const string Header = """
        using CStructSharp;

        namespace Parity;

        """;

    [TestMethod]
    public void ManualFixtures_ParseAndTruncationSweep_MatchTheRuntime()
    {
        var failures = new List<string>();
        foreach (ManualFixture fixture in ManualFixtures.Load())
        {
            if (fixture.Bytes is null || HasConditionals(fixture.Definition))
            {
                continue;
            }

            try
            {
                RunParity(fixture);
            }
            catch (Exception exception) when (exception is AssertFailedException or InvalidOperationException or TargetInvocationException or CStructException)
            {
                failures.Add(fixture.Id + ": " + (exception.InnerException ?? exception).Message);
            }
        }

        Assert.IsEmpty(failures, string.Join("\n\n", failures));
    }

    /// <summary>The benchmark harness's fixtures (up to 128 KiB of bytes): values, expected errors, and a truncation sweep bounded by the fixture's size.</summary>
    [TestMethod]
    public void BenchmarkFixtures_ParseAndTruncationSweep_MatchTheRuntime()
    {
        var failures = new List<string>();
        foreach (BenchmarkFixture fixture in BenchmarkFixtures.Load(128 * 1024))
        {
            if (fixture.Root.Contains('[', StringComparison.Ordinal) || HasConditionals(fixture.Definition))
            {
                // A synthetic root (a type spelling such as `uint32[256]`) is the runtime's alone; a generated
                // Parse needs a declaration.
                continue;
            }

            try
            {
                string arguments = "Root = \"" + fixture.Root + "\", PointerSize = " + fixture.PointerSize + ", Aligned = " + (fixture.Aligned ? "true" : "false") + ", LittleEndian = " + (fixture.LittleEndian ? "true" : "false");
                RunParity(fixture.Id, fixture.Definition, arguments, fixture.Root, fixture.Bytes, fixture.Variables, fixture.ReadOptions, fixture.ExpectedError);
            }
            catch (Exception exception) when (exception is AssertFailedException or InvalidOperationException or TargetInvocationException or CStructException)
            {
                failures.Add(fixture.Id + ": " + (exception.InnerException ?? exception).Message);
            }
        }

        Assert.IsEmpty(failures, string.Join("\n\n", failures));
    }

    // Conditional members (`if`, `switch`) are generated by the next plan item (3.5); until then their fixtures sit out.
    private static bool HasConditionals(string definition)
        => definition.Contains("if (", StringComparison.Ordinal) || definition.Contains("if(", StringComparison.Ordinal) || definition.Contains("switch", StringComparison.Ordinal);

    private static void RunParity(ManualFixture fixture)
    {
        RunParity(fixture.Id, fixture.Definition, ManualFixtures.AttributeArguments(fixture), fixture.Root, Convert.FromHexString(fixture.Bytes!), fixture.Variables, null, null);
    }

    private static void RunParity(string id, string definition, string arguments, string root, byte[] bytes, IReadOnlyDictionary<string, int> fixtureVariables, ReadOptions? options, string? expectedError)
    {
        string className = "Fixture" + string.Concat(id.Split('-').Select(part => char.ToUpperInvariant(part[0]) + part.Substring(1)));
        string source = Header + "[CStructLayout(" + Literal(definition) + ", " + arguments + ")]\npublic static partial class " + className + " { }\n";
        GeneratorResult result = GeneratorRunner.Run(source).AssertClean();
        Assembly assembly = result.Load();
        Type generated = assembly.GetType("Parity." + className)!;
        var runtime = (CStruct)generated.GetProperty("Layout")!.GetValue(null)!;
        IReadOnlyDictionary<string, int>? variables = fixtureVariables.Count == 0 ? null : fixtureVariables;
        MethodInfo parse = generated.GetMethods().Single(method => method.Name == "Parse" + PascalRoot(root, generated) && method.GetParameters()[0].ParameterType == typeof(ReadOnlySpan<byte>));

        if (expectedError is not null)
        {
            Exception? runtimeError = Catch(() => runtime.ReadValue(bytes, root, variables, options));
            Exception? generatedError = Catch(() => Invoke(parse, bytes, variables, options));
            Assert.IsNotNull(runtimeError, id + ": the runtime did not fail");
            Assert.AreEqual(expectedError, runtimeError.GetType().Name, id);
            Assert.AreEqual(runtimeError.GetType(), generatedError?.GetType(), id + ": exception type (" + generatedError?.Message + ")");
            Assert.AreEqual(runtimeError.Message, generatedError!.Message, id);
        }
        else
        {
            object runtimeValue = runtime.ReadValue(bytes, root, variables, options)!;
            object generatedValue = Invoke(parse, bytes, variables, options);
            ParityComparer.AssertSame(runtimeValue, generatedValue, root);
        }

        // The truncation sweep: every prefix (every prefix of a small input; a spread of prefixes of a large one)
        // fails the same way (type and message) in both readers.
        foreach (int length in SweepLengths(bytes.Length))
        {
            byte[] prefix = bytes[..length];
            Exception? runtimeError = Catch(() => runtime.ReadValue(prefix, root, variables, options));
            Exception? generatedError = Catch(() => Invoke(parse, prefix, variables, options));
            Assert.AreEqual(runtimeError?.GetType(), generatedError?.GetType(), $"{id} truncated to {length}: exception type ({runtimeError?.Message} vs {generatedError?.Message})");
            Assert.AreEqual(runtimeError?.Message, generatedError?.Message, $"{id} truncated to {length}");
        }
    }

    private static IEnumerable<int> SweepLengths(int length)
    {
        if (length <= 1024)
        {
            for (int prefix = 0; prefix < length; prefix++)
            {
                yield return prefix;
            }

            yield break;
        }

        for (int prefix = 0; prefix < 64; prefix++)
        {
            yield return prefix;
        }

        for (int prefix = 64; prefix < length; prefix += Math.Max(1, length / 97))
        {
            yield return prefix;
        }

        for (int prefix = Math.Max(64, length - 16); prefix < length; prefix++)
        {
            yield return prefix;
        }
    }

    private static object Invoke(MethodInfo parse, byte[] bytes, IReadOnlyDictionary<string, int>? variables, ReadOptions? options)
    {
        // A ReadOnlySpan<byte> parameter cannot be boxed; call the byte[] overload, which forwards to the span one.
        MethodInfo arrayOverload = parse.DeclaringType!.GetMethods().Single(method => method.Name == parse.Name && method.GetParameters()[0].ParameterType == typeof(byte[]));
        try
        {
            return arrayOverload.Invoke(null, [bytes, variables, options])!;
        }
        catch (TargetInvocationException exception) when (exception.InnerException is not null)
        {
            System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture(exception.InnerException).Throw();
            throw;
        }
    }

    private static Exception? Catch(Func<object?> action)
    {
        try
        {
            action();
            return null;
        }
        catch (CStructException exception)
        {
            return exception;
        }
    }

    private static string PascalRoot(string root, Type generated)
    {
        foreach (MethodInfo method in generated.GetMethods())
        {
            if (method.Name.StartsWith("Parse", StringComparison.Ordinal) && method.Name.Length > 5 && method.Name.Substring(5).Equals(root.Replace("_", string.Empty), StringComparison.OrdinalIgnoreCase))
            {
                return method.Name.Substring(5);
            }
        }

        return root;
    }

    private static string Literal(string definition)
    {
        return "\"" + definition.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "\\r") + "\"";
    }
}
