// <auto-generated/>
// Generated by CStructSharp from the [CStructLayout] attribute on FixtureExpressionExtensions. Do not edit.
#nullable enable
#pragma warning disable

namespace Demo
{
    [global::System.CodeDom.Compiler.GeneratedCode("CStructSharp", "<version>")]
    public static partial class FixtureExpressionExtensions
    {
        /// <summary>The layout text the members of this class were generated from.</summary>
        public const string Definition = "enum kind : uint8 { A = 1, B = 6 ^ 3 }; struct head { uint32 a; uint16 b; }; struct root { uint8 x[kind.B % 4]; uint8 y[sizeof(head) ? offsetof(head, b) : 9]; };";

        /// <summary>The declaration the plain <see cref="Parse"/> and <see cref="Serialize"/> methods operate on.</summary>
        public const string RootName = "root";

        private static readonly global::System.Lazy<global::CStructSharp.CStruct> LayoutInstance = new(CreateLayout, global::System.Threading.LazyThreadSafetyMode.ExecutionAndPublication);

        /// <summary>The runtime <see cref="global::CStructSharp.CStruct"/> for the same definition and options, built on first use: introspection, JSON, memory images, and the parity oracle.</summary>
        public static global::CStructSharp.CStruct Layout => LayoutInstance.Value;

        private static global::CStructSharp.CStruct CreateLayout()
        {
            var options = new global::CStructSharp.CStructCompilationOptions
            {
                CLongWidth = 64,
                BitfieldPacking = global::CStructSharp.BitfieldPacking.SysV,
                BitfieldAllocation = global::CStructSharp.BitfieldAllocation.LowBitFirst,
            };
            return new global::CStructSharp.CStruct(Definition, pointerSize: 4, aligned: false, isLittleEndian: true, compilationOptions: options);
        }

        /// <summary>The layout enum <c>kind</c>, stored as <c>uint8</c>. A stored value with no member keeps its number.</summary>
        public enum Kind : byte
        {
            A = 1,
            B = 5,
        }

        /// <summary>The layout struct <c>head</c>.</summary>
        public sealed partial class Head
        {
            /// <summary><c>uint32 a</c>.</summary>
            public uint A { get; set; }

            /// <summary><c>uint16 b</c>.</summary>
            public ushort B { get; set; }
        }

        /// <summary>The layout struct <c>root</c>.</summary>
        public sealed partial class Root
        {
            /// <summary><c>uint8 x[...]</c>.</summary>
            public byte[] X { get; set; } = global::System.Array.Empty<byte>();

            /// <summary><c>uint8 y[4]</c>.</summary>
            public byte[] Y { get; set; } = global::System.Array.Empty<byte>();
        }
    }
}
