// <auto-generated/>
// Generated by CStructSharp from the [CStructLayout] attribute on FixtureAnonymousBitfieldPadding. Do not edit.
#nullable enable
#pragma warning disable

namespace Demo
{
    [global::System.CodeDom.Compiler.GeneratedCode("CStructSharp", "<version>")]
    public static partial class FixtureAnonymousBitfieldPadding
    {
        /// <summary>The layout text the members of this class were generated from.</summary>
        public const string Definition = "struct root { uint8 flag:1, :3, other:4; };";

        /// <summary>The declaration the plain <see cref="Parse"/> and <see cref="Serialize"/> methods operate on.</summary>
        public const string RootName = "root";

        private static readonly global::System.Lazy<global::CStructSharp.CStruct> LayoutInstance = new(CreateLayout, global::System.Threading.LazyThreadSafetyMode.ExecutionAndPublication);

        /// <summary>The runtime <see cref="global::CStructSharp.CStruct"/> for the same definition and options, built on first use: introspection, JSON, memory images, and the parity oracle.</summary>
        public static global::CStructSharp.CStruct Layout => LayoutInstance.Value;

        private static global::CStructSharp.CStruct CreateLayout()
        {
            var options = new global::CStructSharp.CStructCompilationOptions
            {
                CLongWidth = 64,
                BitfieldPacking = global::CStructSharp.BitfieldPacking.SysV,
                BitfieldAllocation = global::CStructSharp.BitfieldAllocation.LowBitFirst,
            };
            return new global::CStructSharp.CStruct(Definition, pointerSize: 4, aligned: false, isLittleEndian: true, compilationOptions: options);
        }

        /// <summary>The layout struct <c>root</c>.</summary>
        public sealed partial class Root
        {
            /// <summary><c>uint8 flag : 1</c>.</summary>
            public byte Flag { get; set; }

            /// <summary><c>uint8 other : 4</c>.</summary>
            public byte Other { get; set; }
        }

        private const bool Aligned = false;
        private const bool LittleEndian = true;
        private const int PointerSize = 4;
        private const bool HighBitFirst = false;
        private const global::CStructSharp.BitfieldPacking Packing = global::CStructSharp.BitfieldPacking.SysV;
        private const global::CStructSharp.BitfieldAllocation Allocation = global::CStructSharp.BitfieldAllocation.LowBitFirst;

        /// <summary>Reads one <c>root</c> from the start of <paramref name="source"/> with the generated reader; the same value, and the same failures, as the runtime's <c>Parse</c>.</summary>
        /// <param name="source">The bytes; offset 0 is coordinate zero.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The read options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The parsed value.</returns>
        public static Root ParseRoot(global::System.ReadOnlySpan<byte> source, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null)
        {
            var cursor = new global::CStructSharp.Generated.ReadCursor(source, options, "root");
            try
            {
                return ReadRoot(ref cursor, variables, null, null);
            }
            catch (global::CStructSharp.Diagnostics.CStructException exception)
            {
                cursor.Complete(exception);
                throw;
            }
        }

        /// <inheritdoc cref="ParseRoot(global::System.ReadOnlySpan{byte}, global::System.Collections.Generic.IReadOnlyDictionary{string, int}, global::CStructSharp.ReadOptions)"/>
        public static Root ParseRoot(byte[] source, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null)
            => ParseRoot(new global::System.ReadOnlySpan<byte>(source ?? throw new global::System.ArgumentNullException(nameof(source))), variables, options);

        /// <inheritdoc cref="ParseRoot(global::System.ReadOnlySpan{byte}, global::System.Collections.Generic.IReadOnlyDictionary{string, int}, global::CStructSharp.ReadOptions)"/>
        public static Root ParseRoot(global::System.ReadOnlyMemory<byte> source, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null)
            => ParseRoot(source.Span, variables, options);

        /// <summary>Reads the root declaration (<c>root</c>); see <see cref="ParseRoot(global::System.ReadOnlySpan{byte}, global::System.Collections.Generic.IReadOnlyDictionary{string, int}, global::CStructSharp.ReadOptions)"/>.</summary>
        /// <param name="source">The bytes; offset 0 is coordinate zero.</param>
        /// <param name="options">The read options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The parsed value.</returns>
        public static Root Parse(global::System.ReadOnlySpan<byte> source, global::CStructSharp.ReadOptions? options = null) => ParseRoot(source, null, options);

        /// <inheritdoc cref="Parse(global::System.ReadOnlySpan{byte}, global::CStructSharp.ReadOptions)"/>
        public static Root Parse(byte[] source, global::CStructSharp.ReadOptions? options = null) => ParseRoot(source, null, options);

        /// <inheritdoc cref="Parse(global::System.ReadOnlySpan{byte}, global::CStructSharp.ReadOptions)"/>
        public static Root Parse(global::System.ReadOnlyMemory<byte> source, global::CStructSharp.ReadOptions? options = null) => ParseRoot(source.Span, null, options);

        /// <summary>Reads one <c>root</c> at the cursor's position.</summary>
        private static Root ReadRoot(ref global::CStructSharp.Generated.ReadCursor cursor, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables, string? member, string? memberType)
        {
            cursor.EnterComposite(member ?? "root", memberType);
            var value = new Root();
            var placement = global::CStructSharp.Generated.CompositeCursor.Start(cursor.Position, Aligned, Packing, Allocation);
            // uint8 flag : 1
            {
                var slot = placement.AdvanceToBitfield(1, 1, 1, 8, true, "flag");
                cursor.Seek(slot.UnitStart, "flag", "uint8");
                ulong unit = global::CStructSharp.Generated.Codec.ReadUnsigned(cursor.Take(slot.UnitSize, "flag", "uint8"), true);
                if (slot.BitOffset + 1 > slot.UnitSize * 8)
                {
                    throw cursor.Fail("Bitfield exceeds its storage unit: flag", "flag", "uint8");
                }
                ulong bits = global::CStructSharp.Generated.Codec.ExtractBits(unit, global::CStructSharp.Generated.Codec.BitfieldShift(slot.BitOffset, 1, slot.UnitSize * 8, HighBitFirst), 1);
                value.Flag = (byte)bits;
            }
            // uint8  : 3
            {
                var slot = placement.AdvanceToBitfield(1, 1, 3, 8, true, "");
                cursor.Seek(slot.UnitStart, "", "uint8");
                ulong unit = global::CStructSharp.Generated.Codec.ReadUnsigned(cursor.Take(slot.UnitSize, "", "uint8"), true);
                if (slot.BitOffset + 3 > slot.UnitSize * 8)
                {
                    throw cursor.Fail("Bitfield exceeds its storage unit: ", "", "uint8");
                }
                ulong bits = global::CStructSharp.Generated.Codec.ExtractBits(unit, global::CStructSharp.Generated.Codec.BitfieldShift(slot.BitOffset, 3, slot.UnitSize * 8, HighBitFirst), 3);
            }
            // uint8 other : 4
            {
                var slot = placement.AdvanceToBitfield(1, 1, 4, 8, true, "other");
                cursor.Seek(slot.UnitStart, "other", "uint8");
                ulong unit = global::CStructSharp.Generated.Codec.ReadUnsigned(cursor.Take(slot.UnitSize, "other", "uint8"), true);
                if (slot.BitOffset + 4 > slot.UnitSize * 8)
                {
                    throw cursor.Fail("Bitfield exceeds its storage unit: other", "other", "uint8");
                }
                ulong bits = global::CStructSharp.Generated.Codec.ExtractBits(unit, global::CStructSharp.Generated.Codec.BitfieldShift(slot.BitOffset, 4, slot.UnitSize * 8, HighBitFirst), 4);
                value.Other = (byte)bits;
            }
            cursor.Seek(placement.Finish(1), member, memberType);
            cursor.ExitComposite();
            return value;
        }

        /// <summary>Groups a flat element array into rows of <paramref name="inner"/> elements (one nesting level of a multidimensional array).</summary>
        private static T[][] Split<T>(T[] flat, int inner)
        {
            var rows = new T[inner == 0 ? 0 : flat.Length / inner][];
            for (int row = 0; row < rows.Length; row++)
            {
                rows[row] = new T[inner];
                global::System.Array.Copy(flat, row * inner, rows[row], 0, inner);
            }
            return rows;
        }

        /// <summary>Writes one <c>root</c> into a new array with the generated writer; the same bytes, and the same failures, as the runtime's <c>Serialize</c>.</summary>
        /// <param name="value">The value to write.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The write options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The serialized bytes.</returns>
        public static byte[] SerializeRoot(Root value, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.WriteOptions? options = null)
        {
            var cursor = new global::CStructSharp.Generated.WriteCursor(options, "root");
            try
            {
                EncodeRoot(ref cursor, value, variables, null, null);
                return cursor.ToArray();
            }
            catch (global::CStructSharp.Diagnostics.CStructException exception)
            {
                cursor.Complete(exception);
                throw;
            }
            finally
            {
                cursor.Dispose();
            }
        }

        /// <summary>Writes one <c>root</c> into <paramref name="destination"/>; a value that does not fit fails with the runtime's capacity message.</summary>
        /// <param name="value">The value to write.</param>
        /// <param name="destination">The bytes to write into.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The write options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The number of bytes written.</returns>
        public static int SerializeRoot(Root value, global::System.Span<byte> destination, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.WriteOptions? options = null)
        {
            var cursor = new global::CStructSharp.Generated.WriteCursor(destination, options, "root");
            try
            {
                EncodeRoot(ref cursor, value, variables, null, null);
                return cursor.Length;
            }
            catch (global::CStructSharp.Diagnostics.CStructException exception)
            {
                cursor.Complete(exception);
                throw;
            }
        }

        /// <summary>Writes one <c>root</c> to <paramref name="stream"/> at its current position.</summary>
        /// <param name="stream">The destination stream.</param>
        /// <param name="value">The value to write.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The write options; <see langword="null"/> uses the documented defaults.</param>
        public static void WriteRoot(global::System.IO.Stream stream, Root value, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.WriteOptions? options = null)
        {
            global::System.ArgumentNullException.ThrowIfNull(stream);
            if (!stream.CanWrite)
            {
                throw new global::System.ArgumentException("Writing requires a writable stream.", nameof(stream));
            }
            byte[] bytes = SerializeRoot(value, variables, options);
            stream.Write(bytes, 0, bytes.Length);
        }

        /// <summary>Writes the root declaration (<c>root</c>) into a new array; see <see cref="SerializeRoot(Root, global::System.Collections.Generic.IReadOnlyDictionary{string, int}, global::CStructSharp.WriteOptions)"/>.</summary>
        /// <param name="value">The value to write.</param>
        /// <param name="options">The write options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The serialized bytes.</returns>
        public static byte[] Serialize(Root value, global::CStructSharp.WriteOptions? options = null) => SerializeRoot(value, null, options);

        /// <summary>Writes the root declaration (<c>root</c>) into <paramref name="destination"/>.</summary>
        /// <param name="value">The value to write.</param>
        /// <param name="destination">The bytes to write into.</param>
        /// <param name="options">The write options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The number of bytes written.</returns>
        public static int Serialize(Root value, global::System.Span<byte> destination, global::CStructSharp.WriteOptions? options = null) => SerializeRoot(value, destination, null, options);

        /// <summary>Writes the root declaration (<c>root</c>) to <paramref name="stream"/>.</summary>
        /// <param name="stream">The destination stream.</param>
        /// <param name="value">The value to write.</param>
        /// <param name="options">The write options; <see langword="null"/> uses the documented defaults.</param>
        public static void Write(global::System.IO.Stream stream, Root value, global::CStructSharp.WriteOptions? options = null) => WriteRoot(stream, value, null, options);

        /// <summary>Writes one <c>root</c> at the cursor's position.</summary>
        private static void EncodeRoot(ref global::CStructSharp.Generated.WriteCursor cursor, Root? value, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables, string? member, string? memberType)
        {
            if (value is null)
            {
                throw cursor.Fail("Null is not valid for struct or union value: root", member, memberType);
            }
            cursor.EnterComposite(member ?? "root", memberType);
            var placement = global::CStructSharp.Generated.CompositeCursor.Start(cursor.Position, Aligned, Packing, Allocation);
            // uint8 flag : 1
            {
                var slot = placement.AdvanceToBitfield(1, 1, 1, 8, true, "flag");
                cursor.WriteBits(slot, 1, value.Flag, true, HighBitFirst, "flag", "uint8");
            }
            // uint8  : 3
            {
                var slot = placement.AdvanceToBitfield(1, 1, 3, 8, true, "");
                cursor.WriteBits(slot, 3, 0UL, true, HighBitFirst, "", "uint8");
            }
            // uint8 other : 4
            {
                var slot = placement.AdvanceToBitfield(1, 1, 4, 8, true, "other");
                cursor.WriteBits(slot, 4, value.Other, true, HighBitFirst, "other", "uint8");
            }
            cursor.Seek(placement.Current, member, memberType);
            cursor.Pad((int)(placement.Finish(1) - placement.Current), member, memberType);
            cursor.ExitComposite();
        }

        /// <summary>The root declaration as <see cref="global::CStructSharp.ICStructGenerated{Root}"/>.</summary>
        public sealed partial class Root : global::CStructSharp.ICStructGenerated<Root>
        {
            /// <inheritdoc/>
            static global::CStructSharp.CStruct global::CStructSharp.ICStructGenerated<Root>.Layout => FixtureAnonymousBitfieldPadding.Layout;

            /// <inheritdoc/>
            static string global::CStructSharp.ICStructGenerated<Root>.RootName => FixtureAnonymousBitfieldPadding.RootName;

            /// <inheritdoc/>
            static Root global::CStructSharp.ICStructGenerated<Root>.Parse(global::System.ReadOnlySpan<byte> source, global::CStructSharp.ReadOptions? options) => FixtureAnonymousBitfieldPadding.Parse(source, options);

            /// <inheritdoc/>
            static int global::CStructSharp.ICStructGenerated<Root>.Serialize(Root value, global::System.Span<byte> destination, global::CStructSharp.WriteOptions? options) => FixtureAnonymousBitfieldPadding.Serialize(value, destination, options);
        }

        /// <summary>Reads the root declaration with the generated reader and the runtime's debug ranges (the runtime reads the same bytes once more to produce them).</summary>
        /// <param name="source">The bytes; offset 0 is coordinate zero.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The read options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The parsed value and one <see cref="global::CStructSharp.Diagnostics.DebugData"/> per value read, in read order.</returns>
        public static (Root Value, global::System.Collections.Generic.IReadOnlyList<global::CStructSharp.Diagnostics.DebugData> Debug) ParseWithDebug(global::System.ReadOnlySpan<byte> source, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null)
        {
            Root value = ParseRoot(source, variables, options);
            return (value, Layout.ParseWithDebug(source, "root", variables, options).Debug);
        }

        /// <summary>Resolves a path (<c>root.field</c>, <c>items[2].value</c>, ...) to its byte address with the runtime layout.</summary>
        /// <param name="source">The bytes; offset 0 is coordinate zero.</param>
        /// <param name="path">The path, in the runtime's path grammar.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The read options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The address of the selected value.</returns>
        public static long ResolveAddress(global::System.ReadOnlySpan<byte> source, string path, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null) => Layout.ResolveAddress(source, path, variables, options);

        /// <summary>The element count of an array or string selected by a path, with the runtime layout.</summary>
        /// <param name="source">The bytes; offset 0 is coordinate zero.</param>
        /// <param name="path">The path, in the runtime's path grammar.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The read options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The element count.</returns>
        public static int GetArrayLength(global::System.ReadOnlySpan<byte> source, string path, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null) => Layout.GetArrayLength(source, path, variables, options);

        /// <summary>Replaces one value in place by path with the runtime layout; statically placed members also have typed setters in <see cref="Update"/>.</summary>
        /// <param name="target">The bytes holding the value.</param>
        /// <param name="path">The path, in the runtime's path grammar.</param>
        /// <param name="value">The new value.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The update options; <see langword="null"/> uses the documented defaults.</param>
        public static void UpdatePath(global::System.Span<byte> target, string path, object value, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.UpdateOptions? options = null) => Layout.Update(target, path, value, variables, options);

        /// <summary>The size in bytes of every composite with a static size (<c>sizeof</c>); a runtime-sized composite has none.</summary>
        public static class Sizes
        {
            /// <summary><c>sizeof(root)</c>.</summary>
            public const int Root = 1;
        }

        /// <summary>The offset from the root's first byte of every statically placed scalar (<c>offsetof</c>), nested by struct member.</summary>
        public static class Offsets
        {
            /// <summary><c>offsetof(root, flag)</c> (the storage unit's first byte).</summary>
            public const int Flag = 0;

            /// <summary><c>offsetof(root, other)</c> (the storage unit's first byte).</summary>
            public const int Other = 0;
        }

        /// <summary>Typed in-place setters for the statically placed scalars, nested by struct member; a fixed array takes the element index.</summary>
        public static class Update
        {
            /// <summary>Stores <c>flag</c> into <paramref name="target"/> at offset 0, leaving every other byte alone.</summary>
            /// <param name="target">The bytes holding the value.</param>
            /// <param name="value">The new value.</param>
            public static void Flag(global::System.Span<byte> target, byte value)
            {
                var cursor = global::CStructSharp.Generated.WriteCursor.ForUpdate(target, null, "root.flag");
                try
                {
                    cursor.WriteBits(new global::CStructSharp.Generated.BitfieldSlot(0, 1, 0), 1, value, true, HighBitFirst, "flag", "uint8");
                }
                catch (global::CStructSharp.Diagnostics.CStructException exception)
                {
                    cursor.Complete(exception);
                    throw;
                }
            }

            /// <summary>Stores <c>other</c> into <paramref name="target"/> at offset 0, leaving every other byte alone.</summary>
            /// <param name="target">The bytes holding the value.</param>
            /// <param name="value">The new value.</param>
            public static void Other(global::System.Span<byte> target, byte value)
            {
                var cursor = global::CStructSharp.Generated.WriteCursor.ForUpdate(target, null, "root.other");
                try
                {
                    cursor.WriteBits(new global::CStructSharp.Generated.BitfieldSlot(0, 1, 4), 4, value, true, HighBitFirst, "other", "uint8");
                }
                catch (global::CStructSharp.Diagnostics.CStructException exception)
                {
                    cursor.Complete(exception);
                    throw;
                }
            }
        }
    }
}
