// <auto-generated/>
// Generated by CStructSharp from the [CStructLayout] attribute on FixtureEnums. Do not edit.
#nullable enable
#pragma warning disable

namespace Demo
{
    [global::System.CodeDom.Compiler.GeneratedCode("CStructSharp", "<version>")]
    public static partial class FixtureEnums
    {
        /// <summary>The layout text the members of this class were generated from.</summary>
        public const string Definition = "enum mode : uint8 { One=1, Two=2 }; struct root { mode value; byte tail; };";

        /// <summary>The declaration the plain <see cref="Parse"/> and <see cref="Serialize"/> methods operate on.</summary>
        public const string RootName = "root";

        private static readonly global::System.Lazy<global::CStructSharp.CStruct> LayoutInstance = new(CreateLayout, global::System.Threading.LazyThreadSafetyMode.ExecutionAndPublication);

        /// <summary>The runtime <see cref="global::CStructSharp.CStruct"/> for the same definition and options, built on first use: introspection, JSON, memory images, and the parity oracle.</summary>
        public static global::CStructSharp.CStruct Layout => LayoutInstance.Value;

        private static global::CStructSharp.CStruct CreateLayout()
        {
            var options = new global::CStructSharp.CStructCompilationOptions
            {
                CLongWidth = 64,
                BitfieldPacking = global::CStructSharp.BitfieldPacking.SysV,
                BitfieldAllocation = global::CStructSharp.BitfieldAllocation.LowBitFirst,
            };
            return new global::CStructSharp.CStruct(Definition, pointerSize: 2, aligned: false, isLittleEndian: true, compilationOptions: options);
        }

        /// <summary>The layout enum <c>mode</c>, stored as <c>uint8</c>. A stored value with no member keeps its number.</summary>
        public enum Mode : byte
        {
            One = 1,
            Two = 2,
        }

        /// <summary>The layout struct <c>root</c>.</summary>
        public sealed partial class Root
        {
            /// <summary><c>mode value</c>.</summary>
            public Mode Value { get; set; }

            /// <summary><c>byte tail</c>.</summary>
            public byte Tail { get; set; }
        }
    }
}
