// <auto-generated/>
// Generated by CStructSharp from the [CStructLayout] attribute on FixtureTopLevelDeclarations. Do not edit.
#nullable enable
#pragma warning disable

namespace Demo
{
    [global::System.CodeDom.Compiler.GeneratedCode("CStructSharp", "<version>")]
    public static partial class FixtureTopLevelDeclarations
    {
        /// <summary>The layout text the members of this class were generated from.</summary>
        public const string Definition = "struct { uint16 sec; uint16 usec; } timeval; struct root { timeval stamp; uint8 tail; } header;";

        /// <summary>The declaration the plain <see cref="Parse"/> and <see cref="Serialize"/> methods operate on.</summary>
        public const string RootName = "root";

        private static readonly global::System.Lazy<global::CStructSharp.CStruct> LayoutInstance = new(CreateLayout, global::System.Threading.LazyThreadSafetyMode.ExecutionAndPublication);

        /// <summary>The runtime <see cref="global::CStructSharp.CStruct"/> for the same definition and options, built on first use: introspection, JSON, memory images, and the parity oracle.</summary>
        public static global::CStructSharp.CStruct Layout => LayoutInstance.Value;

        private static global::CStructSharp.CStruct CreateLayout()
        {
            var options = new global::CStructSharp.CStructCompilationOptions
            {
                CLongWidth = 64,
                BitfieldPacking = global::CStructSharp.BitfieldPacking.SysV,
                BitfieldAllocation = global::CStructSharp.BitfieldAllocation.LowBitFirst,
            };
            return new global::CStructSharp.CStruct(Definition, pointerSize: 4, aligned: false, isLittleEndian: true, compilationOptions: options);
        }

        /// <summary>The layout struct <c>timeval</c>.</summary>
        public sealed partial class Timeval
        {
            /// <summary><c>uint16 sec</c>.</summary>
            public ushort Sec { get; set; }

            /// <summary><c>uint16 usec</c>.</summary>
            public ushort Usec { get; set; }
        }

        /// <summary>The layout struct <c>root</c>.</summary>
        public sealed partial class Root
        {
            /// <summary><c>timeval stamp</c>.</summary>
            public Timeval Stamp { get; set; } = new();

            /// <summary><c>uint8 tail</c>.</summary>
            public byte Tail { get; set; }
        }
    }
}
