// <auto-generated/>
// Generated by CStructSharp from the [CStructLayout] attribute on FixtureUnions. Do not edit.
#nullable enable
#pragma warning disable

namespace Demo
{
    [global::System.CodeDom.Compiler.GeneratedCode("CStructSharp", "<version>")]
    public static partial class FixtureUnions
    {
        /// <summary>The layout text the members of this class were generated from.</summary>
        public const string Definition = "union choice { uint8 narrow; uint16 wide; };";

        /// <summary>The declaration the plain <see cref="Parse"/> and <see cref="Serialize"/> methods operate on.</summary>
        public const string RootName = "choice";

        private static readonly global::System.Lazy<global::CStructSharp.CStruct> LayoutInstance = new(CreateLayout, global::System.Threading.LazyThreadSafetyMode.ExecutionAndPublication);

        /// <summary>The runtime <see cref="global::CStructSharp.CStruct"/> for the same definition and options, built on first use: introspection, JSON, memory images, and the parity oracle.</summary>
        public static global::CStructSharp.CStruct Layout => LayoutInstance.Value;

        private static global::CStructSharp.CStruct CreateLayout()
        {
            var options = new global::CStructSharp.CStructCompilationOptions
            {
                CLongWidth = 64,
                BitfieldPacking = global::CStructSharp.BitfieldPacking.SysV,
                BitfieldAllocation = global::CStructSharp.BitfieldAllocation.LowBitFirst,
            };
            return new global::CStructSharp.CStruct(Definition, pointerSize: 2, aligned: false, isLittleEndian: true, compilationOptions: options);
        }

        /// <summary>The layout union <c>choice</c>.</summary>
        public sealed partial class Choice
        {
            /// <summary>The member a write stores, or <see langword="null"/> for the first member with a value; a read leaves it <see langword="null"/> because an untagged union does not say which view is active.</summary>
            public string? SelectedMember { get; set; }

            /// <summary>The union's stored bytes as read; a write with <see cref="SelectedMember"/> unset and no member value writes them back.</summary>
            public byte[]? RawStorage { get; set; }

            /// <summary><c>uint8 narrow</c>.</summary>
            public byte Narrow { get; set; }

            /// <summary><c>uint16 wide</c>.</summary>
            public ushort Wide { get; set; }
        }
    }
}
