// <auto-generated/>
// Generated by CStructSharp from the [CStructLayout] attribute on FixtureUnions. Do not edit.
#nullable enable
#pragma warning disable

namespace Demo
{
    [global::System.CodeDom.Compiler.GeneratedCode("CStructSharp", "<version>")]
    public static partial class FixtureUnions
    {
        /// <summary>The layout text the members of this class were generated from.</summary>
        public const string Definition = "union choice { uint8 narrow; uint16 wide; };";

        /// <summary>The declaration the plain <see cref="Parse"/> and <see cref="Serialize"/> methods operate on.</summary>
        public const string RootName = "choice";

        private static readonly global::System.Lazy<global::CStructSharp.CStruct> LayoutInstance = new(CreateLayout, global::System.Threading.LazyThreadSafetyMode.ExecutionAndPublication);

        /// <summary>The runtime <see cref="global::CStructSharp.CStruct"/> for the same definition and options, built on first use: introspection, JSON, memory images, and the parity oracle.</summary>
        public static global::CStructSharp.CStruct Layout => LayoutInstance.Value;

        private static global::CStructSharp.CStruct CreateLayout()
        {
            var options = new global::CStructSharp.CStructCompilationOptions
            {
                CLongWidth = 64,
                BitfieldPacking = global::CStructSharp.BitfieldPacking.SysV,
                BitfieldAllocation = global::CStructSharp.BitfieldAllocation.LowBitFirst,
            };
            return new global::CStructSharp.CStruct(Definition, pointerSize: 2, aligned: false, isLittleEndian: true, compilationOptions: options);
        }

        /// <summary>The layout union <c>choice</c>.</summary>
        public sealed partial class Choice
        {
            /// <summary>The member a write stores, or <see langword="null"/> for the first member with a value; a read leaves it <see langword="null"/> because an untagged union does not say which view is active.</summary>
            public string? SelectedMember { get; set; }

            /// <summary>The union's stored bytes as read; a write with <see cref="SelectedMember"/> unset and no member value writes them back.</summary>
            public byte[]? RawStorage { get; set; }

            /// <summary><c>uint8 narrow</c>.</summary>
            public byte Narrow { get; set; }

            /// <summary><c>uint16 wide</c>.</summary>
            public ushort Wide { get; set; }
        }

        private const bool Aligned = false;
        private const bool LittleEndian = true;
        private const int PointerSize = 2;
        private const bool HighBitFirst = false;
        private const global::CStructSharp.BitfieldPacking Packing = global::CStructSharp.BitfieldPacking.SysV;
        private const global::CStructSharp.BitfieldAllocation Allocation = global::CStructSharp.BitfieldAllocation.LowBitFirst;

        /// <summary>Reads one <c>choice</c> from the start of <paramref name="source"/> with the generated reader; the same value, and the same failures, as the runtime's <c>Parse</c>.</summary>
        /// <param name="source">The bytes; offset 0 is coordinate zero.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The read options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The parsed value.</returns>
        public static Choice ParseChoice(global::System.ReadOnlySpan<byte> source, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null)
        {
            var cursor = new global::CStructSharp.Generated.ReadCursor(source, options, "choice");
            try
            {
                return ReadChoice(ref cursor, variables, null, null);
            }
            catch (global::CStructSharp.Diagnostics.CStructException exception)
            {
                cursor.Complete(exception);
                throw;
            }
        }

        /// <inheritdoc cref="ParseChoice(global::System.ReadOnlySpan{byte}, global::System.Collections.Generic.IReadOnlyDictionary{string, int}, global::CStructSharp.ReadOptions)"/>
        public static Choice ParseChoice(byte[] source, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null)
            => ParseChoice(new global::System.ReadOnlySpan<byte>(source ?? throw new global::System.ArgumentNullException(nameof(source))), variables, options);

        /// <inheritdoc cref="ParseChoice(global::System.ReadOnlySpan{byte}, global::System.Collections.Generic.IReadOnlyDictionary{string, int}, global::CStructSharp.ReadOptions)"/>
        public static Choice ParseChoice(global::System.ReadOnlyMemory<byte> source, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null)
            => ParseChoice(source.Span, variables, options);

        /// <summary>Reads one <c>choice</c> from a sequence of segments: a single segment is read in place, several are copied into a pooled buffer bounded by the total read budget.</summary>
        /// <param name="source">The bytes; offset 0 is coordinate zero.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The read options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The parsed value.</returns>
        public static Choice ParseChoice(global::System.Buffers.ReadOnlySequence<byte> source, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null)
        {
            if (source.IsSingleSegment)
            {
                return ParseChoice(source.FirstSpan, variables, options);
            }
            byte[] buffer = global::CStructSharp.Generated.ReadCursor.CopySequence(source, options, out int length);
            try
            {
                return ParseChoice(new global::System.ReadOnlySpan<byte>(buffer, 0, length), variables, options);
            }
            finally
            {
                global::System.Buffers.ArrayPool<byte>.Shared.Return(buffer);
            }
        }

        /// <summary>Reads one <c>choice</c> from <paramref name="stream"/>: the stream is buffered up to the total read budget (or its remaining length) and read through the span reader; a seekable stream is left after the value.</summary>
        /// <param name="stream">The stream, read from its current position.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The read options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The parsed value.</returns>
        public static Choice ParseChoice(global::System.IO.Stream stream, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null)
        {
            global::System.ArgumentNullException.ThrowIfNull(stream);
            long start = stream.CanSeek ? stream.Position : 0;
            byte[] buffer = global::CStructSharp.Generated.ReadCursor.BufferStream(stream, options, out int length);
            try
            {
                return ParseChoiceBuffered(buffer, length, stream, start, variables, options);
            }
            finally
            {
                global::System.Buffers.ArrayPool<byte>.Shared.Return(buffer);
            }
        }

        /// <summary>Reads one <c>choice</c> from <paramref name="stream"/> with the bytes read by <see cref="global::System.IO.Stream.ReadAsync(global::System.Memory{byte}, global::System.Threading.CancellationToken)"/>: the same buffering and the same reader as the synchronous form; a seekable stream is left after the value (at its origin on failure), a stream that cannot seek is consumed up to the total read budget plus one byte. A stored absolute pointer address counts from the origin, as in the span form.</summary>
        /// <param name="stream">The stream, read from its current position.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The read options; <see langword="null"/> uses the documented defaults.</param>
        /// <param name="cancellationToken">Ends the read while it waits for bytes or at the next boundary the reader checks; linked with the options' token.</param>
        /// <returns>The parsed value.</returns>
        public static async global::System.Threading.Tasks.ValueTask<Choice> ParseChoiceAsync(global::System.IO.Stream stream, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null, global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::System.ArgumentNullException.ThrowIfNull(stream);
            global::CStructSharp.ReadOptions? effective = global::CStructSharp.Generated.ReadCursor.WithCancellation(options, cancellationToken, out global::System.Threading.CancellationTokenSource? linked);
            using (linked)
            {
                long start = stream.CanSeek ? stream.Position : 0;
                (byte[] buffer, int length) = await global::CStructSharp.Generated.ReadCursor.BufferStreamAsync(stream, effective, effective?.CancellationToken ?? default).ConfigureAwait(false);
                try
                {
                    return ParseChoiceBuffered(buffer, length, stream, start, variables, effective);
                }
                finally
                {
                    global::System.Buffers.ArrayPool<byte>.Shared.Return(buffer);
                }
            }
        }

        /// <summary>The synchronous half of the stream forms: the span reader over the buffered bytes, then the stream's final position (after the value, or the origin on failure).</summary>
        private static Choice ParseChoiceBuffered(byte[] buffer, int length, global::System.IO.Stream stream, long start, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables, global::CStructSharp.ReadOptions? options)
        {
            var cursor = new global::CStructSharp.Generated.ReadCursor(new global::System.ReadOnlySpan<byte>(buffer, 0, length), options, "choice");
            try
            {
                Choice value = ReadChoice(ref cursor, variables, null, null);
                if (stream.CanSeek)
                {
                    stream.Position = start + cursor.Position;
                }
                return value;
            }
            catch (global::CStructSharp.Diagnostics.CStructException exception)
            {
                cursor.Complete(exception);
                if (stream.CanSeek)
                {
                    stream.Position = start;
                }
                throw;
            }
        }

        /// <summary>Reads the root declaration (<c>choice</c>); see <see cref="ParseChoice(global::System.ReadOnlySpan{byte}, global::System.Collections.Generic.IReadOnlyDictionary{string, int}, global::CStructSharp.ReadOptions)"/>.</summary>
        /// <param name="source">The bytes; offset 0 is coordinate zero.</param>
        /// <param name="options">The read options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The parsed value.</returns>
        public static Choice Parse(global::System.ReadOnlySpan<byte> source, global::CStructSharp.ReadOptions? options = null) => ParseChoice(source, null, options);

        /// <inheritdoc cref="Parse(global::System.ReadOnlySpan{byte}, global::CStructSharp.ReadOptions)"/>
        public static Choice Parse(byte[] source, global::CStructSharp.ReadOptions? options = null) => ParseChoice(source, null, options);

        /// <inheritdoc cref="Parse(global::System.ReadOnlySpan{byte}, global::CStructSharp.ReadOptions)"/>
        public static Choice Parse(global::System.ReadOnlyMemory<byte> source, global::CStructSharp.ReadOptions? options = null) => ParseChoice(source.Span, null, options);

        /// <inheritdoc cref="ParseChoice(global::System.Buffers.ReadOnlySequence{byte}, global::System.Collections.Generic.IReadOnlyDictionary{string, int}, global::CStructSharp.ReadOptions)"/>
        public static Choice Parse(global::System.Buffers.ReadOnlySequence<byte> source, global::CStructSharp.ReadOptions? options = null) => ParseChoice(source, null, options);

        /// <inheritdoc cref="ParseChoice(global::System.IO.Stream, global::System.Collections.Generic.IReadOnlyDictionary{string, int}, global::CStructSharp.ReadOptions)"/>
        public static Choice Parse(global::System.IO.Stream stream, global::CStructSharp.ReadOptions? options = null) => ParseChoice(stream, null, options);

        /// <inheritdoc cref="ParseChoiceAsync(global::System.IO.Stream, global::System.Collections.Generic.IReadOnlyDictionary{string, int}, global::CStructSharp.ReadOptions, global::System.Threading.CancellationToken)"/>
        public static global::System.Threading.Tasks.ValueTask<Choice> ParseAsync(global::System.IO.Stream stream, global::CStructSharp.ReadOptions? options = null, global::System.Threading.CancellationToken cancellationToken = default) => ParseChoiceAsync(stream, null, options, cancellationToken);

        /// <summary>Reads one <c>choice</c> at the cursor's position.</summary>
        private static Choice ReadChoice(ref global::CStructSharp.Generated.ReadCursor cursor, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables, string? member, string? memberType)
        {
            cursor.EnterComposite(member ?? "choice", memberType);
            var value = new Choice();
            int unionStart = cursor.Position;
            value.RawStorage = cursor.Take(2, member, memberType).ToArray();
            cursor.EnterUnion();
            cursor.Position = unionStart;
            // uint8 narrow
            {
                value.Narrow = cursor.Take(1, "narrow", "uint8")[0];
            }
            cursor.Position = unionStart;
            // uint16 wide
            {
                value.Wide = global::CStructSharp.Generated.Codec.ReadUInt16(cursor.Take(2, "wide", "uint16"), true);
            }
            cursor.ExitUnion();
            cursor.Position = unionStart + 2;
            cursor.ExitComposite();
            return value;
        }

        /// <summary>Groups a flat element array into rows of <paramref name="inner"/> elements (one nesting level of a multidimensional array).</summary>
        private static T[][] Split<T>(T[] flat, int inner)
        {
            var rows = new T[inner == 0 ? 0 : flat.Length / inner][];
            for (int row = 0; row < rows.Length; row++)
            {
                rows[row] = new T[inner];
                global::System.Array.Copy(flat, row * inner, rows[row], 0, inner);
            }
            return rows;
        }

        /// <summary>Writes one <c>choice</c> into a new array with the generated writer; the same bytes, and the same failures, as the runtime's <c>Serialize</c>.</summary>
        /// <param name="value">The value to write.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The write options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The serialized bytes.</returns>
        public static byte[] SerializeChoice(Choice value, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.WriteOptions? options = null)
        {
            var cursor = new global::CStructSharp.Generated.WriteCursor(options, "choice");
            try
            {
                EncodeChoice(ref cursor, value, variables, null, null);
                return cursor.ToArray();
            }
            catch (global::CStructSharp.Diagnostics.CStructException exception)
            {
                cursor.Complete(exception);
                throw;
            }
            finally
            {
                cursor.Dispose();
            }
        }

        /// <summary>Writes one <c>choice</c> into <paramref name="destination"/>; a value that does not fit fails with the runtime's capacity message.</summary>
        /// <param name="value">The value to write.</param>
        /// <param name="destination">The bytes to write into.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The write options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The number of bytes written.</returns>
        public static int SerializeChoice(Choice value, global::System.Span<byte> destination, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.WriteOptions? options = null)
        {
            var cursor = new global::CStructSharp.Generated.WriteCursor(destination, options, "choice");
            try
            {
                EncodeChoice(ref cursor, value, variables, null, null);
                return cursor.Length;
            }
            catch (global::CStructSharp.Diagnostics.CStructException exception)
            {
                cursor.Complete(exception);
                throw;
            }
        }

        /// <summary>Writes one <c>choice</c> to <paramref name="stream"/> at its current position.</summary>
        /// <param name="stream">The destination stream.</param>
        /// <param name="value">The value to write.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The write options; <see langword="null"/> uses the documented defaults.</param>
        public static void WriteChoice(global::System.IO.Stream stream, Choice value, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.WriteOptions? options = null)
        {
            global::System.ArgumentNullException.ThrowIfNull(stream);
            if (!stream.CanWrite)
            {
                throw new global::System.ArgumentException("Writing requires a writable stream.", nameof(stream));
            }
            byte[] bytes = SerializeChoice(value, variables, options);
            stream.Write(bytes, 0, bytes.Length);
        }

        /// <summary>Writes one <c>choice</c> to <paramref name="stream"/> with <see cref="global::System.IO.Stream.WriteAsync(global::System.ReadOnlyMemory{byte}, global::System.Threading.CancellationToken)"/>: the value is serialized first (a validation failure writes nothing), then sent in one write.</summary>
        /// <param name="stream">The writable stream; the current position is the output origin.</param>
        /// <param name="value">The value to write.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The write options; <see langword="null"/> uses the documented defaults.</param>
        /// <param name="cancellationToken">Ends the write before the bytes are sent or at the next boundary the writer checks; linked with the options' token.</param>
        /// <returns>A task that completes when the bytes have been written.</returns>
        public static async global::System.Threading.Tasks.ValueTask WriteChoiceAsync(global::System.IO.Stream stream, Choice value, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.WriteOptions? options = null, global::System.Threading.CancellationToken cancellationToken = default)
        {
            global::System.ArgumentNullException.ThrowIfNull(stream);
            if (!stream.CanWrite)
            {
                throw new global::System.ArgumentException("Writing requires a writable stream.", nameof(stream));
            }
            global::CStructSharp.WriteOptions? effective = global::CStructSharp.Generated.WriteCursor.WithCancellation(options, cancellationToken, out global::System.Threading.CancellationTokenSource? linked);
            using (linked)
            {
                byte[] bytes = SerializeChoice(value, variables, effective);
                await stream.WriteAsync(bytes, effective?.CancellationToken ?? default).ConfigureAwait(false);
            }
        }

        /// <summary>Writes the root declaration (<c>choice</c>) into a new array; see <see cref="SerializeChoice(Choice, global::System.Collections.Generic.IReadOnlyDictionary{string, int}, global::CStructSharp.WriteOptions)"/>.</summary>
        /// <param name="value">The value to write.</param>
        /// <param name="options">The write options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The serialized bytes.</returns>
        public static byte[] Serialize(Choice value, global::CStructSharp.WriteOptions? options = null) => SerializeChoice(value, null, options);

        /// <summary>Writes the root declaration (<c>choice</c>) into <paramref name="destination"/>.</summary>
        /// <param name="value">The value to write.</param>
        /// <param name="destination">The bytes to write into.</param>
        /// <param name="options">The write options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The number of bytes written.</returns>
        public static int Serialize(Choice value, global::System.Span<byte> destination, global::CStructSharp.WriteOptions? options = null) => SerializeChoice(value, destination, null, options);

        /// <summary>Writes the root declaration (<c>choice</c>) to <paramref name="stream"/>.</summary>
        /// <param name="stream">The destination stream.</param>
        /// <param name="value">The value to write.</param>
        /// <param name="options">The write options; <see langword="null"/> uses the documented defaults.</param>
        public static void Write(global::System.IO.Stream stream, Choice value, global::CStructSharp.WriteOptions? options = null) => WriteChoice(stream, value, null, options);

        /// <inheritdoc cref="WriteChoiceAsync(global::System.IO.Stream, Choice, global::System.Collections.Generic.IReadOnlyDictionary{string, int}, global::CStructSharp.WriteOptions, global::System.Threading.CancellationToken)"/>
        public static global::System.Threading.Tasks.ValueTask WriteAsync(global::System.IO.Stream stream, Choice value, global::CStructSharp.WriteOptions? options = null, global::System.Threading.CancellationToken cancellationToken = default) => WriteChoiceAsync(stream, value, null, options, cancellationToken);

        /// <summary>Writes one <c>choice</c> at the cursor's position.</summary>
        private static void EncodeChoice(ref global::CStructSharp.Generated.WriteCursor cursor, Choice? value, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables, string? member, string? memberType)
        {
            if (value is null)
            {
                throw cursor.Fail("Null is not valid for struct or union value: choice", member, memberType);
            }
            cursor.EnterComposite(member ?? "choice", memberType);
            int unionStart = cursor.Position;
            if (value.SelectedMember is null)
            {
                if (value.RawStorage is null)
                {
                    throw cursor.Fail("A whole union write requires SelectedMember or RawStorage: choice", member, memberType);
                }
                if (value.RawStorage.Length != 2)
                {
                    throw cursor.Fail("Raw storage length mismatch for choice: expected 2, got " + value.RawStorage.Length.ToString(global::System.Globalization.CultureInfo.InvariantCulture) + ".", member, memberType);
                }
                new global::System.ReadOnlySpan<byte>(value.RawStorage).CopyTo(cursor.Reserve(2, member, memberType));
                cursor.ExitComposite();
                return;
            }
            cursor.Pad(2, member, memberType);
            cursor.Position = unionStart;
            switch (value.SelectedMember)
            {
            case "narrow":
                // uint8 narrow
                {
                    cursor.Reserve(1, "narrow", "uint8")[0] = value.Narrow;
                }
                break;
            case "wide":
                // uint16 wide
                {
                    global::CStructSharp.Generated.Codec.WriteUInt16(cursor.Reserve(2, "wide", "uint16"), value.Wide, true);
                }
                break;
            default:
                throw cursor.Fail("Union 'choice' has no member named '" + value.SelectedMember + "'.", member, memberType);
            }
            cursor.Position = unionStart + 2;
            cursor.ExitComposite();
        }

        /// <summary>The root declaration as <see cref="global::CStructSharp.ICStructGenerated{Choice}"/>.</summary>
        public sealed partial class Choice : global::CStructSharp.ICStructGenerated<Choice>
        {
            /// <inheritdoc/>
            static global::CStructSharp.CStruct global::CStructSharp.ICStructGenerated<Choice>.Layout => FixtureUnions.Layout;

            /// <inheritdoc/>
            static string global::CStructSharp.ICStructGenerated<Choice>.RootName => FixtureUnions.RootName;

            /// <inheritdoc/>
            static Choice global::CStructSharp.ICStructGenerated<Choice>.Parse(global::System.ReadOnlySpan<byte> source, global::CStructSharp.ReadOptions? options) => FixtureUnions.Parse(source, options);

            /// <inheritdoc/>
            static int global::CStructSharp.ICStructGenerated<Choice>.Serialize(Choice value, global::System.Span<byte> destination, global::CStructSharp.WriteOptions? options) => FixtureUnions.Serialize(value, destination, options);
        }

        /// <summary>The runtime's <see cref="global::CStructSharp.Values.StructValue"/> for a generated value: its bytes, parsed by the runtime layout (every member, in the layout's shape). Pointers keep their addresses and are not followed: the value's bytes hold no targets.</summary>
        /// <param name="value">The value to convert.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The read options for the runtime parse (limits, text trimming); <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The struct value.</returns>
        public static global::CStructSharp.Values.StructValue ToStructValue(Choice value, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null)
        {
            byte[] bytes = SerializeChoice(value, variables);
            var effective = new global::CStructSharp.ReadOptions
            {
                DereferencePointers = false,
                AddressingMode = options?.AddressingMode ?? global::CStructSharp.PointerAddressingMode.Absolute,
                Origin = options?.Origin ?? 0,
                MaxPointerDepth = options?.MaxPointerDepth ?? 64,
                MaxPointerTargetBytes = options?.MaxPointerTargetBytes,
                MaxArrayElements = options?.MaxArrayElements ?? 1_000_000,
                MaxStringBytes = options?.MaxStringBytes ?? (16L * 1024 * 1024),
                MaxTotalBytesRead = options?.MaxTotalBytesRead ?? (64L * 1024 * 1024),
                MaxNestingDepth = options?.MaxNestingDepth ?? 256,
                TrimFixedText = options?.TrimFixedText ?? false,
            };
            return Layout.Parse(bytes, "choice", variables, effective);
        }

        /// <summary>Maps a generated value to a mapped class through the runtime's <see cref="global::CStructSharp.Values.StructValue"/>: <c>ToMapped&lt;MyRoot&gt;(value)</c>.</summary>
        /// <typeparam name="T">A class implementing <see cref="global::CStructSharp.ICStructMapped{TSelf}"/>.</typeparam>
        /// <param name="value">The value to map.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <returns>The mapped instance.</returns>
        public static T ToMapped<T>(Choice value, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null)
            where T : global::CStructSharp.ICStructMapped<T>
            => T.ReadFrom(ToStructValue(value, variables));

        /// <summary>Serializes a mapped instance as the root declaration through the runtime layout (its <c>WriteTo</c> supplies the members).</summary>
        /// <typeparam name="T">A class implementing <see cref="global::CStructSharp.ICStructMapped{TSelf}"/>, registered with <see cref="global::CStructSharp.MappedTypes"/>.</typeparam>
        /// <param name="value">The instance to write.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The write options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The serialized bytes.</returns>
        public static byte[] SerializeMapped<T>(T value, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.WriteOptions? options = null)
            where T : global::CStructSharp.ICStructMapped<T>
            => Layout.Serialize("choice", value!, variables, options);

        /// <summary>Reads the root declaration straight into a mapped class through the runtime layout.</summary>
        /// <typeparam name="T">A class implementing <see cref="global::CStructSharp.ICStructMapped{TSelf}"/>.</typeparam>
        /// <param name="source">The bytes; offset 0 is coordinate zero.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The read options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The mapped instance.</returns>
        public static T ParseMapped<T>(global::System.ReadOnlySpan<byte> source, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null)
            where T : global::CStructSharp.ICStructMapped<T>
            => T.ReadFrom(Layout.Parse(source, "choice", variables, options));

        /// <summary>Reads the root declaration with the generated reader and the runtime's debug ranges (the runtime reads the same bytes once more to produce them).</summary>
        /// <param name="source">The bytes; offset 0 is coordinate zero.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The read options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The parsed value and one <see cref="global::CStructSharp.Diagnostics.DebugData"/> per value read, in read order.</returns>
        public static (Choice Value, global::System.Collections.Generic.IReadOnlyList<global::CStructSharp.Diagnostics.DebugData> Debug) ParseWithDebug(global::System.ReadOnlySpan<byte> source, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null)
        {
            Choice value = ParseChoice(source, variables, options);
            return (value, Layout.ParseWithDebug(source, "choice", variables, options).Debug);
        }

        /// <summary>Resolves a path (<c>choice.field</c>, <c>items[2].value</c>, ...) to its byte address with the runtime layout.</summary>
        /// <param name="source">The bytes; offset 0 is coordinate zero.</param>
        /// <param name="path">The path, in the runtime's path grammar.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The read options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The address of the selected value.</returns>
        public static long ResolveAddress(global::System.ReadOnlySpan<byte> source, string path, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null) => Layout.ResolveAddress(source, path, variables, options);

        /// <summary>The element count of an array or string selected by a path, with the runtime layout.</summary>
        /// <param name="source">The bytes; offset 0 is coordinate zero.</param>
        /// <param name="path">The path, in the runtime's path grammar.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The read options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The element count.</returns>
        public static int GetArrayLength(global::System.ReadOnlySpan<byte> source, string path, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null) => Layout.GetArrayLength(source, path, variables, options);

        /// <summary>Replaces one value in place by path with the runtime layout; statically placed members also have typed setters in <see cref="Update"/>.</summary>
        /// <param name="target">The bytes holding the value.</param>
        /// <param name="path">The path, in the runtime's path grammar.</param>
        /// <param name="value">The new value.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The update options; <see langword="null"/> uses the documented defaults.</param>
        public static void UpdatePath(global::System.Span<byte> target, string path, object value, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.UpdateOptions? options = null) => Layout.Update(target, path, value, variables, options);

        /// <summary>The size in bytes of every composite with a static size (<c>sizeof</c>); a runtime-sized composite has none.</summary>
        public static class Sizes
        {
            /// <summary><c>sizeof(choice)</c>.</summary>
            public const int Choice = 2;
        }

        /// <summary>
        ///     A zero-allocation view of one <c>choice</c> over its bytes: each statically placed member decodes
        ///     directly from the span when read; a member the view does not expose (runtime-sized, conditional, or placed after one)
        ///     is reached through <see cref="ToObject"/>. A view cannot leave the method that created it.
        /// </summary>
        public readonly ref struct ChoiceView
        {
            private readonly global::System.ReadOnlySpan<byte> source;
            private readonly global::CStructSharp.ReadOptions? options;

            /// <summary>Creates a view over <paramref name="source"/>, whose first byte is the value's first byte; the source must hold the value's 2 bytes.</summary>
            /// <param name="source">The bytes, from the value's start; more may follow (pointer targets, the rest of the input).</param>
            /// <param name="options">The read options <see cref="ToObject"/> uses; <see langword="null"/> uses the documented defaults.</param>
            public ChoiceView(global::System.ReadOnlySpan<byte> source, global::CStructSharp.ReadOptions? options = null)
            {
                if (source.Length < 2)
                {
                    var cursor = new global::CStructSharp.Generated.ReadCursor(source, options, "choice");
                    global::CStructSharp.Diagnostics.CStructException failure = cursor.Fail(global::CStructSharp.Generated.ReadCursor.ShortReadText(2, source.Length), null, null);
                    cursor.Complete(failure);
                    throw failure;
                }
                this.source = source;
                this.options = options;
            }

            /// <summary>Gets the value's bytes (its 2 bytes).</summary>
            public global::System.ReadOnlySpan<byte> Bytes => this.source.Slice(0, 2);

            /// <summary><c>uint8 narrow</c> at offset 0.</summary>
            public byte Narrow => this.source.Slice(0, 1)[0];

            /// <summary><c>uint16 wide</c> at offset 0.</summary>
            public ushort Wide => global::CStructSharp.Generated.Codec.ReadUInt16(this.source.Slice(0, 2), true);

            /// <summary>Reads the whole value with the generated reader (every member, runtime-sized ones included).</summary>
            /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
            /// <returns>The value.</returns>
            public Choice ToObject(global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null)
            {
                var cursor = new global::CStructSharp.Generated.ReadCursor(this.source, this.options, "choice");
                try
                {
                    return ReadChoice(ref cursor, variables, null, null);
                }
                catch (global::CStructSharp.Diagnostics.CStructException exception)
                {
                    cursor.Complete(exception);
                    throw;
                }
            }
        }
    }
}
