// <auto-generated/>
// Generated by CStructSharp from the [CStructLayout] attribute on FixtureBitfieldAllocation. Do not edit.
#nullable enable
#pragma warning disable

namespace Demo
{
    [global::System.CodeDom.Compiler.GeneratedCode("CStructSharp", "<version>")]
    public static partial class FixtureBitfieldAllocation
    {
        /// <summary>The layout text the members of this class were generated from.</summary>
        public const string Definition = "struct root { uint16 a : 4; uint16 b : 12; uint8 c : 3; uint8 d : 5; };";

        /// <summary>The declaration the plain <see cref="Parse"/> and <see cref="Serialize"/> methods operate on.</summary>
        public const string RootName = "root";

        private static readonly global::System.Lazy<global::CStructSharp.CStruct> LayoutInstance = new(CreateLayout, global::System.Threading.LazyThreadSafetyMode.ExecutionAndPublication);

        /// <summary>The runtime <see cref="global::CStructSharp.CStruct"/> for the same definition and options, built on first use: introspection, JSON, memory images, and the parity oracle.</summary>
        public static global::CStructSharp.CStruct Layout => LayoutInstance.Value;

        private static global::CStructSharp.CStruct CreateLayout()
        {
            var options = new global::CStructSharp.CStructCompilationOptions
            {
                CLongWidth = 64,
                BitfieldPacking = global::CStructSharp.BitfieldPacking.SysV,
                BitfieldAllocation = global::CStructSharp.BitfieldAllocation.HighBitFirst,
            };
            return new global::CStructSharp.CStruct(Definition, pointerSize: 8, aligned: false, isLittleEndian: false, compilationOptions: options);
        }

        /// <summary>The layout struct <c>root</c>.</summary>
        public sealed partial class Root
        {
            /// <summary><c>uint16 a : 4</c>.</summary>
            public ushort A { get; set; }

            /// <summary><c>uint16 b : 12</c>.</summary>
            public ushort B { get; set; }

            /// <summary><c>uint8 c : 3</c>.</summary>
            public byte C { get; set; }

            /// <summary><c>uint8 d : 5</c>.</summary>
            public byte D { get; set; }
        }
    }
}
