// <auto-generated/>
// Generated by CStructSharp from the [CStructLayout] attribute on Options. Do not edit.
#nullable enable
#pragma warning disable

namespace Demo
{
    [global::System.CodeDom.Compiler.GeneratedCode("CStructSharp", "<version>")]
    public static partial class Options
    {
        /// <summary>The layout text the members of this class were generated from.</summary>
        public const string Definition = "#ifdef WIDE\nstruct root { long a; uint8 b_c:3; uint8 d:5; uint32 e; };\n#else\nstruct root { uint16 a; uint8 b_c:3; uint8 d:5; uint32 e; };\n#endif";

        /// <summary>The declaration the plain <see cref="Parse"/> and <see cref="Serialize"/> methods operate on.</summary>
        public const string RootName = "root";

        private static readonly global::System.Lazy<global::CStructSharp.CStruct> LayoutInstance = new(CreateLayout, global::System.Threading.LazyThreadSafetyMode.ExecutionAndPublication);

        /// <summary>The runtime <see cref="global::CStructSharp.CStruct"/> for the same definition and options, built on first use: introspection, JSON, memory images, and the parity oracle.</summary>
        public static global::CStructSharp.CStruct Layout => LayoutInstance.Value;

        private static global::CStructSharp.CStruct CreateLayout()
        {
            var options = new global::CStructSharp.CStructCompilationOptions
            {
                CLongWidth = 64,
                BitfieldPacking = global::CStructSharp.BitfieldPacking.SysV,
                BitfieldAllocation = global::CStructSharp.BitfieldAllocation.LowBitFirst,
            };
            return new global::CStructSharp.CStruct(Definition, pointerSize: 8, aligned: false, isLittleEndian: false, compilationOptions: options);
        }

        /// <summary>The layout struct <c>root</c>.</summary>
        public sealed partial class Root
        {
            /// <summary><c>uint16 a</c>.</summary>
            public ushort A { get; set; }

            /// <summary><c>uint8 b_c : 3</c>.</summary>
            public byte BC { get; set; }

            /// <summary><c>uint8 d : 5</c>.</summary>
            public byte D { get; set; }

            /// <summary><c>uint32 e</c>.</summary>
            public uint E { get; set; }
        }

        private const bool Aligned = false;
        private const bool LittleEndian = false;
        private const int PointerSize = 8;
        private const bool HighBitFirst = false;
        private const global::CStructSharp.BitfieldPacking Packing = global::CStructSharp.BitfieldPacking.SysV;
        private const global::CStructSharp.BitfieldAllocation Allocation = global::CStructSharp.BitfieldAllocation.LowBitFirst;

        /// <summary>Reads one <c>root</c> from the start of <paramref name="source"/> with the generated reader; the same value, and the same failures, as the runtime's <c>Parse</c>.</summary>
        /// <param name="source">The bytes; offset 0 is coordinate zero.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The read options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The parsed value.</returns>
        public static Root ParseRoot(global::System.ReadOnlySpan<byte> source, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null)
        {
            var cursor = new global::CStructSharp.Generated.ReadCursor(source, options, "root");
            try
            {
                return ReadRoot(ref cursor, variables, null, null);
            }
            catch (global::CStructSharp.Diagnostics.CStructException exception)
            {
                cursor.Complete(exception);
                throw;
            }
        }

        /// <inheritdoc cref="ParseRoot(global::System.ReadOnlySpan{byte}, global::System.Collections.Generic.IReadOnlyDictionary{string, int}, global::CStructSharp.ReadOptions)"/>
        public static Root ParseRoot(byte[] source, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null)
            => ParseRoot(new global::System.ReadOnlySpan<byte>(source ?? throw new global::System.ArgumentNullException(nameof(source))), variables, options);

        /// <inheritdoc cref="ParseRoot(global::System.ReadOnlySpan{byte}, global::System.Collections.Generic.IReadOnlyDictionary{string, int}, global::CStructSharp.ReadOptions)"/>
        public static Root ParseRoot(global::System.ReadOnlyMemory<byte> source, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null)
            => ParseRoot(source.Span, variables, options);

        /// <summary>Reads one <c>root</c> from a sequence of segments: a single segment is read in place, several are copied into a pooled buffer bounded by the total read budget.</summary>
        /// <param name="source">The bytes; offset 0 is coordinate zero.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The read options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The parsed value.</returns>
        public static Root ParseRoot(global::System.Buffers.ReadOnlySequence<byte> source, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null)
        {
            if (source.IsSingleSegment)
            {
                return ParseRoot(source.FirstSpan, variables, options);
            }
            byte[] buffer = global::CStructSharp.Generated.ReadCursor.CopySequence(source, options, out int length);
            try
            {
                return ParseRoot(new global::System.ReadOnlySpan<byte>(buffer, 0, length), variables, options);
            }
            finally
            {
                global::System.Buffers.ArrayPool<byte>.Shared.Return(buffer);
            }
        }

        /// <summary>Reads one <c>root</c> from <paramref name="stream"/>: the stream is buffered up to the total read budget (or its remaining length) and read through the span reader; a seekable stream is left after the value.</summary>
        /// <param name="stream">The stream, read from its current position.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The read options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The parsed value.</returns>
        public static Root ParseRoot(global::System.IO.Stream stream, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null)
        {
            global::System.ArgumentNullException.ThrowIfNull(stream);
            long start = stream.CanSeek ? stream.Position : 0;
            byte[] buffer = global::CStructSharp.Generated.ReadCursor.BufferStream(stream, options, out int length);
            try
            {
                var cursor = new global::CStructSharp.Generated.ReadCursor(new global::System.ReadOnlySpan<byte>(buffer, 0, length), options, "root");
                try
                {
                    Root value = ReadRoot(ref cursor, variables, null, null);
                    if (stream.CanSeek)
                    {
                        stream.Position = start + cursor.Position;
                    }
                    return value;
                }
                catch (global::CStructSharp.Diagnostics.CStructException exception)
                {
                    cursor.Complete(exception);
                    throw;
                }
            }
            finally
            {
                global::System.Buffers.ArrayPool<byte>.Shared.Return(buffer);
            }
        }

        /// <summary>Reads the root declaration (<c>root</c>); see <see cref="ParseRoot(global::System.ReadOnlySpan{byte}, global::System.Collections.Generic.IReadOnlyDictionary{string, int}, global::CStructSharp.ReadOptions)"/>.</summary>
        /// <param name="source">The bytes; offset 0 is coordinate zero.</param>
        /// <param name="options">The read options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The parsed value.</returns>
        public static Root Parse(global::System.ReadOnlySpan<byte> source, global::CStructSharp.ReadOptions? options = null) => ParseRoot(source, null, options);

        /// <inheritdoc cref="Parse(global::System.ReadOnlySpan{byte}, global::CStructSharp.ReadOptions)"/>
        public static Root Parse(byte[] source, global::CStructSharp.ReadOptions? options = null) => ParseRoot(source, null, options);

        /// <inheritdoc cref="Parse(global::System.ReadOnlySpan{byte}, global::CStructSharp.ReadOptions)"/>
        public static Root Parse(global::System.ReadOnlyMemory<byte> source, global::CStructSharp.ReadOptions? options = null) => ParseRoot(source.Span, null, options);

        /// <inheritdoc cref="ParseRoot(global::System.Buffers.ReadOnlySequence{byte}, global::System.Collections.Generic.IReadOnlyDictionary{string, int}, global::CStructSharp.ReadOptions)"/>
        public static Root Parse(global::System.Buffers.ReadOnlySequence<byte> source, global::CStructSharp.ReadOptions? options = null) => ParseRoot(source, null, options);

        /// <inheritdoc cref="ParseRoot(global::System.IO.Stream, global::System.Collections.Generic.IReadOnlyDictionary{string, int}, global::CStructSharp.ReadOptions)"/>
        public static Root Parse(global::System.IO.Stream stream, global::CStructSharp.ReadOptions? options = null) => ParseRoot(stream, null, options);

        /// <summary>Reads one <c>root</c> at the cursor's position.</summary>
        private static Root ReadRoot(ref global::CStructSharp.Generated.ReadCursor cursor, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables, string? member, string? memberType)
        {
            cursor.EnterComposite(member ?? "root", memberType);
            var value = new Root();
            var placement = global::CStructSharp.Generated.CompositeCursor.Start(cursor.Position, Aligned, Packing, Allocation);
            // uint16 a
            {
                cursor.Seek(placement.AdvanceToField(2), "a", "uint16");
                value.A = global::CStructSharp.Generated.Codec.ReadUInt16(cursor.Take(2, "a", "uint16"), false);
                placement.CompleteField(cursor.Position);
            }
            // uint8 b_c : 3
            {
                var slot = placement.AdvanceToBitfield(1, 1, 3, 8, false, "b_c");
                cursor.Seek(slot.UnitStart, "b_c", "uint8");
                ulong unit = global::CStructSharp.Generated.Codec.ReadUnsigned(cursor.Take(slot.UnitSize, "b_c", "uint8"), false);
                if (slot.BitOffset + 3 > slot.UnitSize * 8)
                {
                    throw cursor.Fail("Bitfield exceeds its storage unit: b_c", "b_c", "uint8");
                }
                ulong bits = global::CStructSharp.Generated.Codec.ExtractBits(unit, global::CStructSharp.Generated.Codec.BitfieldShift(slot.BitOffset, 3, slot.UnitSize * 8, HighBitFirst), 3);
                if ((slot.BitOffset + 3) / 8 + 1 <= slot.UnitSize)
                {
                    cursor.Position = (int)slot.UnitStart;
                }
                value.BC = (byte)bits;
            }
            // uint8 d : 5
            {
                var slot = placement.AdvanceToBitfield(1, 1, 5, 8, false, "d");
                cursor.Seek(slot.UnitStart, "d", "uint8");
                ulong unit = global::CStructSharp.Generated.Codec.ReadUnsigned(cursor.Take(slot.UnitSize, "d", "uint8"), false);
                if (slot.BitOffset + 5 > slot.UnitSize * 8)
                {
                    throw cursor.Fail("Bitfield exceeds its storage unit: d", "d", "uint8");
                }
                ulong bits = global::CStructSharp.Generated.Codec.ExtractBits(unit, global::CStructSharp.Generated.Codec.BitfieldShift(slot.BitOffset, 5, slot.UnitSize * 8, HighBitFirst), 5);
                if ((slot.BitOffset + 5) / 8 + 1 <= slot.UnitSize)
                {
                    cursor.Position = (int)slot.UnitStart;
                }
                value.D = (byte)bits;
            }
            // uint32 e
            {
                cursor.Seek(placement.AdvanceToField(4), "e", "uint32");
                value.E = global::CStructSharp.Generated.Codec.ReadUInt32(cursor.Take(4, "e", "uint32"), false);
                placement.CompleteField(cursor.Position);
            }
            cursor.Seek(placement.Finish(4), member, memberType);
            cursor.ExitComposite();
            return value;
        }

        /// <summary>Groups a flat element array into rows of <paramref name="inner"/> elements (one nesting level of a multidimensional array).</summary>
        private static T[][] Split<T>(T[] flat, int inner)
        {
            var rows = new T[inner == 0 ? 0 : flat.Length / inner][];
            for (int row = 0; row < rows.Length; row++)
            {
                rows[row] = new T[inner];
                global::System.Array.Copy(flat, row * inner, rows[row], 0, inner);
            }
            return rows;
        }

        /// <summary>Writes one <c>root</c> into a new array with the generated writer; the same bytes, and the same failures, as the runtime's <c>Serialize</c>.</summary>
        /// <param name="value">The value to write.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The write options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The serialized bytes.</returns>
        public static byte[] SerializeRoot(Root value, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.WriteOptions? options = null)
        {
            var cursor = new global::CStructSharp.Generated.WriteCursor(options, "root");
            try
            {
                EncodeRoot(ref cursor, value, variables, null, null);
                return cursor.ToArray();
            }
            catch (global::CStructSharp.Diagnostics.CStructException exception)
            {
                cursor.Complete(exception);
                throw;
            }
            finally
            {
                cursor.Dispose();
            }
        }

        /// <summary>Writes one <c>root</c> into <paramref name="destination"/>; a value that does not fit fails with the runtime's capacity message.</summary>
        /// <param name="value">The value to write.</param>
        /// <param name="destination">The bytes to write into.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The write options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The number of bytes written.</returns>
        public static int SerializeRoot(Root value, global::System.Span<byte> destination, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.WriteOptions? options = null)
        {
            var cursor = new global::CStructSharp.Generated.WriteCursor(destination, options, "root");
            try
            {
                EncodeRoot(ref cursor, value, variables, null, null);
                return cursor.Length;
            }
            catch (global::CStructSharp.Diagnostics.CStructException exception)
            {
                cursor.Complete(exception);
                throw;
            }
        }

        /// <summary>Writes one <c>root</c> to <paramref name="stream"/> at its current position.</summary>
        /// <param name="stream">The destination stream.</param>
        /// <param name="value">The value to write.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The write options; <see langword="null"/> uses the documented defaults.</param>
        public static void WriteRoot(global::System.IO.Stream stream, Root value, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.WriteOptions? options = null)
        {
            global::System.ArgumentNullException.ThrowIfNull(stream);
            if (!stream.CanWrite)
            {
                throw new global::System.ArgumentException("Writing requires a writable stream.", nameof(stream));
            }
            byte[] bytes = SerializeRoot(value, variables, options);
            stream.Write(bytes, 0, bytes.Length);
        }

        /// <summary>Writes the root declaration (<c>root</c>) into a new array; see <see cref="SerializeRoot(Root, global::System.Collections.Generic.IReadOnlyDictionary{string, int}, global::CStructSharp.WriteOptions)"/>.</summary>
        /// <param name="value">The value to write.</param>
        /// <param name="options">The write options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The serialized bytes.</returns>
        public static byte[] Serialize(Root value, global::CStructSharp.WriteOptions? options = null) => SerializeRoot(value, null, options);

        /// <summary>Writes the root declaration (<c>root</c>) into <paramref name="destination"/>.</summary>
        /// <param name="value">The value to write.</param>
        /// <param name="destination">The bytes to write into.</param>
        /// <param name="options">The write options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The number of bytes written.</returns>
        public static int Serialize(Root value, global::System.Span<byte> destination, global::CStructSharp.WriteOptions? options = null) => SerializeRoot(value, destination, null, options);

        /// <summary>Writes the root declaration (<c>root</c>) to <paramref name="stream"/>.</summary>
        /// <param name="stream">The destination stream.</param>
        /// <param name="value">The value to write.</param>
        /// <param name="options">The write options; <see langword="null"/> uses the documented defaults.</param>
        public static void Write(global::System.IO.Stream stream, Root value, global::CStructSharp.WriteOptions? options = null) => WriteRoot(stream, value, null, options);

        /// <summary>Writes one <c>root</c> at the cursor's position.</summary>
        private static void EncodeRoot(ref global::CStructSharp.Generated.WriteCursor cursor, Root? value, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables, string? member, string? memberType)
        {
            if (value is null)
            {
                throw cursor.Fail("Null is not valid for struct or union value: root", member, memberType);
            }
            cursor.EnterComposite(member ?? "root", memberType);
            var placement = global::CStructSharp.Generated.CompositeCursor.Start(cursor.Position, Aligned, Packing, Allocation);
            // uint16 a
            {
                cursor.Seek(placement.AdvanceToField(2), "a", "uint16");
                global::CStructSharp.Generated.Codec.WriteUInt16(cursor.Reserve(2, "a", "uint16"), value.A, false);
                placement.CompleteField(cursor.Position);
            }
            // uint8 b_c : 3
            {
                var slot = placement.AdvanceToBitfield(1, 1, 3, 8, false, "b_c");
                cursor.WriteBits(slot, 3, value.BC, false, HighBitFirst, "b_c", "uint8");
            }
            // uint8 d : 5
            {
                var slot = placement.AdvanceToBitfield(1, 1, 5, 8, false, "d");
                cursor.WriteBits(slot, 5, value.D, false, HighBitFirst, "d", "uint8");
            }
            // uint32 e
            {
                cursor.Seek(placement.AdvanceToField(4), "e", "uint32");
                global::CStructSharp.Generated.Codec.WriteUInt32(cursor.Reserve(4, "e", "uint32"), value.E, false);
                placement.CompleteField(cursor.Position);
            }
            cursor.Seek(placement.Current, member, memberType);
            cursor.Pad((int)(placement.Finish(4) - placement.Current), member, memberType);
            cursor.ExitComposite();
        }

        /// <summary>The root declaration as <see cref="global::CStructSharp.ICStructGenerated{Root}"/>.</summary>
        public sealed partial class Root : global::CStructSharp.ICStructGenerated<Root>
        {
            /// <inheritdoc/>
            static global::CStructSharp.CStruct global::CStructSharp.ICStructGenerated<Root>.Layout => Options.Layout;

            /// <inheritdoc/>
            static string global::CStructSharp.ICStructGenerated<Root>.RootName => Options.RootName;

            /// <inheritdoc/>
            static Root global::CStructSharp.ICStructGenerated<Root>.Parse(global::System.ReadOnlySpan<byte> source, global::CStructSharp.ReadOptions? options) => Options.Parse(source, options);

            /// <inheritdoc/>
            static int global::CStructSharp.ICStructGenerated<Root>.Serialize(Root value, global::System.Span<byte> destination, global::CStructSharp.WriteOptions? options) => Options.Serialize(value, destination, options);
        }

        /// <summary>The runtime's <see cref="global::CStructSharp.Values.StructValue"/> for a generated value: its bytes, parsed by the runtime layout (every member, in the layout's shape). Pointers keep their addresses and are not followed: the value's bytes hold no targets.</summary>
        /// <param name="value">The value to convert.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The read options for the runtime parse (limits, text trimming); <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The struct value.</returns>
        public static global::CStructSharp.Values.StructValue ToStructValue(Root value, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null)
        {
            byte[] bytes = SerializeRoot(value, variables);
            var effective = new global::CStructSharp.ReadOptions
            {
                DereferencePointers = false,
                AddressingMode = options?.AddressingMode ?? global::CStructSharp.PointerAddressingMode.Absolute,
                Origin = options?.Origin ?? 0,
                MaxPointerDepth = options?.MaxPointerDepth ?? 64,
                MaxPointerTargetBytes = options?.MaxPointerTargetBytes,
                MaxArrayElements = options?.MaxArrayElements ?? 1_000_000,
                MaxStringBytes = options?.MaxStringBytes ?? (16L * 1024 * 1024),
                MaxTotalBytesRead = options?.MaxTotalBytesRead ?? (64L * 1024 * 1024),
                MaxNestingDepth = options?.MaxNestingDepth ?? 256,
                TrimFixedText = options?.TrimFixedText ?? false,
            };
            return Layout.Parse(bytes, "root", variables, effective);
        }

        /// <summary>Maps a generated value to a mapped class through the runtime's <see cref="global::CStructSharp.Values.StructValue"/>: <c>ToMapped&lt;MyRoot&gt;(value)</c>.</summary>
        /// <typeparam name="T">A class implementing <see cref="global::CStructSharp.ICStructMapped{TSelf}"/>.</typeparam>
        /// <param name="value">The value to map.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <returns>The mapped instance.</returns>
        public static T ToMapped<T>(Root value, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null)
            where T : global::CStructSharp.ICStructMapped<T>
            => T.ReadFrom(ToStructValue(value, variables));

        /// <summary>Serializes a mapped instance as the root declaration through the runtime layout (its <c>WriteTo</c> supplies the members).</summary>
        /// <typeparam name="T">A class implementing <see cref="global::CStructSharp.ICStructMapped{TSelf}"/>, registered with <see cref="global::CStructSharp.MappedTypes"/>.</typeparam>
        /// <param name="value">The instance to write.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The write options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The serialized bytes.</returns>
        public static byte[] SerializeMapped<T>(T value, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.WriteOptions? options = null)
            where T : global::CStructSharp.ICStructMapped<T>
            => Layout.Serialize("root", value!, variables, options);

        /// <summary>Reads the root declaration straight into a mapped class through the runtime layout.</summary>
        /// <typeparam name="T">A class implementing <see cref="global::CStructSharp.ICStructMapped{TSelf}"/>.</typeparam>
        /// <param name="source">The bytes; offset 0 is coordinate zero.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The read options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The mapped instance.</returns>
        public static T ParseMapped<T>(global::System.ReadOnlySpan<byte> source, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null)
            where T : global::CStructSharp.ICStructMapped<T>
            => T.ReadFrom(Layout.Parse(source, "root", variables, options));

        /// <summary>Reads the root declaration with the generated reader and the runtime's debug ranges (the runtime reads the same bytes once more to produce them).</summary>
        /// <param name="source">The bytes; offset 0 is coordinate zero.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The read options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The parsed value and one <see cref="global::CStructSharp.Diagnostics.DebugData"/> per value read, in read order.</returns>
        public static (Root Value, global::System.Collections.Generic.IReadOnlyList<global::CStructSharp.Diagnostics.DebugData> Debug) ParseWithDebug(global::System.ReadOnlySpan<byte> source, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null)
        {
            Root value = ParseRoot(source, variables, options);
            return (value, Layout.ParseWithDebug(source, "root", variables, options).Debug);
        }

        /// <summary>Resolves a path (<c>root.field</c>, <c>items[2].value</c>, ...) to its byte address with the runtime layout.</summary>
        /// <param name="source">The bytes; offset 0 is coordinate zero.</param>
        /// <param name="path">The path, in the runtime's path grammar.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The read options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The address of the selected value.</returns>
        public static long ResolveAddress(global::System.ReadOnlySpan<byte> source, string path, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null) => Layout.ResolveAddress(source, path, variables, options);

        /// <summary>The element count of an array or string selected by a path, with the runtime layout.</summary>
        /// <param name="source">The bytes; offset 0 is coordinate zero.</param>
        /// <param name="path">The path, in the runtime's path grammar.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The read options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The element count.</returns>
        public static int GetArrayLength(global::System.ReadOnlySpan<byte> source, string path, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null) => Layout.GetArrayLength(source, path, variables, options);

        /// <summary>Replaces one value in place by path with the runtime layout; statically placed members also have typed setters in <see cref="Update"/>.</summary>
        /// <param name="target">The bytes holding the value.</param>
        /// <param name="path">The path, in the runtime's path grammar.</param>
        /// <param name="value">The new value.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The update options; <see langword="null"/> uses the documented defaults.</param>
        public static void UpdatePath(global::System.Span<byte> target, string path, object value, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.UpdateOptions? options = null) => Layout.Update(target, path, value, variables, options);

        /// <summary>The size in bytes of every composite with a static size (<c>sizeof</c>); a runtime-sized composite has none.</summary>
        public static class Sizes
        {
            /// <summary><c>sizeof(root)</c>.</summary>
            public const int Root = 7;
        }

        /// <summary>The offset from the root's first byte of every statically placed scalar (<c>offsetof</c>), nested by struct member.</summary>
        public static class Offsets
        {
            /// <summary><c>offsetof(root, a)</c>.</summary>
            public const int A = 0;

            /// <summary><c>offsetof(root, b_c)</c> (the storage unit's first byte).</summary>
            public const int BC = 2;

            /// <summary><c>offsetof(root, d)</c> (the storage unit's first byte).</summary>
            public const int D = 2;

            /// <summary><c>offsetof(root, e)</c>.</summary>
            public const int E = 3;
        }

        /// <summary>Typed in-place setters for the statically placed scalars, nested by struct member; a fixed array takes the element index.</summary>
        public static class Update
        {
            /// <summary>Stores <c>a</c> into <paramref name="target"/> at offset 0, leaving every other byte alone.</summary>
            /// <param name="target">The bytes holding the value.</param>
            /// <param name="value">The new value.</param>
            public static void A(global::System.Span<byte> target, ushort value)
            {
                var cursor = global::CStructSharp.Generated.WriteCursor.ForUpdate(target, null, "root.a");
                try
                {
                    cursor.Position = 0;
                    global::CStructSharp.Generated.Codec.WriteUInt16(cursor.Reserve(2, "a", "uint16"), value, false);
                }
                catch (global::CStructSharp.Diagnostics.CStructException exception)
                {
                    cursor.Complete(exception);
                    throw;
                }
            }

            /// <summary>Stores <c>b_c</c> into <paramref name="target"/> at offset 2, leaving every other byte alone.</summary>
            /// <param name="target">The bytes holding the value.</param>
            /// <param name="value">The new value.</param>
            public static void BC(global::System.Span<byte> target, byte value)
            {
                var cursor = global::CStructSharp.Generated.WriteCursor.ForUpdate(target, null, "root.b_c");
                try
                {
                    cursor.WriteBits(new global::CStructSharp.Generated.BitfieldSlot(2, 1, 0), 3, value, false, HighBitFirst, "b_c", "uint8");
                }
                catch (global::CStructSharp.Diagnostics.CStructException exception)
                {
                    cursor.Complete(exception);
                    throw;
                }
            }

            /// <summary>Stores <c>d</c> into <paramref name="target"/> at offset 2, leaving every other byte alone.</summary>
            /// <param name="target">The bytes holding the value.</param>
            /// <param name="value">The new value.</param>
            public static void D(global::System.Span<byte> target, byte value)
            {
                var cursor = global::CStructSharp.Generated.WriteCursor.ForUpdate(target, null, "root.d");
                try
                {
                    cursor.WriteBits(new global::CStructSharp.Generated.BitfieldSlot(2, 1, 3), 5, value, false, HighBitFirst, "d", "uint8");
                }
                catch (global::CStructSharp.Diagnostics.CStructException exception)
                {
                    cursor.Complete(exception);
                    throw;
                }
            }

            /// <summary>Stores <c>e</c> into <paramref name="target"/> at offset 3, leaving every other byte alone.</summary>
            /// <param name="target">The bytes holding the value.</param>
            /// <param name="value">The new value.</param>
            public static void E(global::System.Span<byte> target, uint value)
            {
                var cursor = global::CStructSharp.Generated.WriteCursor.ForUpdate(target, null, "root.e");
                try
                {
                    cursor.Position = 3;
                    global::CStructSharp.Generated.Codec.WriteUInt32(cursor.Reserve(4, "e", "uint32"), value, false);
                }
                catch (global::CStructSharp.Diagnostics.CStructException exception)
                {
                    cursor.Complete(exception);
                    throw;
                }
            }
        }

        /// <summary>
        ///     A zero-allocation view of one <c>root</c> over its bytes: each statically placed member decodes
        ///     directly from the span when read; a member the view does not expose (runtime-sized, conditional, or placed after one)
        ///     is reached through <see cref="ToObject"/>. A view cannot leave the method that created it.
        /// </summary>
        public readonly ref struct RootView
        {
            private readonly global::System.ReadOnlySpan<byte> source;
            private readonly global::CStructSharp.ReadOptions? options;

            /// <summary>Creates a view over <paramref name="source"/>, whose first byte is the value's first byte; the source must hold the value's 7 bytes.</summary>
            /// <param name="source">The bytes, from the value's start; more may follow (pointer targets, the rest of the input).</param>
            /// <param name="options">The read options <see cref="ToObject"/> uses; <see langword="null"/> uses the documented defaults.</param>
            public RootView(global::System.ReadOnlySpan<byte> source, global::CStructSharp.ReadOptions? options = null)
            {
                if (source.Length < 7)
                {
                    var cursor = new global::CStructSharp.Generated.ReadCursor(source, options, "root");
                    global::CStructSharp.Diagnostics.CStructException failure = cursor.Fail(global::CStructSharp.Generated.ReadCursor.ShortReadText(7, source.Length), null, null);
                    cursor.Complete(failure);
                    throw failure;
                }
                this.source = source;
                this.options = options;
            }

            /// <summary>Gets the value's bytes (its 7 bytes).</summary>
            public global::System.ReadOnlySpan<byte> Bytes => this.source.Slice(0, 7);

            /// <summary><c>uint16 a</c> at offset 0.</summary>
            public ushort A => global::CStructSharp.Generated.Codec.ReadUInt16(this.source.Slice(0, 2), false);

            /// <summary><c>uint8 b_c : 3</c> at offset 2.</summary>
            public byte BC => (byte)global::CStructSharp.Generated.Codec.ExtractBits(global::CStructSharp.Generated.Codec.ReadUnsigned(this.source.Slice(2, 1), false), global::CStructSharp.Generated.Codec.BitfieldShift(0, 3, 8, HighBitFirst), 3);

            /// <summary><c>uint8 d : 5</c> at offset 2.</summary>
            public byte D => (byte)global::CStructSharp.Generated.Codec.ExtractBits(global::CStructSharp.Generated.Codec.ReadUnsigned(this.source.Slice(2, 1), false), global::CStructSharp.Generated.Codec.BitfieldShift(3, 5, 8, HighBitFirst), 5);

            /// <summary><c>uint32 e</c> at offset 3.</summary>
            public uint E => global::CStructSharp.Generated.Codec.ReadUInt32(this.source.Slice(3, 4), false);

            /// <summary>Reads the whole value with the generated reader (every member, runtime-sized ones included).</summary>
            /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
            /// <returns>The value.</returns>
            public Root ToObject(global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null)
            {
                var cursor = new global::CStructSharp.Generated.ReadCursor(this.source, this.options, "root");
                try
                {
                    return ReadRoot(ref cursor, variables, null, null);
                }
                catch (global::CStructSharp.Diagnostics.CStructException exception)
                {
                    cursor.Complete(exception);
                    throw;
                }
            }
        }
    }
}
