// <auto-generated/>
// Generated by CStructSharp from the [CStructLayout] attribute on Png. Do not edit.
#nullable enable
#pragma warning disable

namespace Demo
{
    [global::System.CodeDom.Compiler.GeneratedCode("CStructSharp", "<version>")]
    internal static partial class Png
    {
        /// <summary>The layout text the members of this class were generated from.</summary>
        public const string Definition = "struct chunk { uint32 length; };\n#ifdef WITH_TAIL\nstruct root { chunk first; uint8 tail; };\n#else\nstruct root { chunk first; };\n#endif\n";

        /// <summary>The declaration the plain <see cref="Parse"/> and <see cref="Serialize"/> methods operate on.</summary>
        public const string RootName = "root";

        private static readonly global::System.Lazy<global::CStructSharp.CStruct> LayoutInstance = new(CreateLayout, global::System.Threading.LazyThreadSafetyMode.ExecutionAndPublication);

        /// <summary>The runtime <see cref="global::CStructSharp.CStruct"/> for the same definition and options, built on first use: introspection, JSON, memory images, and the parity oracle.</summary>
        public static global::CStructSharp.CStruct Layout => LayoutInstance.Value;

        private static global::CStructSharp.CStruct CreateLayout()
        {
            var options = new global::CStructSharp.CStructCompilationOptions
            {
                CLongWidth = 32,
                BitfieldPacking = global::CStructSharp.BitfieldPacking.Msvc,
                BitfieldAllocation = global::CStructSharp.BitfieldAllocation.HighBitFirst,
                Defined = new global::System.Collections.Generic.HashSet<string>(global::System.StringComparer.Ordinal) { "WITH_TAIL", },
            };
            return new global::CStructSharp.CStruct(Definition, pointerSize: 8, aligned: false, isLittleEndian: true, compilationOptions: options);
        }

        /// <summary>The layout struct <c>chunk</c>.</summary>
        public sealed partial class chunk
        {
            /// <summary><c>uint32 length</c>.</summary>
            public uint length { get; set; }
        }

        /// <summary>The layout struct <c>root</c>.</summary>
        public sealed partial class root
        {
            /// <summary><c>chunk first</c>.</summary>
            public chunk first { get; set; } = new();

            /// <summary><c>uint8 tail</c>.</summary>
            public byte tail { get; set; }
        }

        private const bool Aligned = false;
        private const bool LittleEndian = true;
        private const int PointerSize = 8;
        private const bool HighBitFirst = true;
        private const global::CStructSharp.BitfieldPacking Packing = global::CStructSharp.BitfieldPacking.Msvc;
        private const global::CStructSharp.BitfieldAllocation Allocation = global::CStructSharp.BitfieldAllocation.HighBitFirst;

        /// <summary>Reads one <c>chunk</c> from the start of <paramref name="source"/> with the generated reader; the same value, and the same failures, as the runtime's <c>Parse</c>.</summary>
        /// <param name="source">The bytes; offset 0 is coordinate zero.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The read options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The parsed value.</returns>
        public static chunk Parsechunk(global::System.ReadOnlySpan<byte> source, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null)
        {
            var cursor = new global::CStructSharp.Generated.ReadCursor(source, options, "chunk");
            try
            {
                return Readchunk(ref cursor, variables, null, null);
            }
            catch (global::CStructSharp.Diagnostics.CStructException exception)
            {
                cursor.Complete(exception);
                throw;
            }
        }

        /// <inheritdoc cref="Parsechunk(global::System.ReadOnlySpan{byte}, global::System.Collections.Generic.IReadOnlyDictionary{string, int}, global::CStructSharp.ReadOptions)"/>
        public static chunk Parsechunk(byte[] source, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null)
            => Parsechunk(new global::System.ReadOnlySpan<byte>(source ?? throw new global::System.ArgumentNullException(nameof(source))), variables, options);

        /// <inheritdoc cref="Parsechunk(global::System.ReadOnlySpan{byte}, global::System.Collections.Generic.IReadOnlyDictionary{string, int}, global::CStructSharp.ReadOptions)"/>
        public static chunk Parsechunk(global::System.ReadOnlyMemory<byte> source, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null)
            => Parsechunk(source.Span, variables, options);

        /// <summary>Reads one <c>root</c> from the start of <paramref name="source"/> with the generated reader; the same value, and the same failures, as the runtime's <c>Parse</c>.</summary>
        /// <param name="source">The bytes; offset 0 is coordinate zero.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The read options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The parsed value.</returns>
        public static root Parseroot(global::System.ReadOnlySpan<byte> source, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null)
        {
            var cursor = new global::CStructSharp.Generated.ReadCursor(source, options, "root");
            try
            {
                return Readroot(ref cursor, variables, null, null);
            }
            catch (global::CStructSharp.Diagnostics.CStructException exception)
            {
                cursor.Complete(exception);
                throw;
            }
        }

        /// <inheritdoc cref="Parseroot(global::System.ReadOnlySpan{byte}, global::System.Collections.Generic.IReadOnlyDictionary{string, int}, global::CStructSharp.ReadOptions)"/>
        public static root Parseroot(byte[] source, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null)
            => Parseroot(new global::System.ReadOnlySpan<byte>(source ?? throw new global::System.ArgumentNullException(nameof(source))), variables, options);

        /// <inheritdoc cref="Parseroot(global::System.ReadOnlySpan{byte}, global::System.Collections.Generic.IReadOnlyDictionary{string, int}, global::CStructSharp.ReadOptions)"/>
        public static root Parseroot(global::System.ReadOnlyMemory<byte> source, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null)
            => Parseroot(source.Span, variables, options);

        /// <summary>Reads the root declaration (<c>root</c>); see <see cref="Parseroot(global::System.ReadOnlySpan{byte}, global::System.Collections.Generic.IReadOnlyDictionary{string, int}, global::CStructSharp.ReadOptions)"/>.</summary>
        /// <param name="source">The bytes; offset 0 is coordinate zero.</param>
        /// <param name="options">The read options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The parsed value.</returns>
        public static root Parse(global::System.ReadOnlySpan<byte> source, global::CStructSharp.ReadOptions? options = null) => Parseroot(source, null, options);

        /// <inheritdoc cref="Parse(global::System.ReadOnlySpan{byte}, global::CStructSharp.ReadOptions)"/>
        public static root Parse(byte[] source, global::CStructSharp.ReadOptions? options = null) => Parseroot(source, null, options);

        /// <inheritdoc cref="Parse(global::System.ReadOnlySpan{byte}, global::CStructSharp.ReadOptions)"/>
        public static root Parse(global::System.ReadOnlyMemory<byte> source, global::CStructSharp.ReadOptions? options = null) => Parseroot(source.Span, null, options);

        /// <summary>Reads one <c>chunk</c> at the cursor's position.</summary>
        private static chunk Readchunk(ref global::CStructSharp.Generated.ReadCursor cursor, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables, string? member, string? memberType)
        {
            cursor.EnterComposite(member ?? "chunk", memberType);
            var value = new chunk();
            var placement = global::CStructSharp.Generated.CompositeCursor.Start(cursor.Position, Aligned, Packing, Allocation);
            // uint32 length
            {
                cursor.Seek(placement.AdvanceToField(4), "length", "uint32");
                value.length = global::CStructSharp.Generated.Codec.ReadUInt32(cursor.Take(4, "length", "uint32"), true);
                placement.CompleteField(cursor.Position);
            }
            cursor.Seek(placement.Finish(4), member, memberType);
            cursor.ExitComposite();
            return value;
        }

        /// <summary>Reads one <c>root</c> at the cursor's position.</summary>
        private static root Readroot(ref global::CStructSharp.Generated.ReadCursor cursor, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables, string? member, string? memberType)
        {
            cursor.EnterComposite(member ?? "root", memberType);
            var value = new root();
            var placement = global::CStructSharp.Generated.CompositeCursor.Start(cursor.Position, Aligned, Packing, Allocation);
            // chunk first
            {
                cursor.Seek(placement.AdvanceToField(4), "first", "chunk");
                value.first = Readchunk(ref cursor, variables, "first", "chunk");
                placement.CompleteField(cursor.Position);
            }
            // uint8 tail
            {
                cursor.Seek(placement.AdvanceToField(1), "tail", "uint8");
                value.tail = cursor.Take(1, "tail", "uint8")[0];
                placement.CompleteField(cursor.Position);
            }
            cursor.Seek(placement.Finish(4), member, memberType);
            cursor.ExitComposite();
            return value;
        }

        /// <summary>Groups a flat element array into rows of <paramref name="inner"/> elements (one nesting level of a multidimensional array).</summary>
        private static T[][] Split<T>(T[] flat, int inner)
        {
            var rows = new T[inner == 0 ? 0 : flat.Length / inner][];
            for (int row = 0; row < rows.Length; row++)
            {
                rows[row] = new T[inner];
                global::System.Array.Copy(flat, row * inner, rows[row], 0, inner);
            }
            return rows;
        }
    }
}
