// <auto-generated/>
// Generated by CStructSharp from the [CStructLayout] attribute on Png. Do not edit.
#nullable enable
#pragma warning disable

namespace Demo
{
    [global::System.CodeDom.Compiler.GeneratedCode("CStructSharp", "<version>")]
    internal static partial class Png
    {
        /// <summary>The layout text the members of this class were generated from.</summary>
        public const string Definition = "struct chunk { uint32 length; };\n#ifdef WITH_TAIL\nstruct root { chunk first; uint8 tail; };\n#else\nstruct root { chunk first; };\n#endif\n";

        /// <summary>The declaration the plain <see cref="Parse"/> and <see cref="Serialize"/> methods operate on.</summary>
        public const string RootName = "root";

        private static readonly global::System.Lazy<global::CStructSharp.CStruct> LayoutInstance = new(CreateLayout, global::System.Threading.LazyThreadSafetyMode.ExecutionAndPublication);

        /// <summary>The runtime <see cref="global::CStructSharp.CStruct"/> for the same definition and options, built on first use: introspection, JSON, memory images, and the parity oracle.</summary>
        public static global::CStructSharp.CStruct Layout => LayoutInstance.Value;

        private static global::CStructSharp.CStruct CreateLayout()
        {
            var options = new global::CStructSharp.CStructCompilationOptions
            {
                CLongWidth = 32,
                BitfieldPacking = global::CStructSharp.BitfieldPacking.Msvc,
                BitfieldAllocation = global::CStructSharp.BitfieldAllocation.HighBitFirst,
                Defined = new global::System.Collections.Generic.HashSet<string>(global::System.StringComparer.Ordinal) { "WITH_TAIL", },
            };
            return new global::CStructSharp.CStruct(Definition, pointerSize: 8, aligned: false, isLittleEndian: true, compilationOptions: options);
        }

        /// <summary>The layout struct <c>chunk</c>.</summary>
        public sealed partial class chunk
        {
            /// <summary><c>uint32 length</c>.</summary>
            public uint length { get; set; }
        }

        /// <summary>The layout struct <c>root</c>.</summary>
        public sealed partial class root
        {
            /// <summary><c>chunk first</c>.</summary>
            public chunk first { get; set; } = new();

            /// <summary><c>uint8 tail</c>.</summary>
            public byte tail { get; set; }
        }
    }
}
