// <auto-generated/>
// Generated by CStructSharp from the [CStructLayout] attribute on Png. Do not edit.
#nullable enable
#pragma warning disable

namespace Demo
{
    [global::System.CodeDom.Compiler.GeneratedCode("CStructSharp", "<version>")]
    internal static partial class Png
    {
        /// <summary>The layout text the members of this class were generated from.</summary>
        public const string Definition = "struct chunk { uint32 length; };\n#ifdef WITH_TAIL\nstruct root { chunk first; uint8 tail; };\n#else\nstruct root { chunk first; };\n#endif\n";

        /// <summary>The declaration the plain <see cref="Parse"/> and <see cref="Serialize"/> methods operate on.</summary>
        public const string RootName = "root";

        private static readonly global::System.Lazy<global::CStructSharp.CStruct> LayoutInstance = new(CreateLayout, global::System.Threading.LazyThreadSafetyMode.ExecutionAndPublication);

        /// <summary>The runtime <see cref="global::CStructSharp.CStruct"/> for the same definition and options, built on first use: introspection, JSON, memory images, and the parity oracle.</summary>
        public static global::CStructSharp.CStruct Layout => LayoutInstance.Value;

        private static global::CStructSharp.CStruct CreateLayout()
        {
            var options = new global::CStructSharp.CStructCompilationOptions
            {
                CLongWidth = 32,
                BitfieldPacking = global::CStructSharp.BitfieldPacking.Msvc,
                BitfieldAllocation = global::CStructSharp.BitfieldAllocation.HighBitFirst,
                Defined = new global::System.Collections.Generic.HashSet<string>(global::System.StringComparer.Ordinal) { "WITH_TAIL", },
            };
            return new global::CStructSharp.CStruct(Definition, pointerSize: 8, aligned: false, isLittleEndian: true, compilationOptions: options);
        }

        /// <summary>The layout struct <c>chunk</c>.</summary>
        public sealed partial class chunk
        {
            /// <summary><c>uint32 length</c>.</summary>
            public uint length { get; set; }
        }

        /// <summary>The layout struct <c>root</c>.</summary>
        public sealed partial class root
        {
            /// <summary><c>chunk first</c>.</summary>
            public chunk first { get; set; } = new();

            /// <summary><c>uint8 tail</c>.</summary>
            public byte tail { get; set; }
        }

        private const bool Aligned = false;
        private const bool LittleEndian = true;
        private const int PointerSize = 8;
        private const bool HighBitFirst = true;
        private const global::CStructSharp.BitfieldPacking Packing = global::CStructSharp.BitfieldPacking.Msvc;
        private const global::CStructSharp.BitfieldAllocation Allocation = global::CStructSharp.BitfieldAllocation.HighBitFirst;

        /// <summary>Reads one <c>chunk</c> from the start of <paramref name="source"/> with the generated reader; the same value, and the same failures, as the runtime's <c>Parse</c>.</summary>
        /// <param name="source">The bytes; offset 0 is coordinate zero.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The read options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The parsed value.</returns>
        public static chunk Parsechunk(global::System.ReadOnlySpan<byte> source, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null)
        {
            var cursor = new global::CStructSharp.Generated.ReadCursor(source, options, "chunk");
            try
            {
                return Readchunk(ref cursor, variables, null, null);
            }
            catch (global::CStructSharp.Diagnostics.CStructException exception)
            {
                cursor.Complete(exception);
                throw;
            }
        }

        /// <inheritdoc cref="Parsechunk(global::System.ReadOnlySpan{byte}, global::System.Collections.Generic.IReadOnlyDictionary{string, int}, global::CStructSharp.ReadOptions)"/>
        public static chunk Parsechunk(byte[] source, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null)
            => Parsechunk(new global::System.ReadOnlySpan<byte>(source ?? throw new global::System.ArgumentNullException(nameof(source))), variables, options);

        /// <inheritdoc cref="Parsechunk(global::System.ReadOnlySpan{byte}, global::System.Collections.Generic.IReadOnlyDictionary{string, int}, global::CStructSharp.ReadOptions)"/>
        public static chunk Parsechunk(global::System.ReadOnlyMemory<byte> source, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null)
            => Parsechunk(source.Span, variables, options);

        /// <summary>Reads one <c>chunk</c> from a sequence of segments: a single segment is read in place, several are copied into a pooled buffer bounded by the total read budget.</summary>
        /// <param name="source">The bytes; offset 0 is coordinate zero.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The read options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The parsed value.</returns>
        public static chunk Parsechunk(global::System.Buffers.ReadOnlySequence<byte> source, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null)
        {
            if (source.IsSingleSegment)
            {
                return Parsechunk(source.FirstSpan, variables, options);
            }
            byte[] buffer = global::CStructSharp.Generated.ReadCursor.CopySequence(source, options, out int length);
            try
            {
                return Parsechunk(new global::System.ReadOnlySpan<byte>(buffer, 0, length), variables, options);
            }
            finally
            {
                global::System.Buffers.ArrayPool<byte>.Shared.Return(buffer);
            }
        }

        /// <summary>Reads one <c>chunk</c> from <paramref name="stream"/>: the stream is buffered up to the total read budget (or its remaining length) and read through the span reader; a seekable stream is left after the value.</summary>
        /// <param name="stream">The stream, read from its current position.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The read options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The parsed value.</returns>
        public static chunk Parsechunk(global::System.IO.Stream stream, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null)
        {
            global::System.ArgumentNullException.ThrowIfNull(stream);
            long start = stream.CanSeek ? stream.Position : 0;
            byte[] buffer = global::CStructSharp.Generated.ReadCursor.BufferStream(stream, options, out int length);
            try
            {
                var cursor = new global::CStructSharp.Generated.ReadCursor(new global::System.ReadOnlySpan<byte>(buffer, 0, length), options, "chunk");
                try
                {
                    chunk value = Readchunk(ref cursor, variables, null, null);
                    if (stream.CanSeek)
                    {
                        stream.Position = start + cursor.Position;
                    }
                    return value;
                }
                catch (global::CStructSharp.Diagnostics.CStructException exception)
                {
                    cursor.Complete(exception);
                    throw;
                }
            }
            finally
            {
                global::System.Buffers.ArrayPool<byte>.Shared.Return(buffer);
            }
        }

        /// <summary>Reads one <c>root</c> from the start of <paramref name="source"/> with the generated reader; the same value, and the same failures, as the runtime's <c>Parse</c>.</summary>
        /// <param name="source">The bytes; offset 0 is coordinate zero.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The read options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The parsed value.</returns>
        public static root Parseroot(global::System.ReadOnlySpan<byte> source, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null)
        {
            var cursor = new global::CStructSharp.Generated.ReadCursor(source, options, "root");
            try
            {
                return Readroot(ref cursor, variables, null, null);
            }
            catch (global::CStructSharp.Diagnostics.CStructException exception)
            {
                cursor.Complete(exception);
                throw;
            }
        }

        /// <inheritdoc cref="Parseroot(global::System.ReadOnlySpan{byte}, global::System.Collections.Generic.IReadOnlyDictionary{string, int}, global::CStructSharp.ReadOptions)"/>
        public static root Parseroot(byte[] source, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null)
            => Parseroot(new global::System.ReadOnlySpan<byte>(source ?? throw new global::System.ArgumentNullException(nameof(source))), variables, options);

        /// <inheritdoc cref="Parseroot(global::System.ReadOnlySpan{byte}, global::System.Collections.Generic.IReadOnlyDictionary{string, int}, global::CStructSharp.ReadOptions)"/>
        public static root Parseroot(global::System.ReadOnlyMemory<byte> source, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null)
            => Parseroot(source.Span, variables, options);

        /// <summary>Reads one <c>root</c> from a sequence of segments: a single segment is read in place, several are copied into a pooled buffer bounded by the total read budget.</summary>
        /// <param name="source">The bytes; offset 0 is coordinate zero.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The read options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The parsed value.</returns>
        public static root Parseroot(global::System.Buffers.ReadOnlySequence<byte> source, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null)
        {
            if (source.IsSingleSegment)
            {
                return Parseroot(source.FirstSpan, variables, options);
            }
            byte[] buffer = global::CStructSharp.Generated.ReadCursor.CopySequence(source, options, out int length);
            try
            {
                return Parseroot(new global::System.ReadOnlySpan<byte>(buffer, 0, length), variables, options);
            }
            finally
            {
                global::System.Buffers.ArrayPool<byte>.Shared.Return(buffer);
            }
        }

        /// <summary>Reads one <c>root</c> from <paramref name="stream"/>: the stream is buffered up to the total read budget (or its remaining length) and read through the span reader; a seekable stream is left after the value.</summary>
        /// <param name="stream">The stream, read from its current position.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The read options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The parsed value.</returns>
        public static root Parseroot(global::System.IO.Stream stream, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null)
        {
            global::System.ArgumentNullException.ThrowIfNull(stream);
            long start = stream.CanSeek ? stream.Position : 0;
            byte[] buffer = global::CStructSharp.Generated.ReadCursor.BufferStream(stream, options, out int length);
            try
            {
                var cursor = new global::CStructSharp.Generated.ReadCursor(new global::System.ReadOnlySpan<byte>(buffer, 0, length), options, "root");
                try
                {
                    root value = Readroot(ref cursor, variables, null, null);
                    if (stream.CanSeek)
                    {
                        stream.Position = start + cursor.Position;
                    }
                    return value;
                }
                catch (global::CStructSharp.Diagnostics.CStructException exception)
                {
                    cursor.Complete(exception);
                    throw;
                }
            }
            finally
            {
                global::System.Buffers.ArrayPool<byte>.Shared.Return(buffer);
            }
        }

        /// <summary>Reads the root declaration (<c>root</c>); see <see cref="Parseroot(global::System.ReadOnlySpan{byte}, global::System.Collections.Generic.IReadOnlyDictionary{string, int}, global::CStructSharp.ReadOptions)"/>.</summary>
        /// <param name="source">The bytes; offset 0 is coordinate zero.</param>
        /// <param name="options">The read options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The parsed value.</returns>
        public static root Parse(global::System.ReadOnlySpan<byte> source, global::CStructSharp.ReadOptions? options = null) => Parseroot(source, null, options);

        /// <inheritdoc cref="Parse(global::System.ReadOnlySpan{byte}, global::CStructSharp.ReadOptions)"/>
        public static root Parse(byte[] source, global::CStructSharp.ReadOptions? options = null) => Parseroot(source, null, options);

        /// <inheritdoc cref="Parse(global::System.ReadOnlySpan{byte}, global::CStructSharp.ReadOptions)"/>
        public static root Parse(global::System.ReadOnlyMemory<byte> source, global::CStructSharp.ReadOptions? options = null) => Parseroot(source.Span, null, options);

        /// <inheritdoc cref="Parseroot(global::System.Buffers.ReadOnlySequence{byte}, global::System.Collections.Generic.IReadOnlyDictionary{string, int}, global::CStructSharp.ReadOptions)"/>
        public static root Parse(global::System.Buffers.ReadOnlySequence<byte> source, global::CStructSharp.ReadOptions? options = null) => Parseroot(source, null, options);

        /// <inheritdoc cref="Parseroot(global::System.IO.Stream, global::System.Collections.Generic.IReadOnlyDictionary{string, int}, global::CStructSharp.ReadOptions)"/>
        public static root Parse(global::System.IO.Stream stream, global::CStructSharp.ReadOptions? options = null) => Parseroot(stream, null, options);

        /// <summary>Reads one <c>chunk</c> at the cursor's position.</summary>
        private static chunk Readchunk(ref global::CStructSharp.Generated.ReadCursor cursor, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables, string? member, string? memberType)
        {
            cursor.EnterComposite(member ?? "chunk", memberType);
            var value = new chunk();
            var placement = global::CStructSharp.Generated.CompositeCursor.Start(cursor.Position, Aligned, Packing, Allocation);
            // uint32 length
            {
                cursor.Seek(placement.AdvanceToField(4), "length", "uint32");
                value.length = global::CStructSharp.Generated.Codec.ReadUInt32(cursor.Take(4, "length", "uint32"), true);
                placement.CompleteField(cursor.Position);
            }
            cursor.Seek(placement.Finish(4), member, memberType);
            cursor.ExitComposite();
            return value;
        }

        /// <summary>Reads one <c>root</c> at the cursor's position.</summary>
        private static root Readroot(ref global::CStructSharp.Generated.ReadCursor cursor, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables, string? member, string? memberType)
        {
            cursor.EnterComposite(member ?? "root", memberType);
            var value = new root();
            var placement = global::CStructSharp.Generated.CompositeCursor.Start(cursor.Position, Aligned, Packing, Allocation);
            // chunk first
            {
                cursor.Seek(placement.AdvanceToField(4), "first", "chunk");
                value.first = Readchunk(ref cursor, variables, "first", "chunk");
                placement.CompleteField(cursor.Position);
            }
            // uint8 tail
            {
                cursor.Seek(placement.AdvanceToField(1), "tail", "uint8");
                value.tail = cursor.Take(1, "tail", "uint8")[0];
                placement.CompleteField(cursor.Position);
            }
            cursor.Seek(placement.Finish(4), member, memberType);
            cursor.ExitComposite();
            return value;
        }

        /// <summary>Groups a flat element array into rows of <paramref name="inner"/> elements (one nesting level of a multidimensional array).</summary>
        private static T[][] Split<T>(T[] flat, int inner)
        {
            var rows = new T[inner == 0 ? 0 : flat.Length / inner][];
            for (int row = 0; row < rows.Length; row++)
            {
                rows[row] = new T[inner];
                global::System.Array.Copy(flat, row * inner, rows[row], 0, inner);
            }
            return rows;
        }

        /// <summary>Writes one <c>chunk</c> into a new array with the generated writer; the same bytes, and the same failures, as the runtime's <c>Serialize</c>.</summary>
        /// <param name="value">The value to write.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The write options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The serialized bytes.</returns>
        public static byte[] Serializechunk(chunk value, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.WriteOptions? options = null)
        {
            var cursor = new global::CStructSharp.Generated.WriteCursor(options, "chunk");
            try
            {
                Encodechunk(ref cursor, value, variables, null, null);
                return cursor.ToArray();
            }
            catch (global::CStructSharp.Diagnostics.CStructException exception)
            {
                cursor.Complete(exception);
                throw;
            }
            finally
            {
                cursor.Dispose();
            }
        }

        /// <summary>Writes one <c>chunk</c> into <paramref name="destination"/>; a value that does not fit fails with the runtime's capacity message.</summary>
        /// <param name="value">The value to write.</param>
        /// <param name="destination">The bytes to write into.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The write options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The number of bytes written.</returns>
        public static int Serializechunk(chunk value, global::System.Span<byte> destination, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.WriteOptions? options = null)
        {
            var cursor = new global::CStructSharp.Generated.WriteCursor(destination, options, "chunk");
            try
            {
                Encodechunk(ref cursor, value, variables, null, null);
                return cursor.Length;
            }
            catch (global::CStructSharp.Diagnostics.CStructException exception)
            {
                cursor.Complete(exception);
                throw;
            }
        }

        /// <summary>Writes one <c>chunk</c> to <paramref name="stream"/> at its current position.</summary>
        /// <param name="stream">The destination stream.</param>
        /// <param name="value">The value to write.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The write options; <see langword="null"/> uses the documented defaults.</param>
        public static void Writechunk(global::System.IO.Stream stream, chunk value, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.WriteOptions? options = null)
        {
            global::System.ArgumentNullException.ThrowIfNull(stream);
            if (!stream.CanWrite)
            {
                throw new global::System.ArgumentException("Writing requires a writable stream.", nameof(stream));
            }
            byte[] bytes = Serializechunk(value, variables, options);
            stream.Write(bytes, 0, bytes.Length);
        }

        /// <summary>Writes one <c>root</c> into a new array with the generated writer; the same bytes, and the same failures, as the runtime's <c>Serialize</c>.</summary>
        /// <param name="value">The value to write.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The write options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The serialized bytes.</returns>
        public static byte[] Serializeroot(root value, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.WriteOptions? options = null)
        {
            var cursor = new global::CStructSharp.Generated.WriteCursor(options, "root");
            try
            {
                Encoderoot(ref cursor, value, variables, null, null);
                return cursor.ToArray();
            }
            catch (global::CStructSharp.Diagnostics.CStructException exception)
            {
                cursor.Complete(exception);
                throw;
            }
            finally
            {
                cursor.Dispose();
            }
        }

        /// <summary>Writes one <c>root</c> into <paramref name="destination"/>; a value that does not fit fails with the runtime's capacity message.</summary>
        /// <param name="value">The value to write.</param>
        /// <param name="destination">The bytes to write into.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The write options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The number of bytes written.</returns>
        public static int Serializeroot(root value, global::System.Span<byte> destination, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.WriteOptions? options = null)
        {
            var cursor = new global::CStructSharp.Generated.WriteCursor(destination, options, "root");
            try
            {
                Encoderoot(ref cursor, value, variables, null, null);
                return cursor.Length;
            }
            catch (global::CStructSharp.Diagnostics.CStructException exception)
            {
                cursor.Complete(exception);
                throw;
            }
        }

        /// <summary>Writes one <c>root</c> to <paramref name="stream"/> at its current position.</summary>
        /// <param name="stream">The destination stream.</param>
        /// <param name="value">The value to write.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The write options; <see langword="null"/> uses the documented defaults.</param>
        public static void Writeroot(global::System.IO.Stream stream, root value, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.WriteOptions? options = null)
        {
            global::System.ArgumentNullException.ThrowIfNull(stream);
            if (!stream.CanWrite)
            {
                throw new global::System.ArgumentException("Writing requires a writable stream.", nameof(stream));
            }
            byte[] bytes = Serializeroot(value, variables, options);
            stream.Write(bytes, 0, bytes.Length);
        }

        /// <summary>Writes the root declaration (<c>root</c>) into a new array; see <see cref="Serializeroot(root, global::System.Collections.Generic.IReadOnlyDictionary{string, int}, global::CStructSharp.WriteOptions)"/>.</summary>
        /// <param name="value">The value to write.</param>
        /// <param name="options">The write options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The serialized bytes.</returns>
        public static byte[] Serialize(root value, global::CStructSharp.WriteOptions? options = null) => Serializeroot(value, null, options);

        /// <summary>Writes the root declaration (<c>root</c>) into <paramref name="destination"/>.</summary>
        /// <param name="value">The value to write.</param>
        /// <param name="destination">The bytes to write into.</param>
        /// <param name="options">The write options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The number of bytes written.</returns>
        public static int Serialize(root value, global::System.Span<byte> destination, global::CStructSharp.WriteOptions? options = null) => Serializeroot(value, destination, null, options);

        /// <summary>Writes the root declaration (<c>root</c>) to <paramref name="stream"/>.</summary>
        /// <param name="stream">The destination stream.</param>
        /// <param name="value">The value to write.</param>
        /// <param name="options">The write options; <see langword="null"/> uses the documented defaults.</param>
        public static void Write(global::System.IO.Stream stream, root value, global::CStructSharp.WriteOptions? options = null) => Writeroot(stream, value, null, options);

        /// <summary>Writes one <c>chunk</c> at the cursor's position.</summary>
        private static void Encodechunk(ref global::CStructSharp.Generated.WriteCursor cursor, chunk? value, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables, string? member, string? memberType)
        {
            if (value is null)
            {
                throw cursor.Fail("Null is not valid for struct or union value: chunk", member, memberType);
            }
            cursor.EnterComposite(member ?? "chunk", memberType);
            var placement = global::CStructSharp.Generated.CompositeCursor.Start(cursor.Position, Aligned, Packing, Allocation);
            // uint32 length
            {
                cursor.Seek(placement.AdvanceToField(4), "length", "uint32");
                global::CStructSharp.Generated.Codec.WriteUInt32(cursor.Reserve(4, "length", "uint32"), value.length, true);
                placement.CompleteField(cursor.Position);
            }
            cursor.Seek(placement.Current, member, memberType);
            cursor.Pad((int)(placement.Finish(4) - placement.Current), member, memberType);
            cursor.ExitComposite();
        }

        /// <summary>Writes one <c>root</c> at the cursor's position.</summary>
        private static void Encoderoot(ref global::CStructSharp.Generated.WriteCursor cursor, root? value, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables, string? member, string? memberType)
        {
            if (value is null)
            {
                throw cursor.Fail("Null is not valid for struct or union value: root", member, memberType);
            }
            cursor.EnterComposite(member ?? "root", memberType);
            var placement = global::CStructSharp.Generated.CompositeCursor.Start(cursor.Position, Aligned, Packing, Allocation);
            // chunk first
            {
                cursor.Seek(placement.AdvanceToField(4), "first", "chunk");
                if (value.first is null)
                {
                    throw cursor.Fail("Null is valid only for a scalar pointer field: first", "first", "chunk");
                }
                Encodechunk(ref cursor, value.first, variables, "first", "chunk");
                placement.CompleteField(cursor.Position);
            }
            // uint8 tail
            {
                cursor.Seek(placement.AdvanceToField(1), "tail", "uint8");
                cursor.Reserve(1, "tail", "uint8")[0] = value.tail;
                placement.CompleteField(cursor.Position);
            }
            cursor.Seek(placement.Current, member, memberType);
            cursor.Pad((int)(placement.Finish(4) - placement.Current), member, memberType);
            cursor.ExitComposite();
        }

        /// <summary>The root declaration as <see cref="global::CStructSharp.ICStructGenerated{root}"/>.</summary>
        public sealed partial class root : global::CStructSharp.ICStructGenerated<root>
        {
            /// <inheritdoc/>
            static global::CStructSharp.CStruct global::CStructSharp.ICStructGenerated<root>.Layout => Png.Layout;

            /// <inheritdoc/>
            static string global::CStructSharp.ICStructGenerated<root>.RootName => Png.RootName;

            /// <inheritdoc/>
            static root global::CStructSharp.ICStructGenerated<root>.Parse(global::System.ReadOnlySpan<byte> source, global::CStructSharp.ReadOptions? options) => Png.Parse(source, options);

            /// <inheritdoc/>
            static int global::CStructSharp.ICStructGenerated<root>.Serialize(root value, global::System.Span<byte> destination, global::CStructSharp.WriteOptions? options) => Png.Serialize(value, destination, options);
        }

        /// <summary>The runtime's <see cref="global::CStructSharp.Values.StructValue"/> for a generated value: its bytes, parsed by the runtime layout (every member, in the layout's shape). Pointers keep their addresses and are not followed: the value's bytes hold no targets.</summary>
        /// <param name="value">The value to convert.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The read options for the runtime parse (limits, text trimming); <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The struct value.</returns>
        public static global::CStructSharp.Values.StructValue ToStructValue(root value, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null)
        {
            byte[] bytes = Serializeroot(value, variables);
            var effective = new global::CStructSharp.ReadOptions
            {
                DereferencePointers = false,
                AddressingMode = options?.AddressingMode ?? global::CStructSharp.PointerAddressingMode.Absolute,
                Origin = options?.Origin ?? 0,
                MaxPointerDepth = options?.MaxPointerDepth ?? 64,
                MaxPointerTargetBytes = options?.MaxPointerTargetBytes,
                MaxArrayElements = options?.MaxArrayElements ?? 1_000_000,
                MaxStringBytes = options?.MaxStringBytes ?? (16L * 1024 * 1024),
                MaxTotalBytesRead = options?.MaxTotalBytesRead ?? (64L * 1024 * 1024),
                MaxNestingDepth = options?.MaxNestingDepth ?? 256,
                TrimFixedText = options?.TrimFixedText ?? false,
            };
            return Layout.Parse(bytes, "root", variables, effective);
        }

        /// <summary>Maps a generated value to a mapped class through the runtime's <see cref="global::CStructSharp.Values.StructValue"/>: <c>ToMapped&lt;MyRoot&gt;(value)</c>.</summary>
        /// <typeparam name="T">A class implementing <see cref="global::CStructSharp.ICStructMapped{TSelf}"/>.</typeparam>
        /// <param name="value">The value to map.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <returns>The mapped instance.</returns>
        public static T ToMapped<T>(root value, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null)
            where T : global::CStructSharp.ICStructMapped<T>
            => T.ReadFrom(ToStructValue(value, variables));

        /// <summary>Serializes a mapped instance as the root declaration through the runtime layout (its <c>WriteTo</c> supplies the members).</summary>
        /// <typeparam name="T">A class implementing <see cref="global::CStructSharp.ICStructMapped{TSelf}"/>, registered with <see cref="global::CStructSharp.MappedTypes"/>.</typeparam>
        /// <param name="value">The instance to write.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The write options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The serialized bytes.</returns>
        public static byte[] SerializeMapped<T>(T value, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.WriteOptions? options = null)
            where T : global::CStructSharp.ICStructMapped<T>
            => Layout.Serialize("root", value!, variables, options);

        /// <summary>Reads the root declaration straight into a mapped class through the runtime layout.</summary>
        /// <typeparam name="T">A class implementing <see cref="global::CStructSharp.ICStructMapped{TSelf}"/>.</typeparam>
        /// <param name="source">The bytes; offset 0 is coordinate zero.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The read options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The mapped instance.</returns>
        public static T ParseMapped<T>(global::System.ReadOnlySpan<byte> source, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null)
            where T : global::CStructSharp.ICStructMapped<T>
            => T.ReadFrom(Layout.Parse(source, "root", variables, options));

        /// <summary>Reads the root declaration with the generated reader and the runtime's debug ranges (the runtime reads the same bytes once more to produce them).</summary>
        /// <param name="source">The bytes; offset 0 is coordinate zero.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The read options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The parsed value and one <see cref="global::CStructSharp.Diagnostics.DebugData"/> per value read, in read order.</returns>
        public static (root Value, global::System.Collections.Generic.IReadOnlyList<global::CStructSharp.Diagnostics.DebugData> Debug) ParseWithDebug(global::System.ReadOnlySpan<byte> source, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null)
        {
            root value = Parseroot(source, variables, options);
            return (value, Layout.ParseWithDebug(source, "root", variables, options).Debug);
        }

        /// <summary>Resolves a path (<c>root.field</c>, <c>items[2].value</c>, ...) to its byte address with the runtime layout.</summary>
        /// <param name="source">The bytes; offset 0 is coordinate zero.</param>
        /// <param name="path">The path, in the runtime's path grammar.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The read options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The address of the selected value.</returns>
        public static long ResolveAddress(global::System.ReadOnlySpan<byte> source, string path, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null) => Layout.ResolveAddress(source, path, variables, options);

        /// <summary>The element count of an array or string selected by a path, with the runtime layout.</summary>
        /// <param name="source">The bytes; offset 0 is coordinate zero.</param>
        /// <param name="path">The path, in the runtime's path grammar.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The read options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The element count.</returns>
        public static int GetArrayLength(global::System.ReadOnlySpan<byte> source, string path, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null) => Layout.GetArrayLength(source, path, variables, options);

        /// <summary>Replaces one value in place by path with the runtime layout; statically placed members also have typed setters in <see cref="Update"/>.</summary>
        /// <param name="target">The bytes holding the value.</param>
        /// <param name="path">The path, in the runtime's path grammar.</param>
        /// <param name="value">The new value.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The update options; <see langword="null"/> uses the documented defaults.</param>
        public static void UpdatePath(global::System.Span<byte> target, string path, object value, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.UpdateOptions? options = null) => Layout.Update(target, path, value, variables, options);

        /// <summary>The size in bytes of every composite with a static size (<c>sizeof</c>); a runtime-sized composite has none.</summary>
        public static class Sizes
        {
            /// <summary><c>sizeof(chunk)</c>.</summary>
            public const int chunk = 4;

            /// <summary><c>sizeof(root)</c>.</summary>
            public const int root = 5;
        }

        /// <summary>The offset from the root's first byte of every statically placed scalar (<c>offsetof</c>), nested by struct member.</summary>
        public static class Offsets
        {
            /// <summary><c>offsetof(root, tail)</c>.</summary>
            public const int tail = 4;

            /// <summary>The members of <c>first</c>.</summary>
            public static class first
            {
                /// <summary><c>offsetof(root, first.length)</c>.</summary>
                public const int length = 0;
            }
        }

        /// <summary>Typed in-place setters for the statically placed scalars, nested by struct member; a fixed array takes the element index.</summary>
        public static class Update
        {
            /// <summary>Stores <c>tail</c> into <paramref name="target"/> at offset 4, leaving every other byte alone.</summary>
            /// <param name="target">The bytes holding the value.</param>
            /// <param name="value">The new value.</param>
            public static void tail(global::System.Span<byte> target, byte value)
            {
                var cursor = global::CStructSharp.Generated.WriteCursor.ForUpdate(target, null, "root.tail");
                try
                {
                    cursor.Position = 4;
                    cursor.Reserve(1, "tail", "uint8")[0] = value;
                }
                catch (global::CStructSharp.Diagnostics.CStructException exception)
                {
                    cursor.Complete(exception);
                    throw;
                }
            }

            /// <summary>The members of <c>first</c>.</summary>
            public static class first
            {
                /// <summary>Stores <c>first.length</c> into <paramref name="target"/> at offset 0, leaving every other byte alone.</summary>
                /// <param name="target">The bytes holding the value.</param>
                /// <param name="value">The new value.</param>
                public static void length(global::System.Span<byte> target, uint value)
                {
                    var cursor = global::CStructSharp.Generated.WriteCursor.ForUpdate(target, null, "root.first.length");
                    try
                    {
                        cursor.Position = 0;
                        global::CStructSharp.Generated.Codec.WriteUInt32(cursor.Reserve(4, "length", "uint32"), value, true);
                    }
                    catch (global::CStructSharp.Diagnostics.CStructException exception)
                    {
                        cursor.Complete(exception);
                        throw;
                    }
                }
            }
        }
    }
}
