// <auto-generated/>
// Generated by CStructSharp from the [CStructLayout] attribute on Shapes. Do not edit.
#nullable enable
#pragma warning disable

namespace Demo
{
    [global::System.CodeDom.Compiler.GeneratedCode("CStructSharp", "<version>")]
    public static partial class Shapes
    {
        /// <summary>The layout text the members of this class were generated from.</summary>
        public const string Definition = "struct root {\n    uint32 attributes;\n    union { struct { uint16 ea_size; uint16 reserved; }; uint32 reparse_tag; };\n    union { uint8 narrow; uint16 wide; } choice;\n    struct { uint8 x; uint8 y; } pos;\n    struct { uint8 q; };\n    uint8 name_length;\n};";

        /// <summary>The declaration the plain <see cref="Parse"/> and <see cref="Serialize"/> methods operate on.</summary>
        public const string RootName = "root";

        private static readonly global::System.Lazy<global::CStructSharp.CStruct> LayoutInstance = new(CreateLayout, global::System.Threading.LazyThreadSafetyMode.ExecutionAndPublication);

        /// <summary>The runtime <see cref="global::CStructSharp.CStruct"/> for the same definition and options, built on first use: introspection, JSON, memory images, and the parity oracle.</summary>
        public static global::CStructSharp.CStruct Layout => LayoutInstance.Value;

        private static global::CStructSharp.CStruct CreateLayout()
        {
            var options = new global::CStructSharp.CStructCompilationOptions
            {
                CLongWidth = 64,
                BitfieldPacking = global::CStructSharp.BitfieldPacking.SysV,
                BitfieldAllocation = global::CStructSharp.BitfieldAllocation.LowBitFirst,
            };
            return new global::CStructSharp.CStruct(Definition, pointerSize: 8, aligned: false, isLittleEndian: true, compilationOptions: options);
        }

        /// <summary>The layout struct <c>root</c>.</summary>
        public sealed partial class Root
        {
            /// <summary><c>uint32 attributes</c>.</summary>
            public uint Attributes { get; set; }

            /// <summary><c>uint16 ea_size</c>.</summary>
            public ushort EaSize { get; set; }

            /// <summary><c>uint16 reserved</c>.</summary>
            public ushort Reserved { get; set; }

            /// <summary><c>uint32 reparse_tag</c>.</summary>
            public uint ReparseTag { get; set; }

            /// <summary><c>choice choice</c>.</summary>
            public RootChoice Choice { get; set; } = new();

            /// <summary><c>pos pos</c>.</summary>
            public RootPos Pos { get; set; } = new();

            /// <summary><c>uint8 q</c>.</summary>
            public byte Q { get; set; }

            /// <summary><c>uint8 name_length</c>.</summary>
            public byte NameLength { get; set; }
        }

        /// <summary>The layout union <c>choice</c> (declared inline).</summary>
        public sealed partial class RootChoice
        {
            /// <summary>The member a write stores, or <see langword="null"/> for the first member with a value; a read leaves it <see langword="null"/> because an untagged union does not say which view is active.</summary>
            public string? SelectedMember { get; set; }

            /// <summary>The union's stored bytes as read; a write with <see cref="SelectedMember"/> unset and no member value writes them back.</summary>
            public byte[]? RawStorage { get; set; }

            /// <summary><c>uint8 narrow</c>.</summary>
            public byte Narrow { get; set; }

            /// <summary><c>uint16 wide</c>.</summary>
            public ushort Wide { get; set; }
        }

        /// <summary>The layout struct <c>pos</c> (declared inline).</summary>
        public sealed partial class RootPos
        {
            /// <summary><c>uint8 x</c>.</summary>
            public byte X { get; set; }

            /// <summary><c>uint8 y</c>.</summary>
            public byte Y { get; set; }
        }

        private const bool Aligned = false;
        private const bool LittleEndian = true;
        private const int PointerSize = 8;
        private const bool HighBitFirst = false;
        private const global::CStructSharp.BitfieldPacking Packing = global::CStructSharp.BitfieldPacking.SysV;
        private const global::CStructSharp.BitfieldAllocation Allocation = global::CStructSharp.BitfieldAllocation.LowBitFirst;

        /// <summary>Reads one <c>root</c> from the start of <paramref name="source"/> with the generated reader; the same value, and the same failures, as the runtime's <c>Parse</c>.</summary>
        /// <param name="source">The bytes; offset 0 is coordinate zero.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The read options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The parsed value.</returns>
        public static Root ParseRoot(global::System.ReadOnlySpan<byte> source, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null)
        {
            var cursor = new global::CStructSharp.Generated.ReadCursor(source, options, "root");
            try
            {
                return ReadRoot(ref cursor, variables, null, null);
            }
            catch (global::CStructSharp.Diagnostics.CStructException exception)
            {
                cursor.Complete(exception);
                throw;
            }
        }

        /// <inheritdoc cref="ParseRoot(global::System.ReadOnlySpan{byte}, global::System.Collections.Generic.IReadOnlyDictionary{string, int}, global::CStructSharp.ReadOptions)"/>
        public static Root ParseRoot(byte[] source, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null)
            => ParseRoot(new global::System.ReadOnlySpan<byte>(source ?? throw new global::System.ArgumentNullException(nameof(source))), variables, options);

        /// <inheritdoc cref="ParseRoot(global::System.ReadOnlySpan{byte}, global::System.Collections.Generic.IReadOnlyDictionary{string, int}, global::CStructSharp.ReadOptions)"/>
        public static Root ParseRoot(global::System.ReadOnlyMemory<byte> source, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null)
            => ParseRoot(source.Span, variables, options);

        /// <summary>Reads the root declaration (<c>root</c>); see <see cref="ParseRoot(global::System.ReadOnlySpan{byte}, global::System.Collections.Generic.IReadOnlyDictionary{string, int}, global::CStructSharp.ReadOptions)"/>.</summary>
        /// <param name="source">The bytes; offset 0 is coordinate zero.</param>
        /// <param name="options">The read options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The parsed value.</returns>
        public static Root Parse(global::System.ReadOnlySpan<byte> source, global::CStructSharp.ReadOptions? options = null) => ParseRoot(source, null, options);

        /// <inheritdoc cref="Parse(global::System.ReadOnlySpan{byte}, global::CStructSharp.ReadOptions)"/>
        public static Root Parse(byte[] source, global::CStructSharp.ReadOptions? options = null) => ParseRoot(source, null, options);

        /// <inheritdoc cref="Parse(global::System.ReadOnlySpan{byte}, global::CStructSharp.ReadOptions)"/>
        public static Root Parse(global::System.ReadOnlyMemory<byte> source, global::CStructSharp.ReadOptions? options = null) => ParseRoot(source.Span, null, options);

        /// <summary>Reads one <c>root</c> at the cursor's position.</summary>
        private static Root ReadRoot(ref global::CStructSharp.Generated.ReadCursor cursor, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables, string? member, string? memberType)
        {
            cursor.EnterComposite(member ?? "root", memberType);
            var value = new Root();
            var placement = global::CStructSharp.Generated.CompositeCursor.Start(cursor.Position, Aligned, Packing, Allocation);
            // uint32 attributes
            {
                cursor.Seek(placement.AdvanceToField(4), "attributes", "uint32");
                value.Attributes = global::CStructSharp.Generated.Codec.ReadUInt32(cursor.Take(4, "attributes", "uint32"), true);
                placement.CompleteField(cursor.Position);
            }
            //  
            {
                cursor.Seek(placement.AdvanceToField(4), member, memberType);
                int unionStart = cursor.Position;
                cursor.EnterComposite(member, memberType);
                _ = cursor.Take(4, member, memberType);
                cursor.EnterUnion();
                cursor.Position = unionStart;
                //  
                {
                    cursor.EnterComposite(member, memberType);
                    var placementN = global::CStructSharp.Generated.CompositeCursor.Start(cursor.Position, Aligned, Packing, Allocation);
                    // uint16 ea_size
                    {
                        cursor.Seek(placementN.AdvanceToField(2), "ea_size", "uint16");
                        value.EaSize = global::CStructSharp.Generated.Codec.ReadUInt16(cursor.Take(2, "ea_size", "uint16"), true);
                        placementN.CompleteField(cursor.Position);
                    }
                    // uint16 reserved
                    {
                        cursor.Seek(placementN.AdvanceToField(2), "reserved", "uint16");
                        value.Reserved = global::CStructSharp.Generated.Codec.ReadUInt16(cursor.Take(2, "reserved", "uint16"), true);
                        placementN.CompleteField(cursor.Position);
                    }
                    cursor.Seek(placementN.Finish(2), member, memberType);
                    cursor.ExitComposite();
                }
                cursor.Position = unionStart;
                // uint32 reparse_tag
                {
                    value.ReparseTag = global::CStructSharp.Generated.Codec.ReadUInt32(cursor.Take(4, "reparse_tag", "uint32"), true);
                }
                cursor.ExitUnion();
                cursor.ExitComposite();
                cursor.Position = unionStart + 4;
                placement.CompleteField(cursor.Position);
            }
            // choice choice
            {
                cursor.Seek(placement.AdvanceToField(2), "choice", "choice");
                value.Choice = ReadRootChoice(ref cursor, variables, "choice", "choice");
                placement.CompleteField(cursor.Position);
            }
            // pos pos
            {
                cursor.Seek(placement.AdvanceToField(1), "pos", "pos");
                value.Pos = ReadRootPos(ref cursor, variables, "pos", "pos");
                placement.CompleteField(cursor.Position);
            }
            //  
            {
                cursor.Seek(placement.AdvanceToField(1), member, memberType);
                cursor.EnterComposite(member, memberType);
                var placementN = global::CStructSharp.Generated.CompositeCursor.Start(cursor.Position, Aligned, Packing, Allocation);
                // uint8 q
                {
                    cursor.Seek(placementN.AdvanceToField(1), "q", "uint8");
                    value.Q = cursor.Take(1, "q", "uint8")[0];
                    placementN.CompleteField(cursor.Position);
                }
                cursor.Seek(placementN.Finish(1), member, memberType);
                cursor.ExitComposite();
                placement.CompleteField(cursor.Position);
            }
            // uint8 name_length
            {
                cursor.Seek(placement.AdvanceToField(1), "name_length", "uint8");
                value.NameLength = cursor.Take(1, "name_length", "uint8")[0];
                placement.CompleteField(cursor.Position);
            }
            cursor.Seek(placement.Finish(4), member, memberType);
            cursor.ExitComposite();
            return value;
        }

        /// <summary>Reads one <c>choice</c> at the cursor's position.</summary>
        private static RootChoice ReadRootChoice(ref global::CStructSharp.Generated.ReadCursor cursor, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables, string? member, string? memberType)
        {
            cursor.EnterComposite(member ?? "choice", memberType);
            var value = new RootChoice();
            int unionStart = cursor.Position;
            value.RawStorage = cursor.Take(2, member, memberType).ToArray();
            cursor.EnterUnion();
            cursor.Position = unionStart;
            // uint8 narrow
            {
                value.Narrow = cursor.Take(1, "narrow", "uint8")[0];
            }
            cursor.Position = unionStart;
            // uint16 wide
            {
                value.Wide = global::CStructSharp.Generated.Codec.ReadUInt16(cursor.Take(2, "wide", "uint16"), true);
            }
            cursor.ExitUnion();
            cursor.Position = unionStart + 2;
            cursor.ExitComposite();
            return value;
        }

        /// <summary>Reads one <c>pos</c> at the cursor's position.</summary>
        private static RootPos ReadRootPos(ref global::CStructSharp.Generated.ReadCursor cursor, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables, string? member, string? memberType)
        {
            cursor.EnterComposite(member ?? "pos", memberType);
            var value = new RootPos();
            var placement = global::CStructSharp.Generated.CompositeCursor.Start(cursor.Position, Aligned, Packing, Allocation);
            // uint8 x
            {
                cursor.Seek(placement.AdvanceToField(1), "x", "uint8");
                value.X = cursor.Take(1, "x", "uint8")[0];
                placement.CompleteField(cursor.Position);
            }
            // uint8 y
            {
                cursor.Seek(placement.AdvanceToField(1), "y", "uint8");
                value.Y = cursor.Take(1, "y", "uint8")[0];
                placement.CompleteField(cursor.Position);
            }
            cursor.Seek(placement.Finish(1), member, memberType);
            cursor.ExitComposite();
            return value;
        }

        /// <summary>Groups a flat element array into rows of <paramref name="inner"/> elements (one nesting level of a multidimensional array).</summary>
        private static T[][] Split<T>(T[] flat, int inner)
        {
            var rows = new T[inner == 0 ? 0 : flat.Length / inner][];
            for (int row = 0; row < rows.Length; row++)
            {
                rows[row] = new T[inner];
                global::System.Array.Copy(flat, row * inner, rows[row], 0, inner);
            }
            return rows;
        }
    }
}
