// <auto-generated/>
// Generated by CStructSharp from the [CStructLayout] attribute on Shapes. Do not edit.
#nullable enable
#pragma warning disable

namespace Demo
{
    [global::System.CodeDom.Compiler.GeneratedCode("CStructSharp", "<version>")]
    public static partial class Shapes
    {
        /// <summary>The layout text the members of this class were generated from.</summary>
        public const string Definition = "struct root {\n    uint32 attributes;\n    union { struct { uint16 ea_size; uint16 reserved; }; uint32 reparse_tag; };\n    union { uint8 narrow; uint16 wide; } choice;\n    struct { uint8 x; uint8 y; } pos;\n    struct { uint8 q; };\n    uint8 name_length;\n};";

        /// <summary>The declaration the plain <see cref="Parse"/> and <see cref="Serialize"/> methods operate on.</summary>
        public const string RootName = "root";

        private static readonly global::System.Lazy<global::CStructSharp.CStruct> LayoutInstance = new(CreateLayout, global::System.Threading.LazyThreadSafetyMode.ExecutionAndPublication);

        /// <summary>The runtime <see cref="global::CStructSharp.CStruct"/> for the same definition and options, built on first use: introspection, JSON, memory images, and the parity oracle.</summary>
        public static global::CStructSharp.CStruct Layout => LayoutInstance.Value;

        private static global::CStructSharp.CStruct CreateLayout()
        {
            var options = new global::CStructSharp.CStructCompilationOptions
            {
                CLongWidth = 64,
                BitfieldPacking = global::CStructSharp.BitfieldPacking.SysV,
                BitfieldAllocation = global::CStructSharp.BitfieldAllocation.LowBitFirst,
            };
            return new global::CStructSharp.CStruct(Definition, pointerSize: 8, aligned: false, isLittleEndian: true, compilationOptions: options);
        }

        /// <summary>The layout struct <c>root</c>.</summary>
        public sealed partial class Root
        {
            /// <summary><c>uint32 attributes</c>.</summary>
            public uint Attributes { get; set; }

            /// <summary><c>uint16 ea_size</c>.</summary>
            public ushort EaSize { get; set; }

            /// <summary><c>uint16 reserved</c>.</summary>
            public ushort Reserved { get; set; }

            /// <summary><c>uint32 reparse_tag</c>.</summary>
            public uint ReparseTag { get; set; }

            /// <summary><c>choice choice</c>.</summary>
            public RootChoice Choice { get; set; } = new();

            /// <summary><c>pos pos</c>.</summary>
            public RootPos Pos { get; set; } = new();

            /// <summary><c>uint8 q</c>.</summary>
            public byte Q { get; set; }

            /// <summary><c>uint8 name_length</c>.</summary>
            public byte NameLength { get; set; }
        }

        /// <summary>The layout union <c>choice</c> (declared inline).</summary>
        public sealed partial class RootChoice
        {
            /// <summary>The member a write stores, or <see langword="null"/> for the first member with a value; a read leaves it <see langword="null"/> because an untagged union does not say which view is active.</summary>
            public string? SelectedMember { get; set; }

            /// <summary>The union's stored bytes as read; a write with <see cref="SelectedMember"/> unset and no member value writes them back.</summary>
            public byte[]? RawStorage { get; set; }

            /// <summary><c>uint8 narrow</c>.</summary>
            public byte Narrow { get; set; }

            /// <summary><c>uint16 wide</c>.</summary>
            public ushort Wide { get; set; }
        }

        /// <summary>The layout struct <c>pos</c> (declared inline).</summary>
        public sealed partial class RootPos
        {
            /// <summary><c>uint8 x</c>.</summary>
            public byte X { get; set; }

            /// <summary><c>uint8 y</c>.</summary>
            public byte Y { get; set; }
        }

        private const bool Aligned = false;
        private const bool LittleEndian = true;
        private const int PointerSize = 8;
        private const bool HighBitFirst = false;
        private const global::CStructSharp.BitfieldPacking Packing = global::CStructSharp.BitfieldPacking.SysV;
        private const global::CStructSharp.BitfieldAllocation Allocation = global::CStructSharp.BitfieldAllocation.LowBitFirst;

        /// <summary>Reads one <c>root</c> from the start of <paramref name="source"/> with the generated reader; the same value, and the same failures, as the runtime's <c>Parse</c>.</summary>
        /// <param name="source">The bytes; offset 0 is coordinate zero.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The read options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The parsed value.</returns>
        public static Root ParseRoot(global::System.ReadOnlySpan<byte> source, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null)
        {
            var cursor = new global::CStructSharp.Generated.ReadCursor(source, options, "root");
            try
            {
                return ReadRoot(ref cursor, variables, null, null);
            }
            catch (global::CStructSharp.Diagnostics.CStructException exception)
            {
                cursor.Complete(exception);
                throw;
            }
        }

        /// <inheritdoc cref="ParseRoot(global::System.ReadOnlySpan{byte}, global::System.Collections.Generic.IReadOnlyDictionary{string, int}, global::CStructSharp.ReadOptions)"/>
        public static Root ParseRoot(byte[] source, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null)
            => ParseRoot(new global::System.ReadOnlySpan<byte>(source ?? throw new global::System.ArgumentNullException(nameof(source))), variables, options);

        /// <inheritdoc cref="ParseRoot(global::System.ReadOnlySpan{byte}, global::System.Collections.Generic.IReadOnlyDictionary{string, int}, global::CStructSharp.ReadOptions)"/>
        public static Root ParseRoot(global::System.ReadOnlyMemory<byte> source, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null)
            => ParseRoot(source.Span, variables, options);

        /// <summary>Reads one <c>root</c> from <paramref name="stream"/>: the stream is buffered up to the total read budget (or its remaining length) and read through the span reader; a seekable stream is left after the value.</summary>
        /// <param name="stream">The stream, read from its current position.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The read options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The parsed value.</returns>
        public static Root ParseRoot(global::System.IO.Stream stream, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null)
        {
            global::System.ArgumentNullException.ThrowIfNull(stream);
            long start = stream.CanSeek ? stream.Position : 0;
            byte[] buffer = global::CStructSharp.Generated.ReadCursor.BufferStream(stream, options, out int length);
            try
            {
                var cursor = new global::CStructSharp.Generated.ReadCursor(new global::System.ReadOnlySpan<byte>(buffer, 0, length), options, "root");
                try
                {
                    Root value = ReadRoot(ref cursor, variables, null, null);
                    if (stream.CanSeek)
                    {
                        stream.Position = start + cursor.Position;
                    }
                    return value;
                }
                catch (global::CStructSharp.Diagnostics.CStructException exception)
                {
                    cursor.Complete(exception);
                    throw;
                }
            }
            finally
            {
                global::System.Buffers.ArrayPool<byte>.Shared.Return(buffer);
            }
        }

        /// <summary>Reads the root declaration (<c>root</c>); see <see cref="ParseRoot(global::System.ReadOnlySpan{byte}, global::System.Collections.Generic.IReadOnlyDictionary{string, int}, global::CStructSharp.ReadOptions)"/>.</summary>
        /// <param name="source">The bytes; offset 0 is coordinate zero.</param>
        /// <param name="options">The read options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The parsed value.</returns>
        public static Root Parse(global::System.ReadOnlySpan<byte> source, global::CStructSharp.ReadOptions? options = null) => ParseRoot(source, null, options);

        /// <inheritdoc cref="Parse(global::System.ReadOnlySpan{byte}, global::CStructSharp.ReadOptions)"/>
        public static Root Parse(byte[] source, global::CStructSharp.ReadOptions? options = null) => ParseRoot(source, null, options);

        /// <inheritdoc cref="Parse(global::System.ReadOnlySpan{byte}, global::CStructSharp.ReadOptions)"/>
        public static Root Parse(global::System.ReadOnlyMemory<byte> source, global::CStructSharp.ReadOptions? options = null) => ParseRoot(source.Span, null, options);

        /// <inheritdoc cref="ParseRoot(global::System.IO.Stream, global::System.Collections.Generic.IReadOnlyDictionary{string, int}, global::CStructSharp.ReadOptions)"/>
        public static Root Parse(global::System.IO.Stream stream, global::CStructSharp.ReadOptions? options = null) => ParseRoot(stream, null, options);

        /// <summary>Reads one <c>root</c> at the cursor's position.</summary>
        private static Root ReadRoot(ref global::CStructSharp.Generated.ReadCursor cursor, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables, string? member, string? memberType)
        {
            cursor.EnterComposite(member ?? "root", memberType);
            var value = new Root();
            var placement = global::CStructSharp.Generated.CompositeCursor.Start(cursor.Position, Aligned, Packing, Allocation);
            // uint32 attributes
            {
                cursor.Seek(placement.AdvanceToField(4), "attributes", "uint32");
                value.Attributes = global::CStructSharp.Generated.Codec.ReadUInt32(cursor.Take(4, "attributes", "uint32"), true);
                placement.CompleteField(cursor.Position);
            }
            //  
            {
                cursor.Seek(placement.AdvanceToField(4), member, memberType);
                int unionStart = cursor.Position;
                cursor.EnterComposite(member, memberType);
                _ = cursor.Take(4, member, memberType);
                cursor.EnterUnion();
                cursor.Position = unionStart;
                //  
                {
                    cursor.EnterComposite(member, memberType);
                    var placementUN = global::CStructSharp.Generated.CompositeCursor.Start(cursor.Position, Aligned, Packing, Allocation);
                    // uint16 ea_size
                    {
                        cursor.Seek(placementUN.AdvanceToField(2), "ea_size", "uint16");
                        value.EaSize = global::CStructSharp.Generated.Codec.ReadUInt16(cursor.Take(2, "ea_size", "uint16"), true);
                        placementUN.CompleteField(cursor.Position);
                    }
                    // uint16 reserved
                    {
                        cursor.Seek(placementUN.AdvanceToField(2), "reserved", "uint16");
                        value.Reserved = global::CStructSharp.Generated.Codec.ReadUInt16(cursor.Take(2, "reserved", "uint16"), true);
                        placementUN.CompleteField(cursor.Position);
                    }
                    cursor.Seek(placementUN.Finish(2), member, memberType);
                    cursor.ExitComposite();
                }
                cursor.Position = unionStart;
                // uint32 reparse_tag
                {
                    value.ReparseTag = global::CStructSharp.Generated.Codec.ReadUInt32(cursor.Take(4, "reparse_tag", "uint32"), true);
                }
                cursor.ExitUnion();
                cursor.ExitComposite();
                cursor.Position = unionStart + 4;
                placement.CompleteField(cursor.Position);
            }
            // choice choice
            {
                cursor.Seek(placement.AdvanceToField(2), "choice", "choice");
                value.Choice = ReadRootChoice(ref cursor, variables, "choice", "choice");
                placement.CompleteField(cursor.Position);
            }
            // pos pos
            {
                cursor.Seek(placement.AdvanceToField(1), "pos", "pos");
                value.Pos = ReadRootPos(ref cursor, variables, "pos", "pos");
                placement.CompleteField(cursor.Position);
            }
            //  
            {
                cursor.Seek(placement.AdvanceToField(1), member, memberType);
                cursor.EnterComposite(member, memberType);
                var placementN = global::CStructSharp.Generated.CompositeCursor.Start(cursor.Position, Aligned, Packing, Allocation);
                // uint8 q
                {
                    cursor.Seek(placementN.AdvanceToField(1), "q", "uint8");
                    value.Q = cursor.Take(1, "q", "uint8")[0];
                    placementN.CompleteField(cursor.Position);
                }
                cursor.Seek(placementN.Finish(1), member, memberType);
                cursor.ExitComposite();
                placement.CompleteField(cursor.Position);
            }
            // uint8 name_length
            {
                cursor.Seek(placement.AdvanceToField(1), "name_length", "uint8");
                value.NameLength = cursor.Take(1, "name_length", "uint8")[0];
                placement.CompleteField(cursor.Position);
            }
            cursor.Seek(placement.Finish(4), member, memberType);
            cursor.ExitComposite();
            return value;
        }

        /// <summary>Reads one <c>choice</c> at the cursor's position.</summary>
        private static RootChoice ReadRootChoice(ref global::CStructSharp.Generated.ReadCursor cursor, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables, string? member, string? memberType)
        {
            cursor.EnterComposite(member ?? "choice", memberType);
            var value = new RootChoice();
            int unionStart = cursor.Position;
            value.RawStorage = cursor.Take(2, member, memberType).ToArray();
            cursor.EnterUnion();
            cursor.Position = unionStart;
            // uint8 narrow
            {
                value.Narrow = cursor.Take(1, "narrow", "uint8")[0];
            }
            cursor.Position = unionStart;
            // uint16 wide
            {
                value.Wide = global::CStructSharp.Generated.Codec.ReadUInt16(cursor.Take(2, "wide", "uint16"), true);
            }
            cursor.ExitUnion();
            cursor.Position = unionStart + 2;
            cursor.ExitComposite();
            return value;
        }

        /// <summary>Reads one <c>pos</c> at the cursor's position.</summary>
        private static RootPos ReadRootPos(ref global::CStructSharp.Generated.ReadCursor cursor, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables, string? member, string? memberType)
        {
            cursor.EnterComposite(member ?? "pos", memberType);
            var value = new RootPos();
            var placement = global::CStructSharp.Generated.CompositeCursor.Start(cursor.Position, Aligned, Packing, Allocation);
            // uint8 x
            {
                cursor.Seek(placement.AdvanceToField(1), "x", "uint8");
                value.X = cursor.Take(1, "x", "uint8")[0];
                placement.CompleteField(cursor.Position);
            }
            // uint8 y
            {
                cursor.Seek(placement.AdvanceToField(1), "y", "uint8");
                value.Y = cursor.Take(1, "y", "uint8")[0];
                placement.CompleteField(cursor.Position);
            }
            cursor.Seek(placement.Finish(1), member, memberType);
            cursor.ExitComposite();
            return value;
        }

        /// <summary>Groups a flat element array into rows of <paramref name="inner"/> elements (one nesting level of a multidimensional array).</summary>
        private static T[][] Split<T>(T[] flat, int inner)
        {
            var rows = new T[inner == 0 ? 0 : flat.Length / inner][];
            for (int row = 0; row < rows.Length; row++)
            {
                rows[row] = new T[inner];
                global::System.Array.Copy(flat, row * inner, rows[row], 0, inner);
            }
            return rows;
        }

        /// <summary>Writes one <c>root</c> into a new array with the generated writer; the same bytes, and the same failures, as the runtime's <c>Serialize</c>.</summary>
        /// <param name="value">The value to write.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The write options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The serialized bytes.</returns>
        public static byte[] SerializeRoot(Root value, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.WriteOptions? options = null)
        {
            var cursor = new global::CStructSharp.Generated.WriteCursor(options, "root");
            try
            {
                EncodeRoot(ref cursor, value, variables, null, null);
                return cursor.ToArray();
            }
            catch (global::CStructSharp.Diagnostics.CStructException exception)
            {
                cursor.Complete(exception);
                throw;
            }
            finally
            {
                cursor.Dispose();
            }
        }

        /// <summary>Writes one <c>root</c> into <paramref name="destination"/>; a value that does not fit fails with the runtime's capacity message.</summary>
        /// <param name="value">The value to write.</param>
        /// <param name="destination">The bytes to write into.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The write options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The number of bytes written.</returns>
        public static int SerializeRoot(Root value, global::System.Span<byte> destination, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.WriteOptions? options = null)
        {
            var cursor = new global::CStructSharp.Generated.WriteCursor(destination, options, "root");
            try
            {
                EncodeRoot(ref cursor, value, variables, null, null);
                return cursor.Length;
            }
            catch (global::CStructSharp.Diagnostics.CStructException exception)
            {
                cursor.Complete(exception);
                throw;
            }
        }

        /// <summary>Writes one <c>root</c> to <paramref name="stream"/> at its current position.</summary>
        /// <param name="stream">The destination stream.</param>
        /// <param name="value">The value to write.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The write options; <see langword="null"/> uses the documented defaults.</param>
        public static void WriteRoot(global::System.IO.Stream stream, Root value, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.WriteOptions? options = null)
        {
            global::System.ArgumentNullException.ThrowIfNull(stream);
            if (!stream.CanWrite)
            {
                throw new global::System.ArgumentException("Writing requires a writable stream.", nameof(stream));
            }
            byte[] bytes = SerializeRoot(value, variables, options);
            stream.Write(bytes, 0, bytes.Length);
        }

        /// <summary>Writes the root declaration (<c>root</c>) into a new array; see <see cref="SerializeRoot(Root, global::System.Collections.Generic.IReadOnlyDictionary{string, int}, global::CStructSharp.WriteOptions)"/>.</summary>
        /// <param name="value">The value to write.</param>
        /// <param name="options">The write options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The serialized bytes.</returns>
        public static byte[] Serialize(Root value, global::CStructSharp.WriteOptions? options = null) => SerializeRoot(value, null, options);

        /// <summary>Writes the root declaration (<c>root</c>) into <paramref name="destination"/>.</summary>
        /// <param name="value">The value to write.</param>
        /// <param name="destination">The bytes to write into.</param>
        /// <param name="options">The write options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The number of bytes written.</returns>
        public static int Serialize(Root value, global::System.Span<byte> destination, global::CStructSharp.WriteOptions? options = null) => SerializeRoot(value, destination, null, options);

        /// <summary>Writes the root declaration (<c>root</c>) to <paramref name="stream"/>.</summary>
        /// <param name="stream">The destination stream.</param>
        /// <param name="value">The value to write.</param>
        /// <param name="options">The write options; <see langword="null"/> uses the documented defaults.</param>
        public static void Write(global::System.IO.Stream stream, Root value, global::CStructSharp.WriteOptions? options = null) => WriteRoot(stream, value, null, options);

        /// <summary>Writes one <c>choice</c> into a new array with the generated writer; the same bytes, and the same failures, as the runtime's <c>Serialize</c>.</summary>
        /// <param name="value">The value to write.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The write options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The serialized bytes.</returns>
        public static byte[] SerializeRootChoice(RootChoice value, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.WriteOptions? options = null)
        {
            var cursor = new global::CStructSharp.Generated.WriteCursor(options, "choice");
            try
            {
                EncodeRootChoice(ref cursor, value, variables, null, null);
                return cursor.ToArray();
            }
            catch (global::CStructSharp.Diagnostics.CStructException exception)
            {
                cursor.Complete(exception);
                throw;
            }
            finally
            {
                cursor.Dispose();
            }
        }

        /// <summary>Writes one <c>choice</c> into <paramref name="destination"/>; a value that does not fit fails with the runtime's capacity message.</summary>
        /// <param name="value">The value to write.</param>
        /// <param name="destination">The bytes to write into.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The write options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The number of bytes written.</returns>
        public static int SerializeRootChoice(RootChoice value, global::System.Span<byte> destination, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.WriteOptions? options = null)
        {
            var cursor = new global::CStructSharp.Generated.WriteCursor(destination, options, "choice");
            try
            {
                EncodeRootChoice(ref cursor, value, variables, null, null);
                return cursor.Length;
            }
            catch (global::CStructSharp.Diagnostics.CStructException exception)
            {
                cursor.Complete(exception);
                throw;
            }
        }

        /// <summary>Writes one <c>choice</c> to <paramref name="stream"/> at its current position.</summary>
        /// <param name="stream">The destination stream.</param>
        /// <param name="value">The value to write.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The write options; <see langword="null"/> uses the documented defaults.</param>
        public static void WriteRootChoice(global::System.IO.Stream stream, RootChoice value, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.WriteOptions? options = null)
        {
            global::System.ArgumentNullException.ThrowIfNull(stream);
            if (!stream.CanWrite)
            {
                throw new global::System.ArgumentException("Writing requires a writable stream.", nameof(stream));
            }
            byte[] bytes = SerializeRootChoice(value, variables, options);
            stream.Write(bytes, 0, bytes.Length);
        }

        /// <summary>Writes one <c>pos</c> into a new array with the generated writer; the same bytes, and the same failures, as the runtime's <c>Serialize</c>.</summary>
        /// <param name="value">The value to write.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The write options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The serialized bytes.</returns>
        public static byte[] SerializeRootPos(RootPos value, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.WriteOptions? options = null)
        {
            var cursor = new global::CStructSharp.Generated.WriteCursor(options, "pos");
            try
            {
                EncodeRootPos(ref cursor, value, variables, null, null);
                return cursor.ToArray();
            }
            catch (global::CStructSharp.Diagnostics.CStructException exception)
            {
                cursor.Complete(exception);
                throw;
            }
            finally
            {
                cursor.Dispose();
            }
        }

        /// <summary>Writes one <c>pos</c> into <paramref name="destination"/>; a value that does not fit fails with the runtime's capacity message.</summary>
        /// <param name="value">The value to write.</param>
        /// <param name="destination">The bytes to write into.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The write options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The number of bytes written.</returns>
        public static int SerializeRootPos(RootPos value, global::System.Span<byte> destination, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.WriteOptions? options = null)
        {
            var cursor = new global::CStructSharp.Generated.WriteCursor(destination, options, "pos");
            try
            {
                EncodeRootPos(ref cursor, value, variables, null, null);
                return cursor.Length;
            }
            catch (global::CStructSharp.Diagnostics.CStructException exception)
            {
                cursor.Complete(exception);
                throw;
            }
        }

        /// <summary>Writes one <c>pos</c> to <paramref name="stream"/> at its current position.</summary>
        /// <param name="stream">The destination stream.</param>
        /// <param name="value">The value to write.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The write options; <see langword="null"/> uses the documented defaults.</param>
        public static void WriteRootPos(global::System.IO.Stream stream, RootPos value, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.WriteOptions? options = null)
        {
            global::System.ArgumentNullException.ThrowIfNull(stream);
            if (!stream.CanWrite)
            {
                throw new global::System.ArgumentException("Writing requires a writable stream.", nameof(stream));
            }
            byte[] bytes = SerializeRootPos(value, variables, options);
            stream.Write(bytes, 0, bytes.Length);
        }

        /// <summary>Writes one <c>root</c> at the cursor's position.</summary>
        private static void EncodeRoot(ref global::CStructSharp.Generated.WriteCursor cursor, Root? value, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables, string? member, string? memberType)
        {
            if (value is null)
            {
                throw cursor.Fail("Null is not valid for struct or union value: root", member, memberType);
            }
            cursor.EnterComposite(member ?? "root", memberType);
            var placement = global::CStructSharp.Generated.CompositeCursor.Start(cursor.Position, Aligned, Packing, Allocation);
            // uint32 attributes
            {
                cursor.Seek(placement.AdvanceToField(4), "attributes", "uint32");
                global::CStructSharp.Generated.Codec.WriteUInt32(cursor.Reserve(4, "attributes", "uint32"), value.Attributes, true);
                placement.CompleteField(cursor.Position);
            }
            //  
            {
                cursor.Seek(placement.AdvanceToField(4), member, memberType);
                int unionStart = cursor.Position;
                cursor.EnterComposite(member, memberType);
                cursor.Pad(4, member, memberType);
                cursor.Position = unionStart;
                //  
                {
                    cursor.EnterComposite(member, memberType);
                    var placementUN = global::CStructSharp.Generated.CompositeCursor.Start(cursor.Position, Aligned, Packing, Allocation);
                    // uint16 ea_size
                    {
                        cursor.Seek(placementUN.AdvanceToField(2), "ea_size", "uint16");
                        global::CStructSharp.Generated.Codec.WriteUInt16(cursor.Reserve(2, "ea_size", "uint16"), value.EaSize, true);
                        placementUN.CompleteField(cursor.Position);
                    }
                    // uint16 reserved
                    {
                        cursor.Seek(placementUN.AdvanceToField(2), "reserved", "uint16");
                        global::CStructSharp.Generated.Codec.WriteUInt16(cursor.Reserve(2, "reserved", "uint16"), value.Reserved, true);
                        placementUN.CompleteField(cursor.Position);
                    }
                    cursor.Seek(placementUN.Current, member, memberType);
                    cursor.Pad((int)(placementUN.Finish(2) - placementUN.Current), member, memberType);
                    cursor.ExitComposite();
                }
                cursor.ExitComposite();
                cursor.Position = unionStart + 4;
                placement.CompleteField(cursor.Position);
            }
            // choice choice
            {
                cursor.Seek(placement.AdvanceToField(2), "choice", "choice");
                if (value.Choice is null)
                {
                    throw cursor.Fail("Null is valid only for a scalar pointer field: choice", "choice", "choice");
                }
                EncodeRootChoice(ref cursor, value.Choice, variables, "choice", "choice");
                placement.CompleteField(cursor.Position);
            }
            // pos pos
            {
                cursor.Seek(placement.AdvanceToField(1), "pos", "pos");
                if (value.Pos is null)
                {
                    throw cursor.Fail("Null is valid only for a scalar pointer field: pos", "pos", "pos");
                }
                EncodeRootPos(ref cursor, value.Pos, variables, "pos", "pos");
                placement.CompleteField(cursor.Position);
            }
            //  
            {
                cursor.Seek(placement.AdvanceToField(1), member, memberType);
                cursor.EnterComposite(member, memberType);
                var placementN = global::CStructSharp.Generated.CompositeCursor.Start(cursor.Position, Aligned, Packing, Allocation);
                // uint8 q
                {
                    cursor.Seek(placementN.AdvanceToField(1), "q", "uint8");
                    cursor.Reserve(1, "q", "uint8")[0] = value.Q;
                    placementN.CompleteField(cursor.Position);
                }
                cursor.Seek(placementN.Current, member, memberType);
                cursor.Pad((int)(placementN.Finish(1) - placementN.Current), member, memberType);
                cursor.ExitComposite();
                placement.CompleteField(cursor.Position);
            }
            // uint8 name_length
            {
                cursor.Seek(placement.AdvanceToField(1), "name_length", "uint8");
                cursor.Reserve(1, "name_length", "uint8")[0] = value.NameLength;
                placement.CompleteField(cursor.Position);
            }
            cursor.Seek(placement.Current, member, memberType);
            cursor.Pad((int)(placement.Finish(4) - placement.Current), member, memberType);
            cursor.ExitComposite();
        }

        /// <summary>Writes one <c>choice</c> at the cursor's position.</summary>
        private static void EncodeRootChoice(ref global::CStructSharp.Generated.WriteCursor cursor, RootChoice? value, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables, string? member, string? memberType)
        {
            if (value is null)
            {
                throw cursor.Fail("Null is not valid for struct or union value: choice", member, memberType);
            }
            cursor.EnterComposite(member ?? "choice", memberType);
            int unionStart = cursor.Position;
            if (value.SelectedMember is null)
            {
                if (value.RawStorage is null)
                {
                    throw cursor.Fail("A whole union write requires SelectedMember or RawStorage: choice", member, memberType);
                }
                if (value.RawStorage.Length != 2)
                {
                    throw cursor.Fail("Raw storage length mismatch for choice: expected 2, got " + value.RawStorage.Length.ToString(global::System.Globalization.CultureInfo.InvariantCulture) + ".", member, memberType);
                }
                new global::System.ReadOnlySpan<byte>(value.RawStorage).CopyTo(cursor.Reserve(2, member, memberType));
                cursor.ExitComposite();
                return;
            }
            cursor.Pad(2, member, memberType);
            cursor.Position = unionStart;
            switch (value.SelectedMember)
            {
            case "narrow":
                // uint8 narrow
                {
                    cursor.Reserve(1, "narrow", "uint8")[0] = value.Narrow;
                }
                break;
            case "wide":
                // uint16 wide
                {
                    global::CStructSharp.Generated.Codec.WriteUInt16(cursor.Reserve(2, "wide", "uint16"), value.Wide, true);
                }
                break;
            default:
                throw cursor.Fail("Union 'choice' has no member named '" + value.SelectedMember + "'.", member, memberType);
            }
            cursor.Position = unionStart + 2;
            cursor.ExitComposite();
        }

        /// <summary>Writes one <c>pos</c> at the cursor's position.</summary>
        private static void EncodeRootPos(ref global::CStructSharp.Generated.WriteCursor cursor, RootPos? value, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables, string? member, string? memberType)
        {
            if (value is null)
            {
                throw cursor.Fail("Null is not valid for struct or union value: pos", member, memberType);
            }
            cursor.EnterComposite(member ?? "pos", memberType);
            var placement = global::CStructSharp.Generated.CompositeCursor.Start(cursor.Position, Aligned, Packing, Allocation);
            // uint8 x
            {
                cursor.Seek(placement.AdvanceToField(1), "x", "uint8");
                cursor.Reserve(1, "x", "uint8")[0] = value.X;
                placement.CompleteField(cursor.Position);
            }
            // uint8 y
            {
                cursor.Seek(placement.AdvanceToField(1), "y", "uint8");
                cursor.Reserve(1, "y", "uint8")[0] = value.Y;
                placement.CompleteField(cursor.Position);
            }
            cursor.Seek(placement.Current, member, memberType);
            cursor.Pad((int)(placement.Finish(1) - placement.Current), member, memberType);
            cursor.ExitComposite();
        }

        /// <summary>The root declaration as <see cref="global::CStructSharp.ICStructGenerated{Root}"/>.</summary>
        public sealed partial class Root : global::CStructSharp.ICStructGenerated<Root>
        {
            /// <inheritdoc/>
            static global::CStructSharp.CStruct global::CStructSharp.ICStructGenerated<Root>.Layout => Shapes.Layout;

            /// <inheritdoc/>
            static string global::CStructSharp.ICStructGenerated<Root>.RootName => Shapes.RootName;

            /// <inheritdoc/>
            static Root global::CStructSharp.ICStructGenerated<Root>.Parse(global::System.ReadOnlySpan<byte> source, global::CStructSharp.ReadOptions? options) => Shapes.Parse(source, options);

            /// <inheritdoc/>
            static int global::CStructSharp.ICStructGenerated<Root>.Serialize(Root value, global::System.Span<byte> destination, global::CStructSharp.WriteOptions? options) => Shapes.Serialize(value, destination, options);
        }

        /// <summary>The runtime's <see cref="global::CStructSharp.Values.StructValue"/> for a generated value: its bytes, parsed by the runtime layout (every member, in the layout's shape). Pointers keep their addresses and are not followed: the value's bytes hold no targets.</summary>
        /// <param name="value">The value to convert.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The read options for the runtime parse (limits, text trimming); <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The struct value.</returns>
        public static global::CStructSharp.Values.StructValue ToStructValue(Root value, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null)
        {
            byte[] bytes = SerializeRoot(value, variables);
            var effective = new global::CStructSharp.ReadOptions
            {
                DereferencePointers = false,
                AddressingMode = options?.AddressingMode ?? global::CStructSharp.PointerAddressingMode.Absolute,
                Origin = options?.Origin ?? 0,
                MaxPointerDepth = options?.MaxPointerDepth ?? 64,
                MaxPointerTargetBytes = options?.MaxPointerTargetBytes,
                MaxArrayElements = options?.MaxArrayElements ?? 1_000_000,
                MaxStringBytes = options?.MaxStringBytes ?? (16L * 1024 * 1024),
                MaxTotalBytesRead = options?.MaxTotalBytesRead ?? (64L * 1024 * 1024),
                MaxNestingDepth = options?.MaxNestingDepth ?? 256,
                TrimFixedText = options?.TrimFixedText ?? false,
            };
            return Layout.Parse(bytes, "root", variables, effective);
        }

        /// <summary>Maps a generated value to a mapped class through the runtime's <see cref="global::CStructSharp.Values.StructValue"/>: <c>ToMapped&lt;MyRoot&gt;(value)</c>.</summary>
        /// <typeparam name="T">A class implementing <see cref="global::CStructSharp.ICStructMapped{TSelf}"/>.</typeparam>
        /// <param name="value">The value to map.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <returns>The mapped instance.</returns>
        public static T ToMapped<T>(Root value, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null)
            where T : global::CStructSharp.ICStructMapped<T>
            => T.ReadFrom(ToStructValue(value, variables));

        /// <summary>Serializes a mapped instance as the root declaration through the runtime layout (its <c>WriteTo</c> supplies the members).</summary>
        /// <typeparam name="T">A class implementing <see cref="global::CStructSharp.ICStructMapped{TSelf}"/>, registered with <see cref="global::CStructSharp.MappedTypes"/>.</typeparam>
        /// <param name="value">The instance to write.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The write options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The serialized bytes.</returns>
        public static byte[] SerializeMapped<T>(T value, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.WriteOptions? options = null)
            where T : global::CStructSharp.ICStructMapped<T>
            => Layout.Serialize("root", value!, variables, options);

        /// <summary>Reads the root declaration straight into a mapped class through the runtime layout.</summary>
        /// <typeparam name="T">A class implementing <see cref="global::CStructSharp.ICStructMapped{TSelf}"/>.</typeparam>
        /// <param name="source">The bytes; offset 0 is coordinate zero.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The read options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The mapped instance.</returns>
        public static T ParseMapped<T>(global::System.ReadOnlySpan<byte> source, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null)
            where T : global::CStructSharp.ICStructMapped<T>
            => T.ReadFrom(Layout.Parse(source, "root", variables, options));

        /// <summary>Reads the root declaration with the generated reader and the runtime's debug ranges (the runtime reads the same bytes once more to produce them).</summary>
        /// <param name="source">The bytes; offset 0 is coordinate zero.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The read options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The parsed value and one <see cref="global::CStructSharp.Diagnostics.DebugData"/> per value read, in read order.</returns>
        public static (Root Value, global::System.Collections.Generic.IReadOnlyList<global::CStructSharp.Diagnostics.DebugData> Debug) ParseWithDebug(global::System.ReadOnlySpan<byte> source, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null)
        {
            Root value = ParseRoot(source, variables, options);
            return (value, Layout.ParseWithDebug(source, "root", variables, options).Debug);
        }

        /// <summary>Resolves a path (<c>root.field</c>, <c>items[2].value</c>, ...) to its byte address with the runtime layout.</summary>
        /// <param name="source">The bytes; offset 0 is coordinate zero.</param>
        /// <param name="path">The path, in the runtime's path grammar.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The read options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The address of the selected value.</returns>
        public static long ResolveAddress(global::System.ReadOnlySpan<byte> source, string path, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null) => Layout.ResolveAddress(source, path, variables, options);

        /// <summary>The element count of an array or string selected by a path, with the runtime layout.</summary>
        /// <param name="source">The bytes; offset 0 is coordinate zero.</param>
        /// <param name="path">The path, in the runtime's path grammar.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The read options; <see langword="null"/> uses the documented defaults.</param>
        /// <returns>The element count.</returns>
        public static int GetArrayLength(global::System.ReadOnlySpan<byte> source, string path, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.ReadOptions? options = null) => Layout.GetArrayLength(source, path, variables, options);

        /// <summary>Replaces one value in place by path with the runtime layout; statically placed members also have typed setters in <see cref="Update"/>.</summary>
        /// <param name="target">The bytes holding the value.</param>
        /// <param name="path">The path, in the runtime's path grammar.</param>
        /// <param name="value">The new value.</param>
        /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
        /// <param name="options">The update options; <see langword="null"/> uses the documented defaults.</param>
        public static void UpdatePath(global::System.Span<byte> target, string path, object value, global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null, global::CStructSharp.UpdateOptions? options = null) => Layout.Update(target, path, value, variables, options);

        /// <summary>The size in bytes of every composite with a static size (<c>sizeof</c>); a runtime-sized composite has none.</summary>
        public static class Sizes
        {
            /// <summary><c>sizeof(root)</c>.</summary>
            public const int Root = 14;

            /// <summary><c>sizeof(choice)</c>.</summary>
            public const int RootChoice = 2;

            /// <summary><c>sizeof(pos)</c>.</summary>
            public const int RootPos = 2;
        }

        /// <summary>The offset from the root's first byte of every statically placed scalar (<c>offsetof</c>), nested by struct member.</summary>
        public static class Offsets
        {
            /// <summary><c>offsetof(root, attributes)</c>.</summary>
            public const int Attributes = 0;

            /// <summary><c>offsetof(root, ea_size)</c>.</summary>
            public const int EaSize = 4;

            /// <summary><c>offsetof(root, reserved)</c>.</summary>
            public const int Reserved = 6;

            /// <summary><c>offsetof(root, reparse_tag)</c>.</summary>
            public const int ReparseTag = 4;

            /// <summary><c>offsetof(root, q)</c>.</summary>
            public const int Q = 12;

            /// <summary><c>offsetof(root, name_length)</c>.</summary>
            public const int NameLength = 13;

            /// <summary>The members of <c>Pos</c>.</summary>
            public static class Pos
            {
                /// <summary><c>offsetof(root, pos.x)</c>.</summary>
                public const int X = 10;

                /// <summary><c>offsetof(root, pos.y)</c>.</summary>
                public const int Y = 11;
            }
        }

        /// <summary>Typed in-place setters for the statically placed scalars, nested by struct member; a fixed array takes the element index.</summary>
        public static class Update
        {
            /// <summary>Stores <c>attributes</c> into <paramref name="target"/> at offset 0, leaving every other byte alone.</summary>
            /// <param name="target">The bytes holding the value.</param>
            /// <param name="value">The new value.</param>
            public static void Attributes(global::System.Span<byte> target, uint value)
            {
                var cursor = global::CStructSharp.Generated.WriteCursor.ForUpdate(target, null, "root.attributes");
                try
                {
                    cursor.Position = 0;
                    global::CStructSharp.Generated.Codec.WriteUInt32(cursor.Reserve(4, "attributes", "uint32"), value, true);
                }
                catch (global::CStructSharp.Diagnostics.CStructException exception)
                {
                    cursor.Complete(exception);
                    throw;
                }
            }

            /// <summary>Stores <c>ea_size</c> into <paramref name="target"/> at offset 4, leaving every other byte alone.</summary>
            /// <param name="target">The bytes holding the value.</param>
            /// <param name="value">The new value.</param>
            public static void EaSize(global::System.Span<byte> target, ushort value)
            {
                var cursor = global::CStructSharp.Generated.WriteCursor.ForUpdate(target, null, "root.ea_size");
                try
                {
                    cursor.Position = 4;
                    global::CStructSharp.Generated.Codec.WriteUInt16(cursor.Reserve(2, "ea_size", "uint16"), value, true);
                }
                catch (global::CStructSharp.Diagnostics.CStructException exception)
                {
                    cursor.Complete(exception);
                    throw;
                }
            }

            /// <summary>Stores <c>reserved</c> into <paramref name="target"/> at offset 6, leaving every other byte alone.</summary>
            /// <param name="target">The bytes holding the value.</param>
            /// <param name="value">The new value.</param>
            public static void Reserved(global::System.Span<byte> target, ushort value)
            {
                var cursor = global::CStructSharp.Generated.WriteCursor.ForUpdate(target, null, "root.reserved");
                try
                {
                    cursor.Position = 6;
                    global::CStructSharp.Generated.Codec.WriteUInt16(cursor.Reserve(2, "reserved", "uint16"), value, true);
                }
                catch (global::CStructSharp.Diagnostics.CStructException exception)
                {
                    cursor.Complete(exception);
                    throw;
                }
            }

            /// <summary>Stores <c>reparse_tag</c> into <paramref name="target"/> at offset 4, leaving every other byte alone.</summary>
            /// <param name="target">The bytes holding the value.</param>
            /// <param name="value">The new value.</param>
            public static void ReparseTag(global::System.Span<byte> target, uint value)
            {
                var cursor = global::CStructSharp.Generated.WriteCursor.ForUpdate(target, null, "root.reparse_tag");
                try
                {
                    cursor.Position = 4;
                    global::CStructSharp.Generated.Codec.WriteUInt32(cursor.Reserve(4, "reparse_tag", "uint32"), value, true);
                }
                catch (global::CStructSharp.Diagnostics.CStructException exception)
                {
                    cursor.Complete(exception);
                    throw;
                }
            }

            /// <summary>Stores <c>q</c> into <paramref name="target"/> at offset 12, leaving every other byte alone.</summary>
            /// <param name="target">The bytes holding the value.</param>
            /// <param name="value">The new value.</param>
            public static void Q(global::System.Span<byte> target, byte value)
            {
                var cursor = global::CStructSharp.Generated.WriteCursor.ForUpdate(target, null, "root.q");
                try
                {
                    cursor.Position = 12;
                    cursor.Reserve(1, "q", "uint8")[0] = value;
                }
                catch (global::CStructSharp.Diagnostics.CStructException exception)
                {
                    cursor.Complete(exception);
                    throw;
                }
            }

            /// <summary>Stores <c>name_length</c> into <paramref name="target"/> at offset 13, leaving every other byte alone.</summary>
            /// <param name="target">The bytes holding the value.</param>
            /// <param name="value">The new value.</param>
            public static void NameLength(global::System.Span<byte> target, byte value)
            {
                var cursor = global::CStructSharp.Generated.WriteCursor.ForUpdate(target, null, "root.name_length");
                try
                {
                    cursor.Position = 13;
                    cursor.Reserve(1, "name_length", "uint8")[0] = value;
                }
                catch (global::CStructSharp.Diagnostics.CStructException exception)
                {
                    cursor.Complete(exception);
                    throw;
                }
            }

            /// <summary>The members of <c>Pos</c>.</summary>
            public static class Pos
            {
                /// <summary>Stores <c>pos.x</c> into <paramref name="target"/> at offset 10, leaving every other byte alone.</summary>
                /// <param name="target">The bytes holding the value.</param>
                /// <param name="value">The new value.</param>
                public static void X(global::System.Span<byte> target, byte value)
                {
                    var cursor = global::CStructSharp.Generated.WriteCursor.ForUpdate(target, null, "root.pos.x");
                    try
                    {
                        cursor.Position = 10;
                        cursor.Reserve(1, "x", "uint8")[0] = value;
                    }
                    catch (global::CStructSharp.Diagnostics.CStructException exception)
                    {
                        cursor.Complete(exception);
                        throw;
                    }
                }

                /// <summary>Stores <c>pos.y</c> into <paramref name="target"/> at offset 11, leaving every other byte alone.</summary>
                /// <param name="target">The bytes holding the value.</param>
                /// <param name="value">The new value.</param>
                public static void Y(global::System.Span<byte> target, byte value)
                {
                    var cursor = global::CStructSharp.Generated.WriteCursor.ForUpdate(target, null, "root.pos.y");
                    try
                    {
                        cursor.Position = 11;
                        cursor.Reserve(1, "y", "uint8")[0] = value;
                    }
                    catch (global::CStructSharp.Diagnostics.CStructException exception)
                    {
                        cursor.Complete(exception);
                        throw;
                    }
                }
            }
        }

        /// <summary>
        ///     A zero-allocation view of one <c>root</c> over its bytes: each statically placed member decodes
        ///     directly from the span when read; a member the view does not expose (runtime-sized, conditional, or placed after one)
        ///     is reached through <see cref="ToObject"/>. A view cannot leave the method that created it.
        /// </summary>
        public readonly ref struct RootView
        {
            private readonly global::System.ReadOnlySpan<byte> source;
            private readonly global::CStructSharp.ReadOptions? options;

            /// <summary>Creates a view over <paramref name="source"/>, whose first byte is the value's first byte; the source must hold the value's 14 bytes.</summary>
            /// <param name="source">The bytes, from the value's start; more may follow (pointer targets, the rest of the input).</param>
            /// <param name="options">The read options <see cref="ToObject"/> uses; <see langword="null"/> uses the documented defaults.</param>
            public RootView(global::System.ReadOnlySpan<byte> source, global::CStructSharp.ReadOptions? options = null)
            {
                if (source.Length < 14)
                {
                    var cursor = new global::CStructSharp.Generated.ReadCursor(source, options, "root");
                    global::CStructSharp.Diagnostics.CStructException failure = cursor.Fail(global::CStructSharp.Generated.ReadCursor.ShortReadText(14, source.Length), null, null);
                    cursor.Complete(failure);
                    throw failure;
                }
                this.source = source;
                this.options = options;
            }

            /// <summary>Gets the value's bytes (its 14 bytes).</summary>
            public global::System.ReadOnlySpan<byte> Bytes => this.source.Slice(0, 14);

            /// <summary><c>uint32 attributes</c> at offset 0.</summary>
            public uint Attributes => global::CStructSharp.Generated.Codec.ReadUInt32(this.source.Slice(0, 4), true);

            /// <summary><c>uint16 ea_size</c> at offset 4.</summary>
            public ushort EaSize => global::CStructSharp.Generated.Codec.ReadUInt16(this.source.Slice(4, 2), true);

            /// <summary><c>uint16 reserved</c> at offset 6.</summary>
            public ushort Reserved => global::CStructSharp.Generated.Codec.ReadUInt16(this.source.Slice(6, 2), true);

            /// <summary><c>uint32 reparse_tag</c> at offset 4.</summary>
            public uint ReparseTag => global::CStructSharp.Generated.Codec.ReadUInt32(this.source.Slice(4, 4), true);

            /// <summary>A view of <c>choice choice</c> at offset 8.</summary>
            public RootChoiceView Choice => new(this.source.Slice(8), this.options);

            /// <summary>A view of <c>pos pos</c> at offset 10.</summary>
            public RootPosView Pos => new(this.source.Slice(10), this.options);

            /// <summary><c>uint8 q</c> at offset 12.</summary>
            public byte Q => this.source.Slice(12, 1)[0];

            /// <summary><c>uint8 name_length</c> at offset 13.</summary>
            public byte NameLength => this.source.Slice(13, 1)[0];

            /// <summary>Reads the whole value with the generated reader (every member, runtime-sized ones included).</summary>
            /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
            /// <returns>The value.</returns>
            public Root ToObject(global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null)
            {
                var cursor = new global::CStructSharp.Generated.ReadCursor(this.source, this.options, "root");
                try
                {
                    return ReadRoot(ref cursor, variables, null, null);
                }
                catch (global::CStructSharp.Diagnostics.CStructException exception)
                {
                    cursor.Complete(exception);
                    throw;
                }
            }
        }

        /// <summary>
        ///     A zero-allocation view of one <c>choice</c> over its bytes: each statically placed member decodes
        ///     directly from the span when read; a member the view does not expose (runtime-sized, conditional, or placed after one)
        ///     is reached through <see cref="ToObject"/>. A view cannot leave the method that created it.
        /// </summary>
        public readonly ref struct RootChoiceView
        {
            private readonly global::System.ReadOnlySpan<byte> source;
            private readonly global::CStructSharp.ReadOptions? options;

            /// <summary>Creates a view over <paramref name="source"/>, whose first byte is the value's first byte; the source must hold the value's 2 bytes.</summary>
            /// <param name="source">The bytes, from the value's start; more may follow (pointer targets, the rest of the input).</param>
            /// <param name="options">The read options <see cref="ToObject"/> uses; <see langword="null"/> uses the documented defaults.</param>
            public RootChoiceView(global::System.ReadOnlySpan<byte> source, global::CStructSharp.ReadOptions? options = null)
            {
                if (source.Length < 2)
                {
                    var cursor = new global::CStructSharp.Generated.ReadCursor(source, options, "choice");
                    global::CStructSharp.Diagnostics.CStructException failure = cursor.Fail(global::CStructSharp.Generated.ReadCursor.ShortReadText(2, source.Length), null, null);
                    cursor.Complete(failure);
                    throw failure;
                }
                this.source = source;
                this.options = options;
            }

            /// <summary>Gets the value's bytes (its 2 bytes).</summary>
            public global::System.ReadOnlySpan<byte> Bytes => this.source.Slice(0, 2);

            /// <summary><c>uint8 narrow</c> at offset 0.</summary>
            public byte Narrow => this.source.Slice(0, 1)[0];

            /// <summary><c>uint16 wide</c> at offset 0.</summary>
            public ushort Wide => global::CStructSharp.Generated.Codec.ReadUInt16(this.source.Slice(0, 2), true);

            /// <summary>Reads the whole value with the generated reader (every member, runtime-sized ones included).</summary>
            /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
            /// <returns>The value.</returns>
            public RootChoice ToObject(global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null)
            {
                var cursor = new global::CStructSharp.Generated.ReadCursor(this.source, this.options, "choice");
                try
                {
                    return ReadRootChoice(ref cursor, variables, null, null);
                }
                catch (global::CStructSharp.Diagnostics.CStructException exception)
                {
                    cursor.Complete(exception);
                    throw;
                }
            }
        }

        /// <summary>
        ///     A zero-allocation view of one <c>pos</c> over its bytes: each statically placed member decodes
        ///     directly from the span when read; a member the view does not expose (runtime-sized, conditional, or placed after one)
        ///     is reached through <see cref="ToObject"/>. A view cannot leave the method that created it.
        /// </summary>
        public readonly ref struct RootPosView
        {
            private readonly global::System.ReadOnlySpan<byte> source;
            private readonly global::CStructSharp.ReadOptions? options;

            /// <summary>Creates a view over <paramref name="source"/>, whose first byte is the value's first byte; the source must hold the value's 2 bytes.</summary>
            /// <param name="source">The bytes, from the value's start; more may follow (pointer targets, the rest of the input).</param>
            /// <param name="options">The read options <see cref="ToObject"/> uses; <see langword="null"/> uses the documented defaults.</param>
            public RootPosView(global::System.ReadOnlySpan<byte> source, global::CStructSharp.ReadOptions? options = null)
            {
                if (source.Length < 2)
                {
                    var cursor = new global::CStructSharp.Generated.ReadCursor(source, options, "pos");
                    global::CStructSharp.Diagnostics.CStructException failure = cursor.Fail(global::CStructSharp.Generated.ReadCursor.ShortReadText(2, source.Length), null, null);
                    cursor.Complete(failure);
                    throw failure;
                }
                this.source = source;
                this.options = options;
            }

            /// <summary>Gets the value's bytes (its 2 bytes).</summary>
            public global::System.ReadOnlySpan<byte> Bytes => this.source.Slice(0, 2);

            /// <summary><c>uint8 x</c> at offset 0.</summary>
            public byte X => this.source.Slice(0, 1)[0];

            /// <summary><c>uint8 y</c> at offset 1.</summary>
            public byte Y => this.source.Slice(1, 1)[0];

            /// <summary>Reads the whole value with the generated reader (every member, runtime-sized ones included).</summary>
            /// <param name="variables">Values for the layout's free identifiers, or <see langword="null"/>.</param>
            /// <returns>The value.</returns>
            public RootPos ToObject(global::System.Collections.Generic.IReadOnlyDictionary<string, int>? variables = null)
            {
                var cursor = new global::CStructSharp.Generated.ReadCursor(this.source, this.options, "pos");
                try
                {
                    return ReadRootPos(ref cursor, variables, null, null);
                }
                catch (global::CStructSharp.Diagnostics.CStructException exception)
                {
                    cursor.Complete(exception);
                    throw;
                }
            }
        }
    }
}
