namespace CStructSharp.Generators;

using System;
using System.Globalization;
using CStructSharp.Codecs;

/// <summary>
///     The small pieces of C# text every emitter writes: literals, the file header, and the codec calls that decode or
///     encode one primitive. Each codec kind maps to its <c>Codec</c> method in one table, so the member-by-member
///     readers and writers, the views, the fixed readers and writers, and the mapped classes emit the same calls.
/// </summary>
internal static class Emit
{
    /// <summary>The generated-support class whose static methods decode and encode primitives.</summary>
    public const string CodecClass = "global::CStructSharp.Generated.Codec";

    /// <summary>
    ///     The attribute that keeps a member-by-member reader or writer out of its caller. Such a method is large, and
    ///     when the JIT inlines it into a hot caller it uses up that caller's inlining budget, so the small cursor and
    ///     codec helpers inside it stay calls; called, it keeps them inlined.
    /// </summary>
    public const string NoInlining = "[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]";

    /// <summary>An integer as a C# literal.</summary>
    /// <param name="value">The value.</param>
    /// <returns>The literal, formatted invariantly.</returns>
    public static string Int(int value) => value.ToString(CultureInfo.InvariantCulture);

    /// <summary>A boolean as a C# literal.</summary>
    /// <param name="value">The value.</param>
    /// <returns><c>true</c> or <c>false</c>.</returns>
    public static string Bool(bool value) => value ? "true" : "false";

    /// <summary>An XML documentation reference.</summary>
    /// <param name="target">The referenced member or type, as the <c>cref</c> attribute's text.</param>
    /// <returns>The <c>&lt;see cref="..."/&gt;</c> element.</returns>
    public static string Cref(string target) => "<see cref=\"" + target + "\"/>";

    /// <summary>Writes the header of a generated file: the auto-generated marker, its origin, and the file-wide pragmas.</summary>
    /// <param name="writer">The output.</param>
    /// <param name="origin">What the file is generated from (<c>the [CStructLayout] attribute on Packet</c>).</param>
    public static void FileHeader(SourceWriter writer, string origin)
    {
        writer.Line("// <auto-generated/>");
        writer.Line("// Generated by CStructSharp from " + origin + ". Do not edit.");
        writer.Line("#nullable enable");
        writer.Line("#pragma warning disable");
        writer.Line();
    }

    /// <summary>
    ///     Writes <paramref name="statement"/> so that a <c>CStructWriteException</c> it throws names the member, as the
    ///     runtime writer's failures do.
    /// </summary>
    /// <param name="writer">The output.</param>
    /// <param name="statement">The statement that can fail.</param>
    /// <param name="member">The member-name expression.</param>
    /// <param name="memberType">The member-type expression.</param>
    public static void WithMember(SourceWriter writer, string statement, string member, string memberType)
    {
        writer.Open("try");
        writer.Line(statement);
        writer.Close();
        writer.Open("catch (global::CStructSharp.Diagnostics.CStructWriteException exception)");
        writer.Line("throw cursor.WithMember(exception, " + member + ", " + memberType + ");");
        writer.Close();
    }

    /// <summary>Whether a codec stores its value as one plain byte (an unsigned byte or a one-byte text unit).</summary>
    /// <param name="kind">The codec kind.</param>
    /// <returns>Whether the byte itself is the value.</returns>
    public static bool IsPlainByte(PrimitiveCodecKind kind)
        => kind is PrimitiveCodecKind.UInt8 or PrimitiveCodecKind.Latin1 or PrimitiveCodecKind.Cp437 or PrimitiveCodecKind.Utf8Unit or PrimitiveCodecKind.Utf16LeUnit or PrimitiveCodecKind.Utf16BeUnit;

    /// <summary>
    ///     The <c>Codec</c> method suffix of a multi-byte fixed-width numeric: <c>Int16</c> for <c>ReadInt16</c> and
    ///     <c>WriteInt16</c>, <c>Char</c> for a wide character, <c>Half</c>, <c>Single</c> and <c>Double</c> for floats.
    /// </summary>
    /// <param name="kind">The codec kind.</param>
    /// <returns>The suffix, or <see langword="null"/> for any other kind.</returns>
    public static string? NumericSuffix(PrimitiveCodecKind kind) => kind switch
    {
        PrimitiveCodecKind.WChar => "Char",
        PrimitiveCodecKind.Int16 => "Int16",
        PrimitiveCodecKind.UInt16 => "UInt16",
        PrimitiveCodecKind.Int24 => "Int24",
        PrimitiveCodecKind.UInt24 => "UInt24",
        PrimitiveCodecKind.Int32 => "Int32",
        PrimitiveCodecKind.UInt32 => "UInt32",
        PrimitiveCodecKind.Int48 => "Int48",
        PrimitiveCodecKind.UInt48 => "UInt48",
        PrimitiveCodecKind.Int64 => "Int64",
        PrimitiveCodecKind.UInt64 => "UInt64",
        PrimitiveCodecKind.Int128 => "Int128",
        PrimitiveCodecKind.UInt128 => "UInt128",
        PrimitiveCodecKind.Float16 => "Half",
        PrimitiveCodecKind.Float32 => "Single",
        PrimitiveCodecKind.Float64 => "Double",
        _ => null,
    };

    /// <summary>The expression decoding one fixed-width numeric (including one-byte characters and wide integers).</summary>
    /// <param name="codec">The codec.</param>
    /// <param name="span">An expression for exactly the value's bytes.</param>
    /// <returns>The decode expression.</returns>
    /// <exception cref="InvalidOperationException">The codec is not a fixed-width numeric.</exception>
    public static string NumericDecode(PrimitiveCodec codec, string span)
    {
        if (IsPlainByte(codec.Kind))
        {
            return span + "[0]";
        }

        return codec.Kind switch
        {
            PrimitiveCodecKind.Int8 => "unchecked((sbyte)" + span + "[0])",
            PrimitiveCodecKind.Bool => span + "[0] != 0",
            PrimitiveCodecKind.Char => "(char)" + span + "[0]",
            _ => NumericSuffix(codec.Kind) is { } suffix
                     ? CodecClass + ".Read" + suffix + "(" + span + ", " + Bool(codec.LittleEndian) + ")"
                     : throw new InvalidOperationException("Codec is not a fixed-width numeric: " + codec.Kind),
        };
    }

    /// <summary>The statement storing one fixed-width numeric into <paramref name="span"/>.</summary>
    /// <param name="codec">The codec.</param>
    /// <param name="span">An expression for exactly the value's bytes.</param>
    /// <param name="access">The expression holding the value.</param>
    /// <returns>The store statement.</returns>
    /// <exception cref="InvalidOperationException">The codec is not a fixed-width numeric.</exception>
    public static string NumericStore(PrimitiveCodec codec, string span, string access)
    {
        if (IsPlainByte(codec.Kind))
        {
            return span + "[0] = " + access + ";";
        }

        return codec.Kind switch
        {
            PrimitiveCodecKind.Int8 => span + "[0] = unchecked((byte)" + access + ");",
            PrimitiveCodecKind.Bool => span + "[0] = (byte)(" + access + " ? 1 : 0);",
            PrimitiveCodecKind.Char => span + "[0] = " + CodecClass + ".ToNarrowCharacter(" + access + ");",
            _ => NumericSuffix(codec.Kind) is { } suffix
                     ? CodecClass + ".Write" + suffix + "(" + span + ", " + access + ", " + Bool(codec.LittleEndian) + ");"
                     : throw new InvalidOperationException("Codec is not a fixed-width numeric: " + codec.Kind),
        };
    }

    /// <summary>The storage of a fixed-point codec: the stored integer's width in bits, its fraction bits, and its signedness.</summary>
    /// <param name="kind">The codec kind.</param>
    /// <returns>The format, or <see langword="null"/> when the codec is not fixed point.</returns>
    public static (int Width, int Fraction, bool Signed)? FixedPoint(PrimitiveCodecKind kind) => kind switch
    {
        PrimitiveCodecKind.Fixed16_16 => (32, 16, true),
        PrimitiveCodecKind.UFixed16_16 => (32, 16, false),
        PrimitiveCodecKind.Fixed2_30 => (32, 30, true),
        PrimitiveCodecKind.UFixed8_8 => (16, 8, false),
        _ => null,
    };

    /// <summary>The expression decoding one fixed-point value.</summary>
    /// <param name="codec">A fixed-point codec.</param>
    /// <param name="span">An expression for exactly the value's bytes.</param>
    /// <returns>The decode expression.</returns>
    /// <exception cref="InvalidOperationException">The codec is not fixed point.</exception>
    public static string FixedPointDecode(PrimitiveCodec codec, string span)
    {
        (int width, int fraction, bool signed) = FixedPoint(codec.Kind) ?? throw new InvalidOperationException("Codec is not fixed point: " + codec.Kind);
        return CodecClass + ".DecodeFixedPoint(" + CodecClass + (signed ? ".ReadInt" : ".ReadUInt") + Int(width) + "(" + span + ", " + Bool(codec.LittleEndian) + "), " + Int(fraction) + ")";
    }

    /// <summary>
    ///     Whether an array of this codec is encoded in one call rather than element by element: every fixed-width
    ///     numeric except the three- and six-byte integers (range-checked per element) and one-byte characters
    ///     (whose encoding can reject a value).
    /// </summary>
    /// <param name="codec">The element codec.</param>
    /// <returns>Whether <see cref="BulkEncode"/> applies.</returns>
    public static bool CanBulkEncode(PrimitiveCodec codec)
        => codec.IsFixedWidthNumeric && codec.Kind is not (PrimitiveCodecKind.Int24 or PrimitiveCodecKind.UInt24 or PrimitiveCodecKind.Int48 or PrimitiveCodecKind.UInt48 or PrimitiveCodecKind.Char);

    /// <summary>The statement encoding a whole array of numbers into its bytes (see <see cref="CanBulkEncode"/>).</summary>
    /// <param name="codec">The element codec.</param>
    /// <param name="elementType">The C# element type.</param>
    /// <param name="source">The expression holding the array.</param>
    /// <param name="bytes">An expression for exactly the array's bytes.</param>
    /// <returns>The encode statement.</returns>
    public static string BulkEncode(PrimitiveCodec codec, string elementType, string source, string bytes)
    {
        if (IsPlainByte(codec.Kind))
        {
            return "new global::System.ReadOnlySpan<byte>(" + source + ").CopyTo(" + bytes + ");";
        }

        return codec.Kind switch
        {
            PrimitiveCodecKind.Int8 => "global::System.Runtime.InteropServices.MemoryMarshal.AsBytes<sbyte>(new global::System.ReadOnlySpan<sbyte>(" + source + ")).CopyTo(" + bytes + ");",
            PrimitiveCodecKind.Bool => CodecClass + ".EncodeBooleans(" + source + ", " + bytes + ");",
            _ => CodecClass + ".EncodeIntegers<" + elementType + ">(" + source + ", " + bytes + ", " + Bool(codec.LittleEndian) + ");",
        };
    }

    /// <summary>The statement decoding a whole array of numbers from its bytes into an existing array.</summary>
    /// <param name="codec">The element codec.</param>
    /// <param name="elementType">The C# element type.</param>
    /// <param name="bytes">An expression for exactly the array's bytes.</param>
    /// <param name="elements">The expression holding the destination array.</param>
    /// <returns>The decode statement.</returns>
    public static string BulkDecode(PrimitiveCodec codec, string elementType, string bytes, string elements)
    {
        string le = Bool(codec.LittleEndian);
        return codec.Kind switch
        {
            PrimitiveCodecKind.UInt8 => bytes + ".CopyTo(" + elements + ");",

            // An explicit writable span avoids C# 14 preferring the ReadOnlySpan overload for an array.
            PrimitiveCodecKind.Int8 => bytes + ".CopyTo(global::System.Runtime.InteropServices.MemoryMarshal.AsBytes<sbyte>(new global::System.Span<sbyte>(" + elements + ")));",
            PrimitiveCodecKind.Bool => CodecClass + ".DecodeBooleans(" + bytes + ", " + elements + ");",
            PrimitiveCodecKind.Int24 => CodecClass + ".DecodeInt24(" + bytes + ", " + elements + ", " + le + ");",
            PrimitiveCodecKind.UInt24 => CodecClass + ".DecodeUInt24(" + bytes + ", " + elements + ", " + le + ");",
            _ => CodecClass + ".DecodeIntegers<" + elementType + ">(" + bytes + ", " + elements + ", " + le + ");",
        };
    }
}
