namespace CStructSharp.Generators;

using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using CStructSharp.Codecs;
using CStructSharp.Compilation;
using Microsoft.CodeAnalysis;

/// <summary>
///     Emits the C# for one compiled layout into the attributed <c>static partial</c> class. The emitter is
///     organized by what the runtime does for the same layout: this file holds the class frame (the definition
///     text, the lazily built runtime <see cref="CStruct"/>, the root name); the partial files add the types and
///     the operations.
/// </summary>
internal sealed partial class LayoutEmitter
{
    private readonly LayoutRequest request;
    private readonly LayoutCompilation compilation;
    private readonly string definition;
    private readonly string rootName;
    private readonly List<Diagnostic> diagnostics = new();
    private GeneratedModel model = null!;
    private bool hasErrors;

    public LayoutEmitter(LayoutRequest request, LayoutCompilation compilation, string definition, string rootName)
    {
        this.request = request;
        this.compilation = compilation;
        this.definition = definition;
        this.rootName = rootName;
    }

    public bool HasErrors => this.hasErrors;

    /// <summary>The defines the compilation folded to values.</summary>
    public IReadOnlyDictionary<string, Syntax.Expr> StaticVariables => this.compilation.StaticLayoutVariables;

    /// <summary>The layout's <c>#define</c>s by name (for the ones that depend on caller variables).</summary>
    public IReadOnlyDictionary<string, Syntax.Defines> Definitions => this.definitions ??= this.CollectDefinitions();

    private Dictionary<string, Syntax.Defines>? definitions;

    private Dictionary<string, Syntax.Defines> CollectDefinitions()
    {
        var result = new Dictionary<string, Syntax.Defines>(System.StringComparer.Ordinal);
        foreach (KeyValuePair<string, Syntax.CStructElement> element in this.compilation.CStructElements)
        {
            if (element.Value is Syntax.Defines define)
            {
                result[element.Key] = define;
            }
        }

        return result;
    }

    /// <summary>The members every generated class has, which no generated type or the class itself may be named like.</summary>
    private static readonly string[] ReservedMembers =
    [
        "Layout", "RootName", "Definition", "Parse", "ParseAsync", "Serialize", "Write", "WriteAsync", "ParseWithDebug", "ResolveAddress", "GetArrayLength", "UpdatePath",
        "Sizes", "Offsets", "Update", "CreateCodecs", "CodecInstances", "LayoutInstance", "CreateLayout", "ToStructValue", "ToMapped", "SerializeMapped", "ParseMapped",
    ];

    private static string GeneratorVersion => typeof(LayoutEmitter).Assembly.GetName().Version?.ToString() ?? "0.0.0.0";

    /// <summary>Builds the type model, which assigns every generated name, and reports CSG003 for collisions.</summary>
    public IReadOnlyList<Diagnostic> Validate()
    {
        var taken = new Dictionary<string, string>(System.StringComparer.Ordinal)
        {
            [this.request.ClassName] = "the containing class",
        };
        foreach (string reserved in ReservedMembers)
        {
            taken[reserved] = "the generated " + reserved + " member";
        }

        // A C# type cannot have a member with its own name: a class named like a generated member cannot be generated into.
        if (System.Array.IndexOf(ReservedMembers, this.request.ClassName) >= 0)
        {
            this.Error(GeneratorDiagnostics.NameCollision, "The class '" + this.request.ClassName + "' is named like the generated " + this.request.ClassName + " member, which C# does not allow; rename the class.");
        }

        this.model = GeneratedModel.Build(this.compilation, this.request.KeepNames, taken, this.request.Views);
        foreach (string collision in this.model.Collisions)
        {
            this.Error(GeneratorDiagnostics.NameCollision, collision);
        }

        return this.diagnostics;
    }

    /// <summary>The complete generated file.</summary>
    public string Emit()
    {
        var writer = new SourceWriter();
        writer.Line("// <auto-generated/>");
        writer.Line("// Generated by CStructSharp from the [CStructLayout] attribute on " + this.request.ClassName + ". Do not edit.");
        writer.Line("#nullable enable");
        writer.Line("#pragma warning disable");
        writer.Line();
        if (this.request.Namespace is not null)
        {
            writer.Line("namespace " + this.request.Namespace);
            writer.Line("{");
            writer.Indent();
        }

        foreach (ContainingType container in this.request.ContainingTypes)
        {
            writer.Open("partial " + container.Keyword + " " + container.Name);
        }

        writer.Line("[global::System.CodeDom.Compiler.GeneratedCode(\"CStructSharp\", " + SourceWriter.Literal(GeneratorVersion) + ")]");
        writer.Open(this.request.Accessibility + " static partial class " + this.request.ClassName);
        this.EmitFrame(writer);
        this.EmitTypes(writer);
        this.EmitReaders(writer);
        this.EmitWriters(writer);
        this.EmitOperations(writer);
        this.EmitViews(writer);
        writer.Close();

        for (int index = 0; index < this.request.ContainingTypes.Count; index++)
        {
            writer.Close();
        }

        if (this.request.Namespace is not null)
        {
            writer.Outdent();
            writer.Line("}");
        }

        return writer.ToString();
    }

    private void Error(DiagnosticDescriptor descriptor, string message)
    {
        this.hasErrors = true;
        this.diagnostics.Add(Diagnostic.Create(descriptor, this.request.AttributeSpan.ToLocation(), message));
    }

    /// <summary>The members every generated class has: the definition, the runtime layout, and the root name.</summary>
    private void EmitFrame(SourceWriter writer)
    {
        writer.Line("/// <summary>The layout text the members of this class were generated from.</summary>");
        writer.Line("public const string Definition = " + SourceWriter.Literal(this.definition) + ";");
        writer.Line();
        writer.Line("/// <summary>The declaration the plain <see cref=\"Parse\"/> and <see cref=\"Serialize\"/> methods operate on.</summary>");
        writer.Line("public const string RootName = " + SourceWriter.Literal(this.rootName) + ";");
        writer.Line();
        writer.Line("private static readonly global::System.Lazy<global::CStructSharp.CStruct> LayoutInstance = new(CreateLayout, global::System.Threading.LazyThreadSafetyMode.ExecutionAndPublication);");
        writer.Line();
        writer.Line("/// <summary>The runtime <see cref=\"global::CStructSharp.CStruct\"/> for the same definition and options, built on first use: introspection, JSON, memory images, and the parity oracle.</summary>");
        writer.Line("public static global::CStructSharp.CStruct Layout => LayoutInstance.Value;");
        writer.Line();
        if (this.request.Codecs.Count > 0)
        {
            this.EmitCodecInstances(writer);
        }

        writer.Open("private static global::CStructSharp.CStruct CreateLayout()");
        writer.Line("var options = new global::CStructSharp.CStructCompilationOptions");
        writer.Line("{");
        writer.Indent();
        if (this.request.Codecs.Count > 0)
        {
            writer.Line("Codecs = CodecInstances.Value,");
        }

        writer.Line("CLongWidth = " + (this.request.CLongWidth == 0 ? 64 : this.request.CLongWidth).ToString(CultureInfo.InvariantCulture) + ",");
        writer.Line("BitfieldPacking = global::CStructSharp.BitfieldPacking." + this.request.BitfieldPacking + ",");
        writer.Line("BitfieldAllocation = global::CStructSharp.BitfieldAllocation." + this.request.BitfieldAllocation + ",");
        if (this.request.DefaultEnumStorage is not null)
        {
            writer.Line("DefaultEnumStorage = " + SourceWriter.Literal(this.request.DefaultEnumStorage) + ",");
        }

        if (this.request.Defined.Count > 0)
        {
            writer.Write("Defined = new global::System.Collections.Generic.HashSet<string>(global::System.StringComparer.Ordinal) { ");
            foreach (string symbol in this.request.Defined)
            {
                writer.Write(SourceWriter.Literal(symbol) + ", ");
            }

            writer.Line("},");
        }

        writer.Outdent();
        writer.Line("};");
        writer.Line(
            "return new global::CStructSharp.CStruct(Definition, pointerSize: " + this.request.PointerSize.ToString(CultureInfo.InvariantCulture) +
            ", aligned: " + (this.request.Aligned ? "true" : "false") +
            ", isLittleEndian: " + (this.request.LittleEndian ? "true" : "false") + ", compilationOptions: options);");
        writer.Close();
    }

    /// <summary>
    ///     The custom codec instances: the class implements <c>CreateCodecs()</c>; the first use checks every instance
    ///     against the attribute's declaration (name, fixed size, alignment) because the generated placement relied
    ///     on those facts at build time.
    /// </summary>
    private void EmitCodecInstances(SourceWriter writer)
    {
        const string CodecType = "global::CStructSharp.Codecs.ICustomCodec";
        writer.Line("/// <summary>Supplies the custom codec instances the layout declares (<c>" + string.Join(", ", this.request.Codecs) + "</c>), one per declaration and in that order.</summary>");
        writer.Line("/// <returns>The codec instances.</returns>");
        writer.Line("private static partial global::System.Collections.Generic.IReadOnlyList<" + CodecType + "> CreateCodecs();");
        writer.Line();
        writer.Line("private static readonly global::System.Lazy<" + CodecType + "[]> CodecInstances = new(ResolveCodecs, global::System.Threading.LazyThreadSafetyMode.ExecutionAndPublication);");
        writer.Line();
        writer.Open("private static " + CodecType + "[] ResolveCodecs()");
        writer.Line("global::System.Collections.Generic.IReadOnlyList<" + CodecType + "> supplied = CreateCodecs() ?? throw new global::System.InvalidOperationException(\"CreateCodecs() returned null; return one ICustomCodec per declared codec.\");");
        writer.Line("string[] expected = { " + string.Join(", ", this.request.Codecs.Select(declaration => SourceWriter.Literal(Expected(declaration)))) + " };");
        writer.Open("if (supplied.Count != expected.Length)");
        writer.Line("throw new global::System.InvalidOperationException(\"CreateCodecs() returned \" + supplied.Count.ToString(global::System.Globalization.CultureInfo.InvariantCulture) + \" codecs; the layout declares \" + expected.Length.ToString(global::System.Globalization.CultureInfo.InvariantCulture) + \".\");");
        writer.Close();
        writer.Line("var instances = new " + CodecType + "[expected.Length];");
        writer.Open("for (int index = 0; index < expected.Length; index++)");
        writer.Line(CodecType + " codec = supplied[index] ?? throw new global::System.InvalidOperationException(\"CreateCodecs() returned null for codec \" + expected[index] + \".\");");
        writer.Line("string actual = codec.Name + \":\" + (codec.FixedSize is { } size ? size.ToString(global::System.Globalization.CultureInfo.InvariantCulture) : \"*\") + \":\" + codec.Alignment.ToString(global::System.Globalization.CultureInfo.InvariantCulture);");
        writer.Open("if (actual != expected[index])");
        writer.Line("throw new global::System.InvalidOperationException(\"Custom codec \" + expected[index] + \" is declared in [CStructLayout(Codecs = ...)] but the instance from CreateCodecs() reports \" + actual + \" (name:size:alignment); the generated placement depends on the declaration.\");");
        writer.Close();
        writer.Line("instances[index] = codec;");
        writer.Close();
        writer.Line("return instances;");
        writer.Close();
        writer.Line();
    }

    /// <summary>A declaration in its canonical <c>name:size:alignment</c> spelling (the generated check compares against it).</summary>
    private static string Expected(string declaration)
        => CustomCodecDeclaration.TryParse(declaration, out CustomCodecDescriptor descriptor) ? CustomCodecDeclaration.Describe(descriptor) : declaration;

    /// <summary>The index of a custom codec's instance in <c>CodecInstances</c>: the position of its declaration.</summary>
    private int CodecIndex(string typeName)
    {
        for (int index = 0; index < this.request.Codecs.Count; index++)
        {
            if (CustomCodecDeclaration.TryParse(this.request.Codecs[index], out CustomCodecDescriptor descriptor) && descriptor.Name == typeName)
            {
                return index;
            }
        }

        throw new InvalidOperationException("No declared custom codec named " + typeName);
    }
}
