namespace CStructSharp.Generators;

using System.Collections.Generic;
using System.Globalization;
using CStructSharp.Compilation;
using Microsoft.CodeAnalysis;

/// <summary>
///     Emits the C# for one compiled layout into the attributed <c>static partial</c> class. The emitter is
///     organized by what the runtime does for the same layout: this file holds the class frame (the definition
///     text, the lazily built runtime <see cref="CStruct"/>, the root name); the partial files add the types and
///     the operations.
/// </summary>
internal sealed partial class LayoutEmitter
{
    private readonly LayoutRequest request;
    private readonly LayoutCompilation compilation;
    private readonly string definition;
    private readonly string rootName;
    private readonly List<Diagnostic> diagnostics = new();
    private GeneratedModel model = null!;
    private bool hasErrors;

    public LayoutEmitter(LayoutRequest request, LayoutCompilation compilation, string definition, string rootName)
    {
        this.request = request;
        this.compilation = compilation;
        this.definition = definition;
        this.rootName = rootName;
    }

    public bool HasErrors => this.hasErrors;

    private static string GeneratorVersion => typeof(LayoutEmitter).Assembly.GetName().Version?.ToString() ?? "0.0.0.0";

    /// <summary>Builds the type model, which assigns every generated name, and reports CSG003 for collisions.</summary>
    public IReadOnlyList<Diagnostic> Validate()
    {
        var taken = new Dictionary<string, string>(System.StringComparer.Ordinal)
        {
            [this.request.ClassName] = "the containing class",
            ["Layout"] = "the generated Layout property",
            ["RootName"] = "the generated RootName property",
            ["Definition"] = "the generated Definition constant",
            ["Parse"] = "the generated Parse method",
            ["Serialize"] = "the generated Serialize method",
        };
        this.model = GeneratedModel.Build(this.compilation, this.request.KeepNames, taken);
        foreach (string collision in this.model.Collisions)
        {
            this.Error(GeneratorDiagnostics.NameCollision, collision);
        }

        return this.diagnostics;
    }

    /// <summary>The complete generated file.</summary>
    public string Emit()
    {
        var writer = new SourceWriter();
        writer.Line("// <auto-generated/>");
        writer.Line("// Generated by CStructSharp from the [CStructLayout] attribute on " + this.request.ClassName + ". Do not edit.");
        writer.Line("#nullable enable");
        writer.Line("#pragma warning disable");
        writer.Line();
        if (this.request.Namespace is not null)
        {
            writer.Line("namespace " + this.request.Namespace);
            writer.Line("{");
            writer.Indent();
        }

        foreach (ContainingType container in this.request.ContainingTypes)
        {
            writer.Open("partial " + container.Keyword + " " + container.Name);
        }

        writer.Line("[global::System.CodeDom.Compiler.GeneratedCode(\"CStructSharp\", " + SourceWriter.Literal(GeneratorVersion) + ")]");
        writer.Open(this.request.Accessibility + " static partial class " + this.request.ClassName);
        this.EmitFrame(writer);
        this.EmitTypes(writer);
        writer.Close();

        for (int index = 0; index < this.request.ContainingTypes.Count; index++)
        {
            writer.Close();
        }

        if (this.request.Namespace is not null)
        {
            writer.Outdent();
            writer.Line("}");
        }

        return writer.ToString();
    }

    private void Error(DiagnosticDescriptor descriptor, string message)
    {
        this.hasErrors = true;
        this.diagnostics.Add(Diagnostic.Create(descriptor, this.request.AttributeSpan.ToLocation(), message));
    }

    /// <summary>The members every generated class has: the definition, the runtime layout, and the root name.</summary>
    private void EmitFrame(SourceWriter writer)
    {
        writer.Line("/// <summary>The layout text the members of this class were generated from.</summary>");
        writer.Line("public const string Definition = " + SourceWriter.Literal(this.definition) + ";");
        writer.Line();
        writer.Line("/// <summary>The declaration the plain <see cref=\"Parse\"/> and <see cref=\"Serialize\"/> methods operate on.</summary>");
        writer.Line("public const string RootName = " + SourceWriter.Literal(this.rootName) + ";");
        writer.Line();
        writer.Line("private static readonly global::System.Lazy<global::CStructSharp.CStruct> LayoutInstance = new(CreateLayout, global::System.Threading.LazyThreadSafetyMode.ExecutionAndPublication);");
        writer.Line();
        writer.Line("/// <summary>The runtime <see cref=\"global::CStructSharp.CStruct\"/> for the same definition and options, built on first use: introspection, JSON, memory images, and the parity oracle.</summary>");
        writer.Line("public static global::CStructSharp.CStruct Layout => LayoutInstance.Value;");
        writer.Line();
        writer.Open("private static global::CStructSharp.CStruct CreateLayout()");
        writer.Line("var options = new global::CStructSharp.CStructCompilationOptions");
        writer.Line("{");
        writer.Indent();
        writer.Line("CLongWidth = " + (this.request.CLongWidth == 0 ? 64 : this.request.CLongWidth).ToString(CultureInfo.InvariantCulture) + ",");
        writer.Line("BitfieldPacking = global::CStructSharp.BitfieldPacking." + this.request.BitfieldPacking + ",");
        writer.Line("BitfieldAllocation = global::CStructSharp.BitfieldAllocation." + this.request.BitfieldAllocation + ",");
        if (this.request.DefaultEnumStorage is not null)
        {
            writer.Line("DefaultEnumStorage = " + SourceWriter.Literal(this.request.DefaultEnumStorage) + ",");
        }

        if (this.request.Defined.Count > 0)
        {
            writer.Write("Defined = new global::System.Collections.Generic.HashSet<string>(global::System.StringComparer.Ordinal) { ");
            foreach (string symbol in this.request.Defined)
            {
                writer.Write(SourceWriter.Literal(symbol) + ", ");
            }

            writer.Line("},");
        }

        writer.Outdent();
        writer.Line("};");
        writer.Line(
            "return new global::CStructSharp.CStruct(Definition, pointerSize: " + this.request.PointerSize.ToString(CultureInfo.InvariantCulture) +
            ", aligned: " + (this.request.Aligned ? "true" : "false") +
            ", isLittleEndian: " + (this.request.LittleEndian ? "true" : "false") + ", compilationOptions: options);");
        writer.Close();
    }
}
