<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net10.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><EnableDefaultCompileItems>false</EnableDefaultCompileItems><RunAnalyzers>false</RunAnalyzers></PropertyGroup>
  <ItemGroup><Compile Include="Program.cs" /><ProjectReference Include="$(LibraryRoot)/src/CStructSharp/CStructSharp.csproj" /></ItemGroup>
</Project>
